; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_2_=music_data_2_
.endif

music_data_2_:
	.byte 7
	.word @2_instruments
	.word @2_samples-5
	.word @2_song0ch0,@2_song0ch1,@2_song0ch2,@2_song0ch3,@2_song0ch4,307,256 ; 00 : DPCM ALIGNER (NOT FOR PLAYBACK)
	.word @2_song1ch0,@2_song1ch1,@2_song1ch2,@2_song1ch3,@2_song1ch4,307,256 ; 01 : The Death That I Deservioli
	.word @2_song2ch0,@2_song2ch1,@2_song2ch2,@2_song2ch3,@2_song2ch4,307,256 ; 02 : Oregano Mirage
	.word @2_song3ch0,@2_song3ch1,@2_song3ch2,@2_song3ch3,@2_song3ch4,307,256 ; 03 : A Grain of Bread in a Grain of Sand
	.word @2_song4ch0,@2_song4ch1,@2_song4ch2,@2_song4ch3,@2_song4ch4,307,256 ; 04 : Unexpectancy (3)
	.word @2_song5ch0,@2_song5ch1,@2_song5ch2,@2_song5ch3,@2_song5ch4,307,256 ; 05 : bye bye there!
	.word @2_song6ch0,@2_song6ch1,@2_song6ch2,@2_song6ch3,@2_song6ch4,307,256 ; 06 : Hip to be Italian

.export music_data_2_
.global FAMISTUDIO_DPCM_PTR

@2_instruments:
	.word @2_env15,@2_env33,@2_env24,@2_env0 ; 00 : 0 12 arp 1
	.word @2_env31,@2_env20,@2_env24,@2_env0 ; 01 : ah 1
	.word @2_env13,@2_env20,@2_env24,@2_env0 ; 02 : blank
	.word @2_env19,@2_env20,@2_env11,@2_env0 ; 03 : distort guitar
	.word @2_env10,@2_env1,@2_env25,@2_env0 ; 04 : electric guit
	.word @2_env17,@2_env6,@2_env4,@2_env0 ; 05 : funny guitar
	.word @2_env28,@2_env20,@2_env24,@2_env0 ; 06 : Instrument 1
	.word @2_env9,@2_env20,@2_env2,@2_env0 ; 07 : Instrument 2
	.word @2_env35,@2_env20,@2_env3,@2_env0 ; 08 : New instrument 1
	.word @2_env34,@2_env23,@2_env24,@2_env0 ; 09 : noise (get it) kick
	.word @2_env14,@2_env7,@2_env24,@2_env0 ; 0a : noise hat
	.word @2_env16,@2_env7,@2_env24,@2_env0 ; 0b : noise open hat
	.word @2_env18,@2_env22,@2_env24,@2_env0 ; 0c : noise snare
	.word @2_env13,@2_env20,@2_env24,@2_env0 ; 0d : Orchestral Hits
	.word @2_env29,@2_env20,@2_env26,@2_env0 ; 0e : secret square

@2_env0:
	.byte $00,$c0,$7f,$00,$02
@2_env1:
	.byte $c0,$b8,$b4,$b8,$c0,$00,$04
@2_env2:
	.byte $c2,$c3,$00,$01
@2_env3:
	.byte $c3,$7f,$00,$00
@2_env4:
	.byte $c2,$c0,$00,$01
@2_env5:
	.byte $00,$c0,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$00,$01
@2_env6:
	.byte $c7,$c0,$00,$01
@2_env7:
	.byte $be,$c0,$00,$01
@2_env8:
	.byte $00,$c0,$bf,$be,$be,$bf,$c1,$c2,$c2,$c1,$00,$01
@2_env9:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$10
@2_env10:
	.byte $06,$c1,$c2,$c5,$00,$03,$c3,$c2,$c1,$c1,$c0,$00,$0a
@2_env11:
	.byte $c3,$07,$c2,$07,$c1,$07,$c0,$07,$c1,$07,$c2,$06,$c2,$00,$00
@2_env12:
	.byte $00,$c0,$bf,$03,$c0,$c0,$c1,$02,$c1,$00,$01
@2_env13:
	.byte $00,$cf,$7f,$00,$02
@2_env14:
	.byte $00,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@2_env15:
	.byte $00,$c2,$c4,$00,$02
@2_env16:
	.byte $00,$c5,$c4,$c3,$00,$03
@2_env17:
	.byte $06,$c7,$c5,$c4,$00,$03,$c3,$c2,$c1,$c0,$00,$09
@2_env18:
	.byte $00,$ca,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$0b
@2_env19:
	.byte $06,$cf,$cb,$c8,$00,$03,$c5,$c3,$c2,$c2,$c1,$02,$c0,$c0,$00,$0d
@2_env20:
	.byte $c0,$7f,$00,$01
@2_env21:
	.byte $c0,$cc,$cc,$00,$00
@2_env22:
	.byte $c6,$ca,$00,$01
@2_env23:
	.byte $c6,$cd,$00,$01
@2_env24:
	.byte $7f,$00,$00
@2_env25:
	.byte $c2,$7f,$00,$00
@2_env26:
	.byte $c0,$c2,$00,$01
@2_env27:
	.byte $00,$c0,$bf,$be,$02,$bf,$c1,$c2,$02,$c1,$00,$01
@2_env28:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1f
@2_env29:
	.byte $0a,$c2,$c3,$c4,$02,$c3,$c3,$c2,$00,$07,$c2,$04,$c1,$07,$c0,$04,$c0,$00,$10
@2_env30:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@2_env31:
	.byte $07,$c2,$c4,$c5,$c4,$00,$04,$c4,$c4,$c3,$04,$c2,$07,$c1,$0a,$c0,$00,$0f
@2_env32:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01
@2_env33:
	.byte $c0,$c0,$cc,$cc,$00,$00
@2_env34:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@2_env35:
	.byte $06,$c5,$c8,$c6,$00,$03,$c5,$c4,$c3,$c3,$c2,$03,$c1,$06,$c0,$00,$0e
@2_env36:
	.byte $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01

@2_samples:
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4f,$40,$00 ; 00 arpeggiosquare.dmc (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$45,$2e,$01 ; 01 b1 bass.dmc (Pitch:5)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$47,$2e,$01 ; 02 b1 bass.dmc (Pitch:7)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$5f,$45,$00,$00 ; 03 b2 bass.dmc (Pitch:5)
	.byte $62+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$47,$00,$01 ; 04 b3 bass.dmc (Pitch:7)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4a,$00,$00 ; 05 dash.dmc (Pitch:10)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4d,$00,$00 ; 06 dash.dmc (Pitch:13)
	.byte $79+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0f,$40,$00 ; 07 Hebereke Kick.dmc (Pitch:15)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0c,$40,$00 ; 08 Hebereke Snare.dmc (Pitch:12)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0d,$40,$00 ; 09 Hebereke Snare.dmc (Pitch:13)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0e,$40,$00 ; 0a Hebereke Snare.dmc (Pitch:14)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0f,$40,$00 ; 0b Hebereke Snare.dmc (Pitch:15)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$00 ; 0c OrchHitA.dmc (Pitch:7)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$00 ; 0d OrchHitA.dmc (Pitch:8)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$00 ; 0e OrchHitA.dmc (Pitch:10)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$00 ; 0f OrchHitA.dmc (Pitch:11)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$00 ; 10 OrchHitA.dmc (Pitch:12)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 11 OrchHitA.dmc (Pitch:14)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 12 OrchHitA.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 13 OrchHitF.dmc (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 14 OrchHitF.dmc (Pitch:15)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$00 ; 15 OrchHitF#.dmc (Pitch:13)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 16 OrchHitF#.dmc (Pitch:14)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 17 OrchHitF#.dmc (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 18 OrchHitG.dmc (Pitch:1)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$02,$00,$01 ; 19 OrchHitG.dmc (Pitch:2)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 1a OrchHitG.dmc (Pitch:3)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 1b OrchHitG.dmc (Pitch:4)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$05,$00,$01 ; 1c OrchHitG.dmc (Pitch:5)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 1d OrchHitG.dmc (Pitch:6)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 1e OrchHitG.dmc (Pitch:7)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 1f OrchHitG.dmc (Pitch:9)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 20 OrchHitG.dmc (Pitch:10)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 21 OrchHitG.dmc (Pitch:12)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$01 ; 22 OrchHitG.dmc (Pitch:13)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 23 OrchHitG.dmc (Pitch:14)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 24 OrchHitG.dmc (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 25 OrchHitG#.dmc (Pitch:1)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 26 OrchHitG#.dmc (Pitch:3)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 27 OrchHitG#.dmc (Pitch:4)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 28 OrchHitG#.dmc (Pitch:6)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 29 OrchHitG#.dmc (Pitch:7)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$01 ; 2a OrchHitG#.dmc (Pitch:8)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 2b OrchHitG#.dmc (Pitch:9)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 2c OrchHitG#.dmc (Pitch:10)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$01 ; 2d OrchHitG#.dmc (Pitch:11)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 2e OrchHitG#.dmc (Pitch:12)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 2f OrchHitG#.dmc (Pitch:14)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 30 OrchHitG#.dmc (Pitch:15)
	.byte $74+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0d,$00,$00 ; 31 Pac_Kick44 (Pitch:13)
	.byte $74+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0e,$00,$00 ; 32 Pac_Kick44 (Pitch:14)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$00,$00 ; 33 Pac_Kick64 (Pitch:13)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0e,$00,$00 ; 34 Pac_Kick64 (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$44,$0f,$00,$01 ; 35 taunt.dmc (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$2f,$07,$00,$00 ; 36 untitled.dmc (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$34,$08,$00,$00 ; 37 untitled1.dmc (Pitch:8)

@2_song0ch0:
	.byte $45, $01, $ff, $ff, $ff, $ff
@2_song0ch0loop:
	.byte $00, $42
	.word @2_song0ch0loop
@2_song0ch1:
	.byte $ff, $ff, $ff, $ff
@2_song0ch1loop:
	.byte $00, $42
	.word @2_song0ch1loop
@2_song0ch2:
	.byte $ff, $ff, $ff, $ff
@2_song0ch2loop:
	.byte $00, $42
	.word @2_song0ch2loop
@2_song0ch3:
	.byte $ff, $ff, $ff, $ff
@2_song0ch3loop:
	.byte $00, $42
	.word @2_song0ch3loop
@2_song0ch4:
	.byte $34, $35, $32, $37, $33, $38, $06, $07, $36, $08, $0c, $0b, $0a, $09, $01, $13, $31, $25, $18, $15, $12, $30, $24, $17
	.byte $14, $23, $16, $11, $2f, $22, $10, $2e, $0f, $2d, $21, $2c, $20, $0e, $2b, $0d, $2a, $1f, $29, $1e, $1d, $28, $1c, $27
	.byte $1b, $1a, $26, $19, $05, $03, $04, $02, $00, $ff, $ff, $ff, $8d
@2_song0ch4loop:
	.byte $00, $42
	.word @2_song0ch4loop
@2_song1ch0:
	.byte $45, $02
@2_song1ch0loop:
	.byte $74, $8c
@2_song1ref6:
	.byte $1b, $89
@2_song1ref8:
	.byte $4f, $80, $27, $2e, $43, $22, $87, $4f, $b9, $2e, $33, $43, $27, $87, $4f, $6b, $33, $27, $81, $43, $1b, $85
	.byte $41, $0a
	.word @2_song1ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87
	.byte $41, $0c
	.word @2_song1ref6
	.byte $41, $0a
	.word @2_song1ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87
	.byte $41, $0c
	.word @2_song1ref6
	.byte $41, $0a
	.word @2_song1ref8
@2_song1ref59:
	.byte $4f, $80, $27, $2e, $43, $22, $87, $4f, $7f, $2e, $25, $43, $19, $87, $4f, $80, $25, $2c, $43, $20, $87, $4f, $b0, $2c
	.byte $31, $43, $25, $87, $4f, $77, $31, $25, $81, $43, $19, $85, $4f, $89, $25, $31, $81, $43, $25, $85, $4f, $50, $31, $2c
	.byte $43, $20, $87, $4f, $7f, $2c, $25, $43, $19, $87, $4f, $80, $25, $2c, $43, $20, $87
	.byte $41, $0c
	.word @2_song1ref6
	.byte $41, $0a
	.word @2_song1ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87
	.byte $41, $0c
	.word @2_song1ref6
	.byte $41, $0a
	.word @2_song1ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87
	.byte $41, $0c
	.word @2_song1ref6
	.byte $41, $0a
	.word @2_song1ref8
	.byte $41, $1d
	.word @2_song1ref59
	.byte $4f, $6b, $2c, $27, $43, $1b, $87
	.byte $41, $0a
	.word @2_song1ref8
	.byte $41, $0a
	.word @2_song1ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87, $4f, $7f, $2e, $27, $43, $1b, $85, $46, $00, $4f, $9a, $27, $2e, $81, $43, $22, $85
	.byte $4f, $b9, $2e, $33, $43, $27, $85, $46, $00, $4f, $7f, $33, $27, $81, $43, $1b, $85, $4f, $80, $27, $2e, $43, $22, $85
	.byte $46, $00, $4f, $80, $2e, $33, $43, $27, $87, $4f, $6b, $33, $27, $81, $43, $1b, $83, $46, $00, $4f, $9a, $27, $2e, $81
	.byte $43, $22, $85, $4f, $7f, $2e, $27, $43, $1b, $85
@2_song1ref254:
	.byte $4f, $80, $27, $2e, $43, $22, $85, $4f, $b9, $2e, $33, $43, $27, $85, $4f, $6b, $33, $27, $81, $43, $1b, $83
	.byte $41, $0a
	.word @2_song1ref254
	.byte $4f, $80, $27, $2e, $43, $22, $85, $4f, $7f, $2e, $25, $43, $19, $83, $46, $00, $4f, $8e, $25, $2c, $81, $43, $20, $83
	.byte $4f, $b0, $2c, $31, $43, $25, $83, $46, $00, $4f, $7f, $31, $25, $81, $43, $19, $83, $4f, $89, $25, $31, $81, $43, $25
	.byte $81, $46, $00, $4f, $7f, $31, $2c, $43, $20, $85, $4f, $7f, $2c, $25, $43, $19, $83, $46, $00, $4f, $8e, $25, $2c, $81
	.byte $43, $20, $83, $4f, $6b, $2c, $27, $43, $1b, $83
@2_song1ref361:
	.byte $4f, $80, $27, $2e, $43, $22, $83, $4f, $b9, $2e, $33, $43, $27, $83, $4f, $6b, $33, $27, $81, $43, $1b, $81
	.byte $41, $0a
	.word @2_song1ref361
	.byte $4f, $80, $27, $2e, $43, $22, $83, $4f, $7f, $2e, $27, $43, $1b, $81, $46, $00, $4f, $9a, $27, $2e, $81, $43, $22, $81
	.byte $4f, $b9, $2e, $33, $43, $27, $81, $46, $00, $4f, $7f, $33, $27, $81
@2_song1ref424:
	.byte $43, $1b, $81, $4f, $80, $27, $2e, $43, $22, $81, $46, $00, $4f, $80, $2e, $33, $43, $27, $83, $4f, $6b, $33, $27, $81
	.byte $43, $1b, $4f, $80, $27, $2e, $43, $22, $83, $4f, $7f, $2e, $27
	.byte $41, $0d
	.word @2_song1ref424
	.byte $81, $46, $00, $4f, $80, $2e, $33, $43, $27, $83, $4f, $6b, $33, $27, $81, $43, $1b, $46, $00, $4f, $9a, $27, $2e, $81
	.byte $43, $22, $73, $84, $4f, $7f, $2e, $25, $43, $19, $81, $72, $4f, $80, $25, $2c, $43, $20, $81, $71, $4f, $b0, $2c, $31
	.byte $43, $25, $81, $4f, $77, $31, $25, $81, $43, $19, $4f, $89, $25, $31, $81, $43, $25, $4f, $50, $31, $2c, $43, $20, $81
	.byte $72, $4f, $7f, $2c, $25, $43, $19, $81, $73
@2_song1ref545:
	.byte $4f, $80, $25, $2c, $43, $20, $81
@2_song1ref552:
	.byte $4f, $6b, $2c, $27
@2_song1ref556:
	.byte $43, $1b, $46, $00, $4f, $80, $27, $2e, $43, $22, $81, $4f, $b9, $2e, $33, $43, $27, $46, $00, $4f, $7f, $33, $27, $43
	.byte $1b, $81, $4f, $80, $27, $2e, $43, $22, $46, $00, $4f, $80, $2e, $33, $43, $27, $81, $4f, $7f, $33, $27, $43, $1b, $46
	.byte $00, $4f, $80, $27, $2e, $43, $22, $81, $4f, $7f, $2e, $27
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
@2_song1ref622:
	.byte $4f, $7f, $2e, $25, $43, $19, $46, $00, $4f, $80, $25, $2c, $43, $20, $81, $4f, $b0, $2c, $31, $43, $25, $46, $00, $4f
	.byte $7f, $31, $25, $43, $19, $81, $4f, $80, $25, $31, $43, $25, $46, $00, $4f, $7f, $31, $2c, $43, $20, $81, $4f, $7f, $2c
	.byte $25, $43, $19, $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
@2_song1ref757:
	.byte $46, $00, $4f, $80, $25, $2c, $43, $20, $81, $75, $8c, $4f, $80, $2c, $3a, $43, $2e, $85, $4f, $12, $3a, $38, $43, $2c
	.byte $85, $4f, $ee, $38, $3a, $43, $2e, $85, $4f, $12, $3a, $38, $43, $2c, $85, $4f, $1e, $38, $35, $43, $29, $85, $4f, $f5
	.byte $35, $36, $43, $2a, $85, $4f, $0b, $36, $35, $43, $29, $85, $4f, $32, $35, $31, $43, $25, $85, $4f, $e5, $31, $33, $43
	.byte $27, $85, $4f, $1b, $33, $31, $43, $25, $85, $74, $4f, $e5, $31, $33, $43, $27, $85, $4f, $1b, $33, $31, $43, $25, $85
	.byte $73, $4f, $e5, $31, $33, $43, $27, $85, $4f, $1b, $33, $31, $43, $25, $85, $72, $4f, $e5, $31, $33, $43, $27, $85, $4f
	.byte $1b, $33, $31, $43, $25, $85, $73, $84
	.byte $41, $15
	.word @2_song1ref552
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $46, $00
	.byte $41, $18
	.word @2_song1ref545
	.byte $41, $14
	.word @2_song1ref556
	.byte $41, $13
	.word @2_song1ref556
	.byte $41, $11
	.word @2_song1ref622
	.byte $41, $33
	.word @2_song1ref757
	.byte $7c, $86
@2_song1ref986:
	.byte $4f, $7f, $31, $11, $87, $43, $05
@2_song1ref993:
	.byte $44, $85, $05, $43, $05, $85, $44, $87, $05, $43, $05, $85, $05, $43, $05, $85, $4f, $7f, $11, $0f, $43, $03, $85, $4f
	.byte $80, $0f, $11, $43, $05, $85, $44, $87, $4f, $7f, $11, $0f, $43, $03, $85, $4f, $80, $0f, $11, $43, $05, $85, $4f, $80
	.byte $11, $14, $43, $08, $ad, $4f, $7f, $14, $11, $43, $05, $87
	.byte $41, $1b
	.word @2_song1ref993
	.byte $4f, $80, $11, $16, $43, $0a, $99, $4f, $84, $16, $18, $43, $0c, $8f
	.byte $41, $21
	.word @2_song1ref986
	.byte $42
	.word @2_song1ch0loop
@2_song1ch1:
@2_song1ch1loop:
	.byte $89, $71
@2_song1ref1079:
	.byte $4d, $01, $8c
@2_song1ref1082:
	.byte $1b, $89, $22, $89, $27, $89, $1b, $89, $22, $89, $27, $89, $1b, $89, $22, $89, $4d, $01
	.byte $41, $10
	.word @2_song1ref1082
	.byte $4d, $01
	.byte $41, $10
	.word @2_song1ref1082
@2_song1ref1108:
	.byte $84, $19, $89, $20, $89, $25, $89, $19, $89, $25, $89, $20, $89, $19, $89, $20, $89
	.byte $41, $10
	.word @2_song1ref1079
	.byte $4d, $01
	.byte $41, $10
	.word @2_song1ref1082
	.byte $4d, $01
	.byte $41, $10
	.word @2_song1ref1082
	.byte $41, $10
	.word @2_song1ref1108
	.byte $41, $10
	.word @2_song1ref1079
	.byte $4d, $01
	.byte $41, $0d
	.word @2_song1ref1082
	.byte $83, $85, $00, $81, $4d, $01
	.byte $41, $0b
	.word @2_song1ref1082
	.byte $87, $81, $00, $85, $4d, $01
	.byte $41, $0c
	.word @2_song1ref1082
	.byte $4d, $01
	.byte $41, $09
	.word @2_song1ref1082
@2_song1ref1172:
	.byte $83, $85, $00, $81, $4d, $01, $1b, $89, $22, $89, $27, $89, $1b, $87, $81, $00, $85, $4d, $01, $1b, $89, $22, $89, $27
	.byte $89, $1b
	.byte $41, $0b
	.word @2_song1ref1172
	.byte $7c, $4e, $00, $86
@2_song1ref1205:
	.byte $03, $4d, $00
@2_song1ref1208:
	.byte $89, $44, $85, $03, $87, $44, $87, $03, $87, $03, $87, $01, $87, $03, $87, $44, $87, $01, $87, $03, $87, $06, $af, $03
	.byte $41, $15
	.word @2_song1ref1208
	.byte $08, $9b, $0a, $91, $4e, $00
	.byte $41, $18
	.word @2_song1ref1205
	.byte $75, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $8c, $1e, $87, $1d, $87, $1b, $83, $48, .lobyte(@2_env5), .hibyte(@2_env5)
	.byte $a1, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $1e, $87, $1d, $87, $1e, $87, $1d, $87, $1b, $83, $48, .lobyte(@2_env5)
	.byte .hibyte(@2_env5), $8d, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $1e, $87, $1d, $87, $1b, $83, $48, .lobyte(@2_env5), .hibyte(@2_env5)
	.byte $8b, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $81, $4e, $03, $8e
@2_song1ref1300:
	.byte $27, $87, $2e, $87, $27, $87, $2e, $87, $72, $27, $87, $2e, $87, $27, $87, $2e, $87, $75, $31, $87, $2e, $87, $31, $87
	.byte $2e, $87, $72, $31, $87, $2e, $87, $31, $87, $2e, $87, $75, $31, $87, $72, $2e, $87, $75, $31, $87, $72, $31, $87, $75
	.byte $2e, $87, $72, $31, $87, $75, $2e, $87, $72, $2e, $87, $75, $33, $87, $72, $2e, $87, $75, $33, $87, $72, $33, $87, $71
	.byte $3f, $81, $46, $00, $72, $3f, $83, $73, $3f, $81, $46, $00, $74, $3f, $83, $75, $3f, $81, $46, $00, $76, $3f, $83, $77
	.byte $3f, $81, $46, $00, $78, $3f, $83, $75, $4e, $03
	.byte $41, $20
	.word @2_song1ref1300
	.byte $75, $4e, $03, $8c, $22, $87, $20, $87, $22, $87, $20, $87, $1d, $87, $1e, $87, $1d, $87, $19, $87, $84, $1b, $87, $48
	.byte .lobyte(@2_env30), .hibyte(@2_env30), $89, $74, $93, $73, $93, $72, $8f, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $81
	.byte $4e, $02, $81, $7f, $4d, $ff, $88
@2_song1ref1454:
	.byte $1b
@2_song1ref1455:
	.byte $87, $22, $87, $44, $87, $22, $91, $48, .lobyte(@2_env8), .hibyte(@2_env8), $93, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $44, $87, $25
	.byte $41, $0b
	.word @2_song1ref1455
@2_song1ref1476:
	.byte $87, $44, $87, $25, $87, $44, $87, $22, $87, $44, $87, $22, $87, $44, $87, $26, $87, $43, $4f, $fe, $32, $33, $87, $48
	.byte .lobyte(@2_env36), .hibyte(@2_env36), $81, $43, $27, $ad, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $44, $87, $4d, $ff
	.byte $41, $0c
	.word @2_song1ref1454
	.byte $41, $0a
	.word @2_song1ref1455
@2_song1ref1520:
	.byte $28, $81, $43, $4f, $fd, $34, $35, $83, $48, .lobyte(@2_env36), .hibyte(@2_env36), $83, $43, $29, $83, $48, .lobyte(@2_env0)
	.byte .hibyte(@2_env0), $49, $44, $87, $2a, $87, $44, $87, $29, $87, $44, $87, $27, $91, $48, .lobyte(@2_env36), .hibyte(@2_env36)
	.byte $bb, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $44, $87, $4d, $ff
	.byte $41, $0c
	.word @2_song1ref1454
	.byte $41, $0b
	.word @2_song1ref1455
	.byte $41, $18
	.word @2_song1ref1476
	.byte $4d, $ff
	.byte $41, $0c
	.word @2_song1ref1454
	.byte $41, $0a
	.word @2_song1ref1455
	.byte $41, $16
	.word @2_song1ref1520
	.byte $4e, $00, $82
@2_song1ref1586:
	.byte $20, $87, $1e, $87, $1d, $87, $1b, $87, $1d, $87, $48, .lobyte(@2_env30), .hibyte(@2_env30), $89, $44, $91, $48, .lobyte(@2_env0)
	.byte .hibyte(@2_env0), $49, $20, $87, $1e, $87, $1d, $87, $24, $87, $48, .lobyte(@2_env30), .hibyte(@2_env30), $93, $44, $87, $48
	.byte .lobyte(@2_env0), .hibyte(@2_env0), $49, $27, $87, $ff, $9f, $4e, $00
	.byte $41, $1a
	.word @2_song1ref1586
	.byte $42
	.word @2_song1ch1loop
@2_song1ch2:
@2_song1ch2loop:
	.byte $00, $dd, $df, $00, $dd, $df, $00, $dd, $df, $00, $dd, $df, $84, $1d, $00, $ab, $25, $00, $ab, $1d, $00, $a7, $25, $00
	.byte $a7, $1d, $00, $a3, $25, $00, $a3, $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9b, $25, $00, $9b, $1d, $00, $97, $25, $00
	.byte $97, $1d, $00, $95, $25, $00, $95, $1d, $00, $ab
@2_song1ref1695:
	.byte $1d, $0f, $87, $00, $85, $25, $0f, $87, $00, $85, $1d, $0f, $83, $00, $0f, $87, $25, $0d, $85, $0f, $87, $1d, $00, $85
	.byte $0d, $87, $25, $0f, $85, $12, $87, $1d, $12, $8f, $25, $12, $8f
	.byte $41, $1d
	.word @2_song1ref1695
	.byte $14, $87, $1d, $14, $8f, $25, $16, $8f
	.byte $41, $25
	.word @2_song1ref1695
@2_song1ref1746:
	.byte $1d, $0d, $a3, $1d, $0d, $a3, $1d, $0c, $8f, $1d, $0c, $8f, $1d, $0b, $85, $1d, $0b, $85, $1d, $0b, $85, $1d, $0b, $85
	.byte $41, $25
	.word @2_song1ref1695
	.byte $41, $23
	.word @2_song1ref1695
	.byte $14, $8f
	.byte $41, $25
	.word @2_song1ref1695
	.byte $41, $18
	.word @2_song1ref1746
	.byte $41, $25
	.word @2_song1ref1695
	.byte $41, $23
	.word @2_song1ref1695
	.byte $14, $8f
	.byte $41, $25
	.word @2_song1ref1695
	.byte $1d, $0d, $8f, $25, $0d, $8f, $1d, $0d, $8f, $25, $0d, $8f, $1d, $0c, $8f, $25, $0c, $8f, $1d, $0b, $8f, $25, $0b, $8f
	.byte $41, $25
	.word @2_song1ref1695
	.byte $41, $23
	.word @2_song1ref1695
	.byte $14, $8f
	.byte $41, $25
	.word @2_song1ref1695
	.byte $41, $18
	.word @2_song1ref1746
@2_song1ref1833:
	.byte $1d, $11, $87, $00, $85, $25, $11, $87, $00, $85, $1d, $11, $83, $00, $11, $87, $25, $0f, $85, $11, $87, $1d, $00, $85
	.byte $0f, $87, $25, $11, $85, $14, $87, $1d, $14, $8f, $25, $14, $8f
	.byte $41, $20
	.word @2_song1ref1833
	.byte $16, $8f, $25, $18, $8f
	.byte $41, $25
	.word @2_song1ref1833
	.byte $42
	.word @2_song1ch2loop
@2_song1ch3:
@2_song1ch3loop:
	.byte $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $92, $14, $ad, $98, $14, $ad, $92, $14
	.byte $a9, $98, $14, $a9, $92, $14, $a5, $98, $14, $a5, $92, $14, $a1, $98, $14, $a1, $92, $14, $9d, $98, $14, $9d, $92, $14
	.byte $99, $98, $14, $99, $92, $14, $97, $98, $14, $97, $92, $14, $95, $70, $50, $06, $90, $84, $23, $95, $7f
@2_song1ref1954:
	.byte $92, $14, $91, $98, $14, $91, $92, $14, $91, $98, $14, $91, $92, $14, $91, $98, $14, $91
	.byte $41, $0c
	.word @2_song1ref1954
	.byte $41, $0c
	.word @2_song1ref1954
	.byte $41, $0c
	.word @2_song1ref1954
	.byte $92, $14, $a5, $14, $a5, $14, $91, $14, $91, $14, $87, $14, $87, $14, $87, $14, $87
@2_song1ref1998:
	.byte $14, $87, $94, $21, $87, $98, $14, $87, $94, $21, $87, $92, $14, $81, $46, $00, $94, $1f, $83, $21, $81, $46, $00, $1f
	.byte $83, $98, $14, $87, $94, $21, $87, $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $77, $50, $fe, $00, $9a, $1b, $b5, $bf, $50, $04, $a0, $84, $21, $a5, $7f, $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $77, $50, $fe, $00, $9a, $1b, $b5, $bf, $50, $04, $a0, $84, $21, $a5, $7f, $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $92
	.byte $41, $14
	.word @2_song1ref1998
	.byte $42
	.word @2_song1ch3loop
@2_song1ch4:
@2_song1ch4loop:
@2_song1ref2163:
	.byte $33, $a1, $33, $a1, $33, $95, $c7, $33, $95
	.byte $41, $09
	.word @2_song1ref2163
	.byte $41, $09
	.word @2_song1ref2163
	.byte $41, $09
	.word @2_song1ref2163
	.byte $df, $d7, $cf, $c7, $bf, $b7, $b3, $af
@2_song1ref2189:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $0a
	.word @2_song1ref2189
	.byte $41, $0a
	.word @2_song1ref2189
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $42
	.word @2_song1ch4loop
@2_song2ch0:
@2_song2ch0loop:
	.byte $81, $75
@2_song2ref4:
	.byte $90
@2_song2ref5:
	.byte $08
@2_song2ref6:
	.byte $00, $08, $81, $0f, $81, $08, $81, $0f, $81, $14, $85, $17, $00, $17, $81, $0b, $81, $17, $81, $00, $81, $17, $00, $17
	.byte $89, $12, $81, $06, $81, $00, $81, $17, $81, $00, $81, $0b, $81, $06, $81, $00, $81, $19, $81, $0d, $81, $08, $81, $10
	.byte $85, $00, $81, $12, $81, $00
@2_song2ref60:
	.byte $81, $08, $83, $0b, $83, $0f, $81, $09, $83, $0d, $83, $10
	.byte $41, $0c
	.word @2_song2ref60
	.byte $41, $0c
	.word @2_song2ref60
@2_song2ref78:
	.byte $81, $0f, $81, $10, $81, $0f, $81, $0d, $81, $0f, $81, $10, $81, $0f, $81, $0d, $7f, $86
@2_song2ref96:
	.byte $08, $85, $44, $81, $08, $85, $44, $89, $0b, $85, $44, $81, $0b, $85, $44, $89, $06, $85, $44, $81, $06, $85, $44, $89
	.byte $01, $85, $44, $81, $01, $85, $44, $89
	.byte $41, $0f
	.word @2_song2ref96
	.byte $85, $06, $85, $44, $85, $0b, $85, $44, $85, $0d, $85, $44, $85, $10, $89, $12, $85, $42
	.word @2_song2ch0loop
@2_song2ch1:
@2_song2ch1loop:
	.byte $7c
	.byte $41, $43
	.word @2_song2ref4
	.byte $41, $0c
	.word @2_song2ref60
	.byte $41, $0c
	.word @2_song2ref60
	.byte $41, $10
	.word @2_song2ref78
	.byte $81, $7f, $00, $85, $88, $27, $81, $44, $81, $27, $81, $2c, $81, $44, $81, $2a, $81, $44, $81, $27, $25, $23, $85, $20
	.byte $81, $23, $81, $44, $81, $25, $81, $27, $81, $25, $81, $23, $81, $20, $81, $44, $81, $23, $81, $27, $81, $25, $85, $2a
	.byte $81, $2a, $44, $2a, $89, $44, $85, $87, $2c, $83, $4f, $40, $38, $2c, $43, $20, $81, $2c, $89, $2a, $99, $00, $c1, $42
	.word @2_song2ch1loop
@2_song2ch2:
@2_song2ch2loop:
	.byte $ff, $7f, $47, $02, $84
@2_song2ref245:
	.byte $1d, $00, $83, $47, $02, $25, $00, $83, $47, $02, $1d, $00, $83, $47, $02, $25, $00, $83, $47, $02
	.byte $41, $0c
	.word @2_song2ref245
	.byte $47, $02
	.byte $41, $0b
	.word @2_song2ref245
	.byte $a3, $8a
	.byte $41, $39
	.word @2_song2ref5
	.byte $41, $37
	.word @2_song2ref6
	.byte $42
	.word @2_song2ch2loop
@2_song2ch3:
@2_song2ch3loop:
	.byte $7f
@2_song2ref286:
	.byte $94, $21, $23, $96, $20, $81, $94, $21, $23, $96, $20, $81, $94, $21, $23, $96, $20, $81
	.byte $41, $0c
	.word @2_song2ref286
	.byte $41, $0c
	.word @2_song2ref286
	.byte $41, $0c
	.word @2_song2ref286
	.byte $41, $0c
	.word @2_song2ref286
	.byte $94, $21
@2_song2ref318:
	.byte $23, $96, $20, $81, $92, $14, $94, $23, $96, $20, $81, $98, $14, $94, $23, $96, $20, $81, $92, $14, $94, $23, $96, $20
	.byte $81, $98, $14, $94
	.byte $41, $10
	.word @2_song2ref318
	.byte $94
	.byte $41, $10
	.word @2_song2ref318
	.byte $94, $23, $96, $20, $81, $00, $9d
@2_song2ref360:
	.byte $92, $14, $94, $23, $96, $20, $94, $23, $98, $14, $81, $94, $23, $96, $20, $92, $14, $94, $23, $96, $20, $94, $23, $98
	.byte $14, $81, $94, $23, $96, $20
	.byte $41, $10
	.word @2_song2ref360
	.byte $41, $10
	.word @2_song2ref360
	.byte $41, $10
	.word @2_song2ref360
	.byte $41, $10
	.word @2_song2ref360
	.byte $41, $10
	.word @2_song2ref360
	.byte $41, $10
	.word @2_song2ref360
	.byte $41, $10
	.word @2_song2ref360
	.byte $42
	.word @2_song2ch3loop
@2_song2ch4:
	.byte $45, $05
@2_song2ch4loop:
	.byte $45, $05, $ff, $45, $05, $ff, $ff, $45, $05, $ff, $42
	.word @2_song2ch4loop
@2_song3ch0:
	.byte $45, $02
@2_song3ch0loop:
	.byte $7f, $4d, $ff
@2_song3ref7:
	.byte $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $9c
@2_song3ref12:
	.byte $20, $89, $48, .lobyte(@2_env32), .hibyte(@2_env32), $9d, $44, $89, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $1e, $83
	.byte $44, $83, $48, .lobyte(@2_env32), .hibyte(@2_env32), $85, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $21, $89, $48, .lobyte(@2_env32)
	.byte .hibyte(@2_env32), $9d, $44, $89, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $1e, $83, $44, $83, $48, .lobyte(@2_env32)
	.byte .hibyte(@2_env32), $85, $4d, $ff, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $4d, $ff, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
@2_song3ref74:
	.byte $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $27, $83, $44, $83, $48, .lobyte(@2_env32), .hibyte(@2_env32), $85, $48, .lobyte(@2_env0)
	.byte .hibyte(@2_env0), $49, $28, $83, $44, $83, $48, .lobyte(@2_env32), .hibyte(@2_env32), $85, $48, .lobyte(@2_env0), .hibyte(@2_env0)
	.byte $49, $27, $83, $44, $83, $48, .lobyte(@2_env32), .hibyte(@2_env32), $85, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $25
	.byte $83, $44, $83, $48, .lobyte(@2_env32), .hibyte(@2_env32), $85
	.byte $41, $14
	.word @2_song3ref74
	.byte $4d, $ff, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $4d, $ff, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $4d, $ff, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $41, $14
	.word @2_song3ref74
	.byte $41, $0a
	.word @2_song3ref74
@2_song3ref158:
	.byte $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $a3, $00, $ff, $8d, $00, $ff, $8d, $00, $ff, $8d, $00, $ff, $8d, $42
	.word @2_song3ch0loop
@2_song3ch1:
@2_song3ch1loop:
	.byte $7f, $4d, $01
	.byte $41, $14
	.word @2_song3ref7
	.byte $4d, $01, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $4d, $01, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $41, $14
	.word @2_song3ref74
	.byte $41, $14
	.word @2_song3ref74
	.byte $4d, $01, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $4d, $01, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $4d, $01, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $41, $14
	.word @2_song3ref12
	.byte $41, $14
	.word @2_song3ref74
	.byte $41, $0a
	.word @2_song3ref74
	.byte $41, $0d
	.word @2_song3ref158
	.byte $42
	.word @2_song3ch1loop
@2_song3ch2:
@2_song3ch2loop:
	.byte $84
@2_song3ref250:
	.byte $1d, $08, $99, $0c, $83, $25, $0c, $8d, $0f, $8f, $1d, $09, $99, $0d, $83, $25, $0d, $8d, $10, $8f
	.byte $41, $14
	.word @2_song3ref250
	.byte $41, $14
	.word @2_song3ref250
@2_song3ref276:
	.byte $1d, $0f, $8d, $0f, $8f, $25, $0a, $8d, $0a, $8f, $1d, $03, $8d, $03, $8f, $25, $09, $8d, $09, $8f
	.byte $41, $14
	.word @2_song3ref250
	.byte $41, $14
	.word @2_song3ref250
	.byte $41, $14
	.word @2_song3ref250
	.byte $41, $10
	.word @2_song3ref276
	.byte $00, $9f
	.byte $41, $14
	.word @2_song3ref250
	.byte $41, $14
	.word @2_song3ref250
	.byte $41, $14
	.word @2_song3ref250
	.byte $41, $14
	.word @2_song3ref276
	.byte $42
	.word @2_song3ch2loop
@2_song3ch3:
@2_song3ch3loop:
@2_song3ref326:
	.byte $92, $14, $89, $94, $23, $83, $21, $89, $23, $83, $98, $14, $89, $94, $23, $83, $21, $89, $23, $83, $92, $14, $89, $94
	.byte $23, $83, $96, $21, $89, $94, $23, $83, $98, $14, $89, $94, $23, $83, $96, $21, $89, $94, $23, $83
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $19
	.word @2_song3ref326
	.byte $a1
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $20
	.word @2_song3ref326
	.byte $41, $20
	.word @2_song3ref326
	.byte $42
	.word @2_song3ch3loop
@2_song3ch4:
@2_song3ch4loop:
@2_song3ref408:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
	.byte $41, $0a
	.word @2_song3ref408
	.byte $ff, $8f, $ff, $8f, $42
	.word @2_song3ch4loop
@2_song4ch0:
	.byte $45, $02
@2_song4ch0loop:
	.byte $74, $8c
@2_song4ref6:
	.byte $25, $87, $4f, $e5, $31, $33, $43, $27, $8f, $4f, $1b, $33, $31, $43, $25, $85, $4f, $e5, $31, $33, $43, $27, $8f, $4f
	.byte $1b, $33, $31, $43, $25, $85, $4f, $e5, $31, $33, $43, $27, $8f, $4f, $1b, $33, $31, $43, $25, $85, $4f, $e5, $31, $33
	.byte $43, $27, $8f, $4f, $1b, $33, $31, $43, $25, $85, $4f, $e5, $31, $33, $43, $27, $85, $4f, $1b, $33, $31, $43, $25, $85
	.byte $4f, $e5, $31, $33, $43, $27, $85
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $41, $23
	.word @2_song4ref6
	.byte $84, $1b, $4f, $dc, $27, $2e, $85, $43, $22, $9b, $48, .lobyte(@2_env12), .hibyte(@2_env12), $f7, $72, $ff, $9b, $48, .lobyte(@2_env0)
	.byte .hibyte(@2_env0), $49, $83, $7f, $4e, $02, $88
@2_song4ref162:
	.byte $1b, $87, $1e, $83, $7c, $4e, $02, $1b, $87, $1e, $81, $7f, $1e, $87, $20, $83, $7c, $1e, $87, $20, $81, $7f, $20, $87
	.byte $22, $83, $7c, $20, $87, $22, $81, $7f, $22, $87, $23, $83, $7c, $22, $87, $23, $81, $7f, $22, $8d, $7c, $22, $95, $7f
	.byte $4e, $02
	.byte $41, $24
	.word @2_song4ref162
	.byte $7f, $4e, $02
	.byte $41, $24
	.word @2_song4ref162
	.byte $7f, $4e, $02
	.byte $41, $20
	.word @2_song4ref162
	.byte $7f, $25, $8d, $7c, $25, $95, $7f, $4e, $02
	.byte $41, $24
	.word @2_song4ref162
	.byte $7f, $4e, $02
	.byte $41, $24
	.word @2_song4ref162
	.byte $7f, $4e, $02
	.byte $41, $24
	.word @2_song4ref162
	.byte $7f, $4e, $02, $1b, $87, $1e, $83, $77, $4e, $02, $1b, $87, $1e, $81, $7f, $1e, $87, $20, $83, $77, $1e, $87, $20, $81
	.byte $7f, $20, $87, $22, $83, $77, $20, $87, $22, $81, $7f, $22, $87, $23, $83, $77, $22, $87, $23, $81, $7f, $25, $8d, $77
	.byte $25, $81, $75, $4e, $00, $84
@2_song4ref305:
	.byte $25, $87, $27, $87, $2a, $91, $48, .lobyte(@2_env27), .hibyte(@2_env27), $9d, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49
	.byte $89, $25, $87, $27, $87, $2c, $91, $48, .lobyte(@2_env27), .hibyte(@2_env27), $9d, $48, .lobyte(@2_env0), .hibyte(@2_env0)
	.byte $49, $89, $25, $87, $27, $87, $2e, $8b, $2c, $89, $2a, $8b, $2c, $8b, $2a, $89, $27, $8b, $2a, $91, $48, .lobyte(@2_env27)
	.byte .hibyte(@2_env27), $9d, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $89
	.byte $41, $1f
	.word @2_song4ref305
	.byte $91, $48, .lobyte(@2_env27), .hibyte(@2_env27), $ab, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $89
	.byte $41, $24
	.word @2_song4ref305
	.byte $41, $15
	.word @2_song4ref305
	.byte $91, $48, .lobyte(@2_env27), .hibyte(@2_env27), $bb, $72, $cd, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $81, $73
@2_song4ref394:
	.byte $4f, $7f, $3a, $27
@2_song4ref398:
	.byte $43, $1b, $46, $00, $4f, $80, $27, $2e, $43, $22, $81, $4f, $b9, $2e, $33, $43, $27, $46, $00, $4f, $7f, $33, $27, $43
	.byte $1b, $81, $4f, $80, $27, $2e, $43, $22, $46, $00, $4f, $80, $2e, $33, $43, $27, $81, $4f, $7f, $33, $27, $43, $1b, $46
	.byte $00, $4f, $80, $27, $2e, $43, $22, $81, $4f, $7f, $2e, $27
	.byte $41, $14
	.word @2_song4ref398
	.byte $41, $13
	.word @2_song4ref398
@2_song4ref464:
	.byte $4f, $7f, $2e, $25, $43, $19, $46, $00, $4f, $80, $25, $2c, $43, $20, $81, $4f, $b0, $2c, $31, $43, $25, $46, $00, $4f
	.byte $7f, $31, $25, $43, $19, $81, $4f, $80, $25, $31, $43, $25, $46, $00, $4f, $7f, $31, $2c, $43, $20, $81, $4f, $7f, $2c
	.byte $25, $43, $19, $46, $00, $4f, $80, $25, $2c, $43, $20, $81
	.byte $41, $15
	.word @2_song4ref394
	.byte $41, $14
	.word @2_song4ref398
	.byte $41, $13
	.word @2_song4ref398
	.byte $41, $14
	.word @2_song4ref464
	.byte $41, $15
	.word @2_song4ref394
	.byte $41, $14
	.word @2_song4ref398
	.byte $41, $13
	.word @2_song4ref398
	.byte $41, $14
	.word @2_song4ref464
	.byte $41, $15
	.word @2_song4ref394
	.byte $41, $14
	.word @2_song4ref398
	.byte $41, $13
	.word @2_song4ref398
	.byte $41, $14
	.word @2_song4ref464
	.byte $41, $15
	.word @2_song4ref394
	.byte $41, $14
	.word @2_song4ref398
	.byte $41, $13
	.word @2_song4ref398
	.byte $41, $14
	.word @2_song4ref464
	.byte $41, $15
	.word @2_song4ref394
	.byte $41, $14
	.word @2_song4ref398
	.byte $41, $13
	.word @2_song4ref398
	.byte $41, $14
	.word @2_song4ref464
	.byte $41, $15
	.word @2_song4ref394
	.byte $41, $14
	.word @2_song4ref398
	.byte $41, $13
	.word @2_song4ref398
	.byte $41, $14
	.word @2_song4ref464
	.byte $41, $15
	.word @2_song4ref394
	.byte $41, $14
	.word @2_song4ref398
	.byte $41, $13
	.word @2_song4ref398
	.byte $41, $14
	.word @2_song4ref464
	.byte $42
	.word @2_song4ch0loop
@2_song4ch1:
@2_song4ch1loop:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $86
@2_song4ref621:
	.byte $03, $ff, $9d, $40, $0c, $ff, $9d, $40, $0b, $ff, $9d, $40, $0b, $ff, $9d, $03, $ff, $9d, $40, $0c, $ff, $9d, $40, $0b
	.byte $ff, $9d, $40, $0b, $ff, $9d
	.byte $41, $15
	.word @2_song4ref621
	.byte $ff, $9f
@2_song4ref656:
	.byte $03, $8b, $44, $83, $03, $8b, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83
	.byte $03, $81, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83, $01, $a5
	.byte $41, $2a
	.word @2_song4ref656
	.byte $41, $2a
	.word @2_song4ref656
	.byte $41, $2a
	.word @2_song4ref656
	.byte $41, $2a
	.word @2_song4ref656
	.byte $41, $2a
	.word @2_song4ref656
	.byte $41, $2a
	.word @2_song4ref656
	.byte $41, $2a
	.word @2_song4ref656
@2_song4ref719:
	.byte $40, $0b, $91, $44, $87, $40, $0b, $91, $44, $9b, $01, $91, $44, $87, $01, $91, $44, $9b, $40, $0a, $91, $44, $87, $40
	.byte $0a, $91, $44, $9b, $03, $91, $44, $87, $03, $87, $01, $91, $44, $87, $01, $87
	.byte $41, $24
	.word @2_song4ref719
	.byte $41, $24
	.word @2_song4ref719
	.byte $41, $17
	.word @2_song4ref719
	.byte $87, $40, $0a, $91, $44, $87, $40, $0a, $91, $44, $87, $40, $0a, $87, $44, $87, $40, $0a, $87, $44, $87, $7f, $88
@2_song4ref791:
	.byte $1b, $87, $22, $87, $44, $87, $22, $91, $48, .lobyte(@2_env8), .hibyte(@2_env8), $93, $48, .lobyte(@2_env0), .hibyte(@2_env0)
	.byte $49, $44, $87, $25, $87, $22, $87, $44, $87, $22, $91, $48, .lobyte(@2_env8), .hibyte(@2_env8), $93, $48, .lobyte(@2_env0)
	.byte .hibyte(@2_env0), $49, $44, $87, $25, $87, $44, $87, $25, $87, $44, $87, $22, $87, $44, $87, $22, $87, $44, $87, $26
	.byte $87, $43, $4f, $fe, $32, $33, $87, $48, .lobyte(@2_env36), .hibyte(@2_env36), $81, $43, $27, $ad, $48, .lobyte(@2_env0), .hibyte(@2_env0)
	.byte $49, $44, $87
	.byte $41, $16
	.word @2_song4ref791
	.byte $28, $81, $43, $4f, $fd, $34, $35, $83, $48, .lobyte(@2_env36), .hibyte(@2_env36), $83, $43, $29, $83, $48, .lobyte(@2_env0)
	.byte .hibyte(@2_env0), $49, $44, $87, $2a, $87, $44, $87, $29, $87, $44, $87, $27, $91, $48, .lobyte(@2_env36), .hibyte(@2_env36)
	.byte $97, $48, .lobyte(@2_env0), .hibyte(@2_env0), $49, $44, $83, $19, $a5, $1b, $9b, $1d, $9b, $1e, $9b, $20, $9b, $22, $a5
	.byte $22, $9b, $20, $9b, $1e, $9b, $20, $9b, $1e, $91, $1d, $91, $1b, $9b, $1d, $9b, $1e, $9b, $20, $9b, $22, $a5, $27, $9b
	.byte $25, $9b, $27, $91, $29, $9b, $2a, $9b, $29, $91, $42
	.word @2_song4ch1loop
@2_song4ch2:
@2_song4ch2loop:
@2_song4ref958:
	.byte $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d
	.byte $41, $15
	.word @2_song4ref958
	.byte $86, $12, $ff, $9d, $12, $ff, $9d, $0f, $ff, $9d, $84, $0c, $ff, $9d, $0b, $ff, $9d, $ff, $9f
@2_song4ref1001:
	.byte $1d, $00, $85, $1d, $00, $85, $25, $00, $85, $1d, $00, $85, $1d, $00, $85, $1d, $00, $85, $25, $00, $85, $1d, $00, $85
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $41, $18
	.word @2_song4ref1001
	.byte $1d, $00, $ff, $9b
@2_song4ref1116:
	.byte $1d, $0f, $87, $00, $85, $25, $0f, $87, $00, $85, $1d, $0f, $83, $00, $0f, $87, $25, $0d, $85, $0f, $87, $1d, $00, $85
	.byte $0f, $87, $25, $0f, $85, $0f, $87, $1d, $0d, $8f, $25, $0d, $8f
	.byte $41, $25
	.word @2_song4ref1116
	.byte $41, $25
	.word @2_song4ref1116
	.byte $41, $25
	.word @2_song4ref1116
	.byte $41, $25
	.word @2_song4ref1116
	.byte $41, $25
	.word @2_song4ref1116
	.byte $41, $25
	.word @2_song4ref1116
	.byte $41, $25
	.word @2_song4ref1116
	.byte $42
	.word @2_song4ch2loop
@2_song4ch3:
@2_song4ch3loop:
	.byte $41, $15
	.word @2_song4ref958
	.byte $41, $15
	.word @2_song4ref958
	.byte $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $f7, $70, $50, $04, $a0, $84, $21, $a5, $77, $50, $fe, $00, $1c, $b5, $e7
	.byte $cf, $7f, $92, $14, $81, $00, $83, $14, $81, $00, $8d, $14, $81, $00, $83, $14, $81, $00, $8d, $14, $81, $00, $83, $14
	.byte $81, $00, $83
@2_song4ref1235:
	.byte $14, $87, $14, $87, $98, $14, $87, $92, $14, $87, $14, $87, $14, $87, $98, $14, $87, $92, $14, $87, $14, $87, $14, $87
	.byte $98, $14, $87, $92, $14, $87
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $41, $18
	.word @2_song4ref1235
	.byte $14, $f5, $70, $50, $04, $a0, $84, $21, $a5, $7f
@2_song4ref1332:
	.byte $92, $14, $87, $94, $21, $87, $98, $14, $87, $94, $21, $87, $92, $14, $81, $46, $00, $94, $1f, $83, $21, $81, $46, $00
	.byte $1f, $83, $98, $14, $87, $94, $21, $87
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $41, $14
	.word @2_song4ref1332
	.byte $42
	.word @2_song4ch3loop
@2_song4ch4:
@2_song4ch4loop:
	.byte $41, $15
	.word @2_song4ref958
	.byte $41, $15
	.word @2_song4ref958
	.byte $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $cf, $0c, $87, $0c, $91, $0b, $87, $0b, $91
	.byte $09, $87, $09, $87
@2_song4ref1447:
	.byte $05, $f5, $03, $a5, $05, $f5, $03, $a5, $05, $f5, $03, $a5, $05, $f5, $03, $a5, $05, $f5, $03, $a5, $05, $f5, $03, $a5
	.byte $05, $f5, $03, $a5, $05, $f5, $03, $a5
@2_song4ref1479:
	.byte $04, $9b, $04, $af, $03, $9b, $03, $af, $02, $9b, $02, $af, $05, $9b, $05, $87, $03, $9b, $03, $87
	.byte $41, $14
	.word @2_song4ref1479
	.byte $41, $14
	.word @2_song4ref1479
	.byte $04, $9b, $04, $af, $03, $9b, $03, $af, $02, $9b, $02, $9b, $02, $9b, $02, $9b, $02, $91, $02, $91
	.byte $41, $20
	.word @2_song4ref1447
	.byte $42
	.word @2_song4ch4loop
@2_song5ch0:
	.byte $45, $02
@2_song5ch0loop:
	.byte $4d, $ff, $91, $77, $4e, $03
@2_song5ref10:
	.byte $90
@2_song5ref11:
	.byte $0d, $81, $00, $85, $0d, $81, $00, $81, $0d, $81, $00, $85, $0d, $81, $00, $81, $0d, $81, $44, $89, $0d, $81, $44, $89
	.byte $0b, $81, $44, $89, $0b, $81, $44, $81, $0d, $81, $00, $85, $0d, $81, $00, $81, $0d, $81, $00, $85, $0d, $81, $00, $81
	.byte $10, $91, $44, $81, $12, $8b, $4d, $ff, $91, $4e, $03
	.byte $41, $37
	.word @2_song5ref11
	.byte $4e, $03
	.byte $41, $37
	.word @2_song5ref11
	.byte $4e, $03
	.byte $41, $37
	.word @2_song5ref11
	.byte $4e, $03
	.byte $41, $37
	.word @2_song5ref11
	.byte $4e, $03
	.byte $41, $36
	.word @2_song5ref11
	.byte $42
	.word @2_song5ch0loop
@2_song5ch1:
@2_song5ch1loop:
	.byte $41, $31
	.word @2_song5ref10
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2_song5ref11
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2_song5ref11
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2_song5ref11
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2_song5ref11
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2_song5ref11
	.byte $89, $44, $89, $12, $97, $44, $83, $42
	.word @2_song5ch1loop
@2_song5ch2:
@2_song5ch2loop:
	.byte $84
@2_song5ref162:
	.byte $0d, $81, $00, $85, $0d, $81, $00, $81, $0d, $81, $0d, $00, $83, $0d, $81, $00, $81, $0d, $85, $0d, $83, $00, $0d, $8d
	.byte $0b, $8b, $00, $0b, $85, $0d, $81, $00, $85, $0d, $81, $00, $81, $0d, $81, $0d, $00, $83, $0d, $81, $00, $81, $10, $85
	.byte $10, $8d, $12, $85, $12, $95
	.byte $41, $36
	.word @2_song5ref162
	.byte $41, $36
	.word @2_song5ref162
	.byte $41, $36
	.word @2_song5ref162
	.byte $41, $36
	.word @2_song5ref162
	.byte $41, $36
	.word @2_song5ref162
	.byte $42
	.word @2_song5ch2loop
@2_song5ch3:
@2_song5ch3loop:
	.byte $92
@2_song5ref236:
	.byte $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95
	.byte $41, $14
	.word @2_song5ref236
	.byte $41, $14
	.word @2_song5ref236
	.byte $14, $95, $14, $95
@2_song5ref266:
	.byte $1c, $89, $94, $21, $83, $23, $83, $92, $1c, $89, $94, $21, $83, $23, $83, $92, $1c, $89, $94, $21, $89, $92, $1c, $83
	.byte $94, $21, $83, $22, $89, $92
	.byte $41, $16
	.word @2_song5ref266
	.byte $92
	.byte $41, $16
	.word @2_song5ref266
	.byte $92
	.byte $41, $16
	.word @2_song5ref266
	.byte $42
	.word @2_song5ch3loop
@2_song5ch4:
@2_song5ch4loop:
	.byte $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $42
	.word @2_song5ch4loop
@2_song6ch0:
	.byte $45, $02
@2_song6ch0loop:
	.byte $ff, $ff, $ff, $ff, $ff, $42
	.word @2_song6ch0loop
@2_song6ch1:
@2_song6ch1loop:
	.byte $ff, $80, $11, $fd, $10, $fd, $11, $8d, $00, $ed, $ff, $42
	.word @2_song6ch1loop
@2_song6ch2:
@2_song6ch2loop:
	.byte $84, $1d, $00, $9b, $1d, $00, $9b, $1d, $00, $9b, $1d, $00, $9b, $ff, $ff, $ff, $ff, $42
	.word @2_song6ch2loop
@2_song6ch3:
@2_song6ch3loop:
@2_song6ref49:
	.byte $92, $14, $8d, $94, $21, $8d, $92, $14, $8d, $94, $21, $8d
	.byte $41, $08
	.word @2_song6ref49
	.byte $ff, $ff, $ff, $ff, $42
	.word @2_song6ch3loop
@2_song6ch4:
@2_song6ch4loop:
	.byte $ff, $ff, $ff, $ff, $12, $85, $12, $a5, $12, $85, $12, $a5, $12, $85, $12, $95, $42
	.word @2_song6ch4loop
