; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music3_data_=music3_data_
.endif

music3_data_:
	.byte 4
	.word @instruments
	.word @samples-5
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; 00 : DPCM ALIGNER (NOT FOR PLAYBACK)
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,262,218 ; 01 : Victorous Degenerate (Rank S)
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,262,218 ; 02 : Victorous Degenerate (Rank P)
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,245,204 ; 03 : Theatrical Shenanigans

.export music3_data_
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env17,@env4,@env0 ; 00 : bass
	.word @env8,@env15,@env23,@env0 ; 01 : blank
	.word @env16,@env15,@env23,@env0 ; 02 : Blank two electric boogaloo
	.word @env30,@env15,@env18,@env0 ; 03 : goofy Synth Bass 
	.word @env34,@env20,@env23,@env0 ; 04 : noise (get it) kick
	.word @env9,@env7,@env23,@env0 ; 05 : noise hat
	.word @env24,@env21,@env23,@env0 ; 06 : Noise kick (now with echo!)
	.word @env12,@env7,@env23,@env0 ; 07 : noise open hat
	.word @env14,@env19,@env23,@env0 ; 08 : noise snare
	.word @env26,@env15,@env22,@env27 ; 09 : oooh voice pads
	.word @env11,@env37,@env23,@env0 ; 0a : Open Snare
	.word @env33,@env15,@env35,@env0 ; 0b : Rank Lead P
	.word @env33,@env15,@env10,@env0 ; 0c : Rank Lead S
	.word @env32,@env15,@env23,@env3 ; 0d : Short Tri Snare
	.word @env2,@env1,@env23,@env0 ; 0e : Snare side B
	.word @env25,@env29,@env23,@env0 ; 0f : Tri Toms

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $bd,$c6,$c0,$00,$02
@env2:
	.byte $00,$ca,$c8,$c7,$c6,$03,$c5,$04,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$10
@env3:
	.byte $80,$e0,$00,$01
@env4:
	.byte $c2,$c3,$00,$01
@env5:
	.byte $00,$c0,$be,$be,$c0,$c2,$c2,$00,$01
@env6:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env7:
	.byte $be,$c0,$00,$01
@env8:
	.byte $00,$cf,$7f,$00,$02
@env9:
	.byte $00,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@env10:
	.byte $c3,$c2,$c2,$c0,$00,$03
@env11:
	.byte $00,$ca,$cc,$c8,$c7,$c6,$c5,$c5,$c4,$02,$c3,$02,$c2,$c2,$c1,$02,$c0,$00,$10
@env12:
	.byte $00,$c5,$c4,$c3,$00,$03
@env13:
	.byte $00,$c0,$be,$bd,$bf,$c1,$c3,$c2,$00,$01
@env14:
	.byte $00,$ca,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$0b
@env15:
	.byte $c0,$7f,$00,$01
@env16:
	.byte $06,$cf,$cf,$cf,$00,$03,$c0,$00,$06
@env17:
	.byte $c5,$c0,$00,$01
@env18:
	.byte $c0,$02,$c1,$c1,$c2,$c2,$c3,$00,$06
@env19:
	.byte $c6,$ca,$00,$01
@env20:
	.byte $c6,$cd,$00,$01
@env21:
	.byte $c6,$ce,$00,$01
@env22:
	.byte $c1,$c1,$c2,$00,$02
@env23:
	.byte $7f,$00,$00
@env24:
	.byte $00,$ca,$c7,$c6,$c5,$c3,$c2,$c7,$c5,$c4,$c4,$c3,$c2,$c1,$c0,$00,$0e
@env25:
	.byte $00,$cf,$09,$c0,$00,$03
@env26:
	.byte $08,$c2,$04,$c3,$c3,$c3,$00,$05,$c2,$05,$c1,$c1,$c0,$00,$0c
@env27:
	.byte $80,$c7,$c5,$c2,$00,$03
@env28:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env29:
	.byte $c0,$bd,$ba,$b7,$b4,$b1,$ae,$ab,$a8,$a5,$00,$09
@env30:
	.byte $0b,$c7,$c6,$c6,$c5,$02,$c4,$c4,$c3,$00,$08,$c3,$c2,$c2,$c1,$c1,$c0,$00,$10
@env31:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@env32:
	.byte $00,$cf,$05,$c0,$00,$03
@env33:
	.byte $06,$c7,$c6,$c5,$00,$03,$c5,$c4,$c4,$c3,$c2,$c1,$00,$0b
@env34:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@env35:
	.byte $c0,$02,$c2,$00,$02
@env36:
	.byte $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01
@env37:
	.byte $c5,$c1,$ca,$ca,$c9,$ca,$cb,$ca,$00,$04

@samples:
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4f,$40,$00 ; 00 arpeggiosquare.dmc (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$45,$2e,$01 ; 01 b1 bass.dmc (Pitch:5)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$47,$2e,$01 ; 02 b1 bass.dmc (Pitch:7)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$5f,$45,$00,$00 ; 03 b2 bass.dmc (Pitch:5)
	.byte $62+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$47,$00,$01 ; 04 b3 bass.dmc (Pitch:7)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4a,$00,$00 ; 05 dash.dmc (Pitch:10)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4d,$00,$00 ; 06 dash.dmc (Pitch:13)
	.byte $79+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0f,$40,$00 ; 07 Hebereke Kick.dmc (Pitch:15)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0c,$40,$00 ; 08 Hebereke Snare.dmc (Pitch:12)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0d,$40,$00 ; 09 Hebereke Snare.dmc (Pitch:13)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0e,$40,$00 ; 0a Hebereke Snare.dmc (Pitch:14)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0f,$40,$00 ; 0b Hebereke Snare.dmc (Pitch:15)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$00 ; 0c OrchHitA.dmc (Pitch:7)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$00 ; 0d OrchHitA.dmc (Pitch:8)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$00 ; 0e OrchHitA.dmc (Pitch:10)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$00 ; 0f OrchHitA.dmc (Pitch:11)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$00 ; 10 OrchHitA.dmc (Pitch:12)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 11 OrchHitA.dmc (Pitch:14)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 12 OrchHitA.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 13 OrchHitF.dmc (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 14 OrchHitF.dmc (Pitch:15)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$00 ; 15 OrchHitF#.dmc (Pitch:13)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 16 OrchHitF#.dmc (Pitch:14)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 17 OrchHitF#.dmc (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 18 OrchHitG.dmc (Pitch:1)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$02,$00,$01 ; 19 OrchHitG.dmc (Pitch:2)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 1a OrchHitG.dmc (Pitch:3)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 1b OrchHitG.dmc (Pitch:4)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$05,$00,$01 ; 1c OrchHitG.dmc (Pitch:5)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 1d OrchHitG.dmc (Pitch:6)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 1e OrchHitG.dmc (Pitch:7)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 1f OrchHitG.dmc (Pitch:9)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 20 OrchHitG.dmc (Pitch:10)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 21 OrchHitG.dmc (Pitch:12)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$01 ; 22 OrchHitG.dmc (Pitch:13)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 23 OrchHitG.dmc (Pitch:14)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 24 OrchHitG.dmc (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 25 OrchHitG#.dmc (Pitch:1)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 26 OrchHitG#.dmc (Pitch:3)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 27 OrchHitG#.dmc (Pitch:4)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 28 OrchHitG#.dmc (Pitch:6)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 29 OrchHitG#.dmc (Pitch:7)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$01 ; 2a OrchHitG#.dmc (Pitch:8)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 2b OrchHitG#.dmc (Pitch:9)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 2c OrchHitG#.dmc (Pitch:10)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$01 ; 2d OrchHitG#.dmc (Pitch:11)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 2e OrchHitG#.dmc (Pitch:12)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 2f OrchHitG#.dmc (Pitch:14)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 30 OrchHitG#.dmc (Pitch:15)
	.byte $74+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0d,$00,$00 ; 31 Pac_Kick44 (Pitch:13)
	.byte $74+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0e,$00,$00 ; 32 Pac_Kick44 (Pitch:14)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$00,$00 ; 33 Pac_Kick64 (Pitch:13)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0e,$00,$00 ; 34 Pac_Kick64 (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$44,$0f,$00,$01 ; 35 taunt.dmc (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$2f,$07,$00,$00 ; 36 untitled.dmc (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$34,$08,$00,$00 ; 37 untitled1.dmc (Pitch:8)

@song0ch0:
	.byte $45, $01, $ff, $ff, $ff, $ff
@song0ch0loop:
	.byte $00, $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $ff, $ff, $ff
@song0ch1loop:
	.byte $00, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $ff, $ff, $ff
@song0ch2loop:
	.byte $00, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $ff, $ff
@song0ch3loop:
	.byte $00, $42
	.word @song0ch3loop
@song0ch4:
	.byte $34, $35, $32, $37, $33, $38, $06, $07, $36, $08, $0c, $0b, $0a, $09, $01, $13, $31, $25, $18, $15, $12, $30, $24, $17
	.byte $14, $23, $16, $11, $2f, $22, $10, $2e, $0f, $2d, $21, $2c, $20, $0e, $2b, $0d, $2a, $1f, $29, $1e, $1d, $28, $1c, $27
	.byte $1b, $1a, $26, $19, $05, $03, $04, $02, $00, $ff, $ff, $ff, $8d
@song0ch4loop:
	.byte $00, $42
	.word @song0ch4loop
@song1ch0:
	.byte $45, $02, $00, $dd, $72, $4e, $02, $84, $11, $93, $50, $02, $70, $b1, $97, $7f, $98, $1d, $85
@song1ref20:
	.byte $44, $81, $1d
@song1ref23:
	.byte $81, $44, $1d, $81, $44, $20, $81, $44, $81, $20
@song1ref33:
	.byte $81, $44, $81, $20, $81, $44, $81, $22
@song1ref41:
	.byte $81, $44, $22
@song1ref44:
	.byte $81, $44, $22, $81, $44, $22, $81, $44, $23, $85, $44, $81, $23, $83, $48, .lobyte(@env31), .hibyte(@env31), $81, $44
	.byte $81, $48, .lobyte(@env0), .hibyte(@env0), $49, $1d, $85, $48, .lobyte(@env31), .hibyte(@env31), $44, $81, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $1b
	.byte $41, $09
	.word @song1ref23
	.byte $1d
	.byte $41, $0a
	.word @song1ref33
	.byte $20
	.byte $41, $09
	.word @song1ref44
	.byte $81, $44
@song1ref93:
	.byte $24, $81, $44, $23, $81, $44, $24, $83, $1d
@song1ref102:
	.byte $44, $81, $1d, $44, $81, $1d, $44, $81, $1d, $44, $81
@song1ref113:
	.byte $20, $44, $81, $20, $44, $81, $20
@song1ref120:
	.byte $44, $81, $20, $44, $81, $22, $44, $81, $22, $44, $81, $22, $44, $81, $22, $44, $81, $23, $44, $81, $23, $44, $81, $25
	.byte $44, $81, $27, $44, $81, $48, .lobyte(@env5), .hibyte(@env5), $29, $d9, $44, $81, $81, $00, $db
@song1ch0loop:
	.byte $00, $42
	.word @song1ch0loop
@song1ch1:
	.byte $00, $dd, $72, $4e, $01, $84, $0c, $93, $50, $02, $70, $b1, $97, $78, $98, $18, $85, $44, $81, $18
@song1ref184:
	.byte $81, $44, $18, $81, $44, $1b, $81, $44, $81, $1b, $81, $44, $81, $1b, $81
	.byte $41, $08
	.word @song1ref20
	.byte $1d, $81, $44, $1d, $81, $44, $1e, $85, $44, $81, $1e, $83, $48, .lobyte(@env31), .hibyte(@env31), $81, $44, $81, $48
	.byte .lobyte(@env0), .hibyte(@env0), $49, $18, $85, $48, .lobyte(@env31), .hibyte(@env31), $44, $81, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $16
	.byte $41, $09
	.word @song1ref184
	.byte $18, $81, $44, $81, $1b, $81, $44, $81, $1d, $81, $44, $1b, $81, $44, $1d, $81, $44, $1d, $81, $44, $1e, $81, $44, $1f
	.byte $81, $44, $1e, $81, $44, $1f, $83, $18, $44, $81, $18, $44, $81, $18, $44, $81, $18, $44, $81, $1b, $44, $81, $1b, $44
	.byte $81, $1b, $44, $81, $1b
	.byte $41, $0b
	.word @song1ref102
	.byte $1d, $44, $81, $1e, $44, $81, $1e
	.byte $41, $08
	.word @song1ref120
	.byte $18, $d9, $44, $81, $81, $00, $db
@song1ch1loop:
	.byte $00, $42
	.word @song1ch1loop
@song1ch2:
	.byte $00, $95, $9a, $25, $ad, $25, $95, $00, $95, $25, $ad, $25, $95, $84
@song1ref331:
	.byte $1d, $85, $44, $81, $1b, $81, $44, $1d, $81, $44, $9a, $25, $81, $44, $81, $84, $1d
	.byte $41, $0a
	.word @song1ref33
	.byte $20
	.byte $41, $08
	.word @song1ref41
	.byte $9a, $25, $81, $44, $85, $84, $23, $85, $44, $81
	.byte $41, $0b
	.word @song1ref331
	.byte $85, $84, $1d
	.byte $41, $0a
	.word @song1ref33
	.byte $20
	.byte $41, $08
	.word @song1ref41
	.byte $9a, $25, $83, $84
	.byte $41, $14
	.word @song1ref93
	.byte $9a, $25, $83, $84
	.byte $41, $09
	.word @song1ref113
	.byte $9a, $25, $44, $81, $84, $22, $44, $81, $22, $44, $81, $9a, $25, $44, $81, $84, $23, $81, $00, $9a, $25, $44, $81, $84
	.byte $25, $44, $81, $9a, $25, $44, $81, $50, $99, $00, $82, $1d, $db, $00, $df
@song1ch2loop:
	.byte $00, $42
	.word @song1ch2loop
@song1ch3:
@song1ref436:
	.byte $88, $14, $89, $14, $89, $90, $14, $83, $88, $14, $8f, $14, $95, $90, $14, $95
	.byte $41, $0c
	.word @song1ref436
	.byte $41, $0c
	.word @song1ref436
	.byte $41, $0c
	.word @song1ref436
	.byte $88, $14, $83
@song1ref464:
	.byte $14, $83, $14, $83, $14, $83, $90, $14, $83, $88
	.byte $41, $08
	.word @song1ref464
	.byte $88, $14, $83, $14, $83, $90, $14, $83, $88, $14, $83, $90, $14, $83, $88, $14, $83, $90, $14, $83, $df, $78, $50, $fe
	.byte $00, $82, $1f, $b5, $a7
@song1ch3loop:
	.byte $00, $42
	.word @song1ch3loop
@song1ch4:
@song1ref511:
	.byte $32, $89, $32, $89, $33, $83, $32, $8f, $32, $95, $33, $95
	.byte $41, $0c
	.word @song1ref511
	.byte $41, $0c
	.word @song1ref511
	.byte $41, $0c
	.word @song1ref511
	.byte $32
@song1ref533:
	.byte $83, $32, $83, $32, $83, $32, $83, $33
	.byte $41, $08
	.word @song1ref533
	.byte $83, $32, $83, $32, $83, $33, $83, $32, $83, $33, $83, $32, $83, $33, $83, $32, $dd, $08, $dd
@song1ch4loop:
	.byte $00, $42
	.word @song1ch4loop
@song2ch0:
	.byte $45, $02, $00, $ad, $71, $48, .lobyte(@env36), .hibyte(@env36), $4e, $02, $82, $1d, $93, $72, $8d, $50, $01, $80, $8b
	.byte $c7, $43, $4f, $18, $29, $1e, $91, $73, $81, $72, $81, $7f, $4d, $fe, $48, .lobyte(@env0), .hibyte(@env0), $49, $96
	.byte $1d, $85
@song2ref41:
	.byte $44, $81, $1d
@song2ref44:
	.byte $81, $44, $1d, $81, $44, $20, $81, $44, $81, $20
@song2ref54:
	.byte $81, $44, $81, $20, $81, $44, $81, $22
@song2ref62:
	.byte $81, $44, $22
@song2ref65:
	.byte $81, $44, $22, $81, $44, $22, $81, $44, $23, $85, $44, $81, $23, $83, $48, .lobyte(@env31), .hibyte(@env31), $81, $44
	.byte $81, $48, .lobyte(@env0), .hibyte(@env0), $49, $1d, $85, $48, .lobyte(@env31), .hibyte(@env31), $44, $81, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $1b
	.byte $41, $09
	.word @song2ref44
	.byte $1d
	.byte $41, $0a
	.word @song2ref54
	.byte $20
	.byte $41, $09
	.word @song2ref65
	.byte $81, $44
@song2ref114:
	.byte $24, $81, $44, $23, $81, $44, $24, $83, $1d
@song2ref123:
	.byte $44, $81, $1d, $44, $81, $1d, $44, $81, $1d, $44, $81, $20, $44, $81, $20, $44, $81, $20
@song2ref141:
	.byte $44, $81, $20, $44, $81, $22, $44, $81, $22, $44, $81, $22, $44, $81, $22, $44, $81, $23, $44, $81, $23, $44, $81, $25
	.byte $44, $81, $27, $44, $81, $29, $8d, $48, .lobyte(@env28), .hibyte(@env28), $cb, $44, $81, $7a, $4d, $00, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $4f, $10, $35, $2a, $8f, $43, $1e, $83, $78, $4f, $10, $35, $2a, $8f, $43, $1e, $83, $74, $4f
	.byte $08, $35, $2d, $89, $44, $89, $00, $95
@song2ch0loop:
	.byte $00, $42
	.word @song2ch0loop
@song2ch1:
	.byte $00, $ad, $71, $48, .lobyte(@env36), .hibyte(@env36), $4e, $02, $82, $18, $93, $72, $8d, $50, $01, $80, $8b, $c7, $43
	.byte $4f, $19, $24, $1b, $91, $73, $81, $72, $81, $7f, $4d, $fe, $48, .lobyte(@env0), .hibyte(@env0), $49, $96, $18, $85
	.byte $44, $81, $18
@song2ref258:
	.byte $81, $44, $18, $81, $44, $1b, $81, $44, $81, $1b, $81, $44, $81, $1b, $81
	.byte $41, $08
	.word @song2ref41
	.byte $1d, $81, $44, $1d, $81, $44, $1e, $85, $44, $81, $1e, $83, $48, .lobyte(@env31), .hibyte(@env31), $81, $44, $81, $48
	.byte .lobyte(@env0), .hibyte(@env0), $49, $18, $85, $48, .lobyte(@env31), .hibyte(@env31), $44, $81, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $16
	.byte $41, $09
	.word @song2ref258
	.byte $18, $81, $44, $81, $1b, $81, $44, $81, $1d, $81, $44, $1b, $81, $44, $1d, $81, $44, $1d, $81, $44, $1e, $81, $44, $1f
	.byte $81, $44, $1e, $81, $44, $1f, $83, $18, $44, $81, $18, $44, $81, $18, $44, $81, $18, $44, $81, $1b, $44, $81, $1b, $44
	.byte $81, $1b, $44, $81, $1b
	.byte $41, $0b
	.word @song2ref123
	.byte $1d, $44, $81, $1e, $44, $81, $1e
	.byte $41, $08
	.word @song2ref141
	.byte $24, $8d, $48, .lobyte(@env28), .hibyte(@env28), $cb, $44, $81, $7a, $4d, $00, $48, .lobyte(@env0), .hibyte(@env0)
	.byte $49, $4f, $10, $30, $25, $95, $78, $4f, $10, $30, $25, $95, $74, $4f, $08, $30, $2a, $89, $44, $89, $00, $95
@song2ch1loop:
	.byte $00, $42
	.word @song2ch1loop
@song2ch2:
	.byte $9e
@song2ref421:
	.byte $22, $89, $22, $8f, $22, $8f, $22, $ad
	.byte $41, $08
	.word @song2ref421
	.byte $20, $84, $1d, $83, $00, $81, $18, $81, $44, $1d, $81, $44, $9a, $25, $81, $44, $81, $84, $1d
	.byte $41, $0a
	.word @song2ref54
	.byte $20
	.byte $41, $08
	.word @song2ref62
	.byte $9a, $25, $81, $44, $85, $84, $23, $85, $44, $81, $1d, $85, $44, $81, $1b, $81, $44, $1d, $81, $44, $9a, $25, $85, $84
	.byte $1d
	.byte $41, $0a
	.word @song2ref54
	.byte $20
	.byte $41, $08
	.word @song2ref62
	.byte $9a, $25, $83, $84
	.byte $41, $08
	.word @song2ref114
	.byte $80, $1d, $81, $00, $1d, $81, $00, $1d, $81, $00, $1d, $81, $00, $9a, $25, $83, $80, $20, $81, $00, $20, $81, $00, $20
	.byte $81, $00, $9a, $25, $83, $80, $22, $81, $00, $22, $81, $00, $9a, $25, $83, $80, $23, $81, $00, $9a, $25, $83, $80, $25
	.byte $81, $00, $9a, $25, $83, $84, $1d, $8d, $48, .lobyte(@env28), .hibyte(@env28), $cf, $00, $dd
@song2ch2loop:
	.byte $00, $42
	.word @song2ch2loop
@song2ch3:
@song2ref564:
	.byte $88, $14, $89, $14, $89, $9c, $1d, $83, $88, $14, $8f, $14, $95, $9c, $1d, $95
	.byte $41, $0c
	.word @song2ref564
	.byte $78, $50, $f9, $20, $82, $1f, $89, $7f
@song2ref591:
	.byte $8a, $21, $83
@song2ref594:
	.byte $21, $83, $9c, $1d, $83, $88, $14, $83
@song2ref602:
	.byte $8a, $21, $83, $21, $83, $88, $14, $83, $8a, $21, $83, $21, $83, $21, $83, $9c, $1d, $89
	.byte $41, $08
	.word @song2ref602
	.byte $88, $14, $83, $8a
	.byte $41, $14
	.word @song2ref594
	.byte $41, $0d
	.word @song2ref602
	.byte $83, $88, $14, $83
	.byte $41, $0a
	.word @song2ref591
	.byte $9c, $1d, $83, $88, $14, $83, $9c, $1d, $83, $88, $14, $83, $8a, $21, $83, $8e, $1f, $81, $50, $cc, $00, $83, $89, $00
	.byte $cb, $78, $50, $fe, $00, $82, $1f, $b5, $a7
@song2ch3loop:
	.byte $00, $42
	.word @song2ch3loop
@song2ch4:
@song2ref678:
	.byte $08, $89, $08, $89, $0b, $83, $08, $8f, $08, $95, $0b, $95
	.byte $41, $0c
	.word @song2ref678
	.byte $41, $0c
	.word @song2ref678
	.byte $41, $0c
	.word @song2ref678
	.byte $08, $95, $0c, $83, $08, $8f, $0c, $83, $08, $83, $08, $83, $0c, $83, $08, $83, $0c, $83, $08, $83, $0c, $83, $08, $dd
	.byte $08, $dd
@song2ch4loop:
	.byte $00, $42
	.word @song2ch4loop
@song3ch0:
	.byte $45, $06
@song3ch0loop:
	.byte $9f, $9f, $9f, $4d, $fe
@song3ref9:
	.byte $92, $1f, $81, $44, $1f, $81, $44, $23, $81, $44, $26, $81, $44, $2b, $83, $44, $48, .lobyte(@env13), .hibyte(@env13)
	.byte $13, $99, $48, .lobyte(@env13), .hibyte(@env13), $13, $81, $9f, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $9f, $9f, $9f
	.byte $41, $0f
	.word @song3ref9
	.byte $48, .lobyte(@env13), .hibyte(@env13), $18, $99, $48, .lobyte(@env13), .hibyte(@env13), $19, $81, $9f, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $9f, $9f, $9f, $9f, $86
@song3ref66:
	.byte $13, $44, $13, $44, $16, $44, $18, $44, $19, $44, $18, $44, $16, $44, $11, $44
	.byte $41, $10
	.word @song3ref66
	.byte $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $7f
@song3ref90:
	.byte $8c, $14, $85, $14, $85, $94, $14, $89, $8c, $14, $81, $83, $14, $85, $14, $81, $94, $14, $8d
	.byte $41, $0f
	.word @song3ref90
	.byte $41, $0f
	.word @song3ref90
	.byte $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
@song3ref119:
	.byte $32, $85, $32, $85, $33, $89, $32, $81, $83, $32, $85, $32, $81, $33, $8d
	.byte $41, $0f
	.word @song3ref119
	.byte $41, $0f
	.word @song3ref119
	.byte $42
	.word @song3ch4loop
