; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_1_=music_data_1_
.endif

music_data_1_:
	.byte 7
	.word @1_instruments
	.word @1_samples-5
	.word @1_song0ch0,@1_song0ch1,@1_song0ch2,@1_song0ch3,@1_song0ch4,307,256 ; 00 : DPCM ALIGNER (NOT FOR PLAYBACK)
	.word @1_song1ch0,@1_song1ch1,@1_song1ch2,@1_song1ch3,@1_song1ch4,323,269 ; 01 : Time for a Smackdown!
	.word @1_song2ch0,@1_song2ch1,@1_song2ch2,@1_song2ch3,@1_song2ch4,307,256 ; 02 : Pizza Deluxe!
	.word @1_song3ch0,@1_song3ch1,@1_song3ch2,@1_song3ch3,@1_song3ch4,307,256 ; 03 : Mondays
	.word @1_song4ch0,@1_song4ch1,@1_song4ch2,@1_song4ch3,@1_song4ch4,286,238 ; 04 : Funiculi Holiday
	.word @1_song5ch0,@1_song5ch1,@1_song5ch2,@1_song5ch3,@1_song5ch4,307,256 ; 05 : hmm look what u done did you found a secret :) V2
	.word @1_song6ch0,@1_song6ch1,@1_song6ch2,@1_song6ch3,@1_song6ch4,307,256 ; 06 : It's Pizza Time!

.export music_data_1_
.global FAMISTUDIO_DPCM_PTR

@1_instruments:
	.word @1_env18,@1_env47,@1_env30,@1_env0 ; 00 : 0 12 arp 1
	.word @1_env9,@1_env24,@1_env31,@1_env0 ; 01 : 5B square lmao.
	.word @1_env10,@1_env24,@1_env5,@1_env0 ; 02 : A piano
	.word @1_env44,@1_env24,@1_env30,@1_env0 ; 03 : ah
	.word @1_env20,@1_env16,@1_env33,@1_env13 ; 04 : Arp Strings
	.word @1_env15,@1_env25,@1_env4,@1_env0 ; 05 : bass
	.word @1_env15,@1_env24,@1_env30,@1_env0 ; 06 : blank
	.word @1_env39,@1_env43,@1_env33,@1_env13 ; 07 : Chord like arps
	.word @1_env23,@1_env24,@1_env14,@1_env0 ; 08 : distort guitar
	.word @1_env21,@1_env8,@1_env7,@1_env0 ; 09 : funny guitar
	.word @1_env35,@1_env24,@1_env33,@1_env0 ; 0a : funnyclick.mp4
	.word @1_env26,@1_env24,@1_env30,@1_env0 ; 0b : main
	.word @1_env37,@1_env49,@1_env1,@1_env0 ; 0c : Music box
	.word @1_env48,@1_env29,@1_env30,@1_env0 ; 0d : noise (get it) kick
	.word @1_env17,@1_env12,@1_env30,@1_env0 ; 0e : noise hat
	.word @1_env19,@1_env12,@1_env30,@1_env0 ; 0f : noise open hat
	.word @1_env22,@1_env28,@1_env30,@1_env0 ; 10 : noise snare
	.word @1_env11,@1_env24,@1_env6,@1_env0 ; 11 : secret bell
	.word @1_env36,@1_env24,@1_env33,@1_env0 ; 12 : secret square
	.word @1_env45,@1_env24,@1_env30,@1_env2 ; 13 : Short Tri Snare
	.word @1_env46,@1_env24,@1_env38,@1_env0 ; 14 : slightly better electric guitar
	.word @1_env32,@1_env40,@1_env30,@1_env0 ; 15 : Tri Toms

@1_env0:
	.byte $00,$c0,$7f,$00,$02
@1_env1:
	.byte $c1,$c0,$00,$01
@1_env2:
	.byte $80,$e0,$00,$01
@1_env3:
	.byte $00,$c0,$bd,$bb,$ba,$bb,$be,$c2,$c5,$c6,$c5,$c3,$00,$01
@1_env4:
	.byte $c2,$c3,$00,$01
@1_env5:
	.byte $c3,$7f,$00,$00
@1_env6:
	.byte $c2,$c1,$00,$01
@1_env7:
	.byte $c2,$c0,$00,$01
@1_env8:
	.byte $c7,$c0,$00,$01
@1_env9:
	.byte $00,$c9,$c6,$c1,$c3,$c4,$c5,$c2,$c3,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0f
@1_env10:
	.byte $0a,$c9,$c7,$c6,$c5,$c3,$c4,$c3,$00,$07,$c2,$02,$c1,$c1,$00,$0d
@1_env11:
	.byte $00,$c3,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$09
@1_env12:
	.byte $be,$c0,$00,$01
@1_env13:
	.byte $80,$bf,$c0,$c0,$00,$03
@1_env14:
	.byte $c3,$07,$c2,$07,$c1,$07,$c0,$07,$c1,$07,$c2,$06,$c2,$00,$00
@1_env15:
	.byte $00,$cf,$7f,$00,$02
@1_env16:
	.byte $c0,$c0,$b7,$c3,$00,$00
@1_env17:
	.byte $00,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@1_env18:
	.byte $00,$c2,$c4,$00,$02
@1_env19:
	.byte $00,$c5,$c4,$c3,$00,$03
@1_env20:
	.byte $08,$c1,$1e,$c2,$20,$c2,$00,$05,$c2,$02,$c1,$05,$c0,$00,$0c
@1_env21:
	.byte $06,$c7,$c5,$c4,$00,$03,$c3,$c2,$c1,$c0,$00,$09
@1_env22:
	.byte $00,$ca,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$0b
@1_env23:
	.byte $06,$cf,$cb,$c8,$00,$03,$c5,$c3,$c2,$c2,$c1,$02,$c0,$c0,$00,$0d
@1_env24:
	.byte $c0,$7f,$00,$01
@1_env25:
	.byte $c5,$c0,$00,$01
@1_env26:
	.byte $07,$c2,$c4,$c3,$c2,$00,$04,$c1,$02,$c0,$c0,$00,$0a
@1_env27:
	.byte $c0,$cc,$cc,$00,$00
@1_env28:
	.byte $c6,$ca,$00,$01
@1_env29:
	.byte $c6,$cd,$00,$01
@1_env30:
	.byte $7f,$00,$00
@1_env31:
	.byte $c2,$7f,$00,$00
@1_env32:
	.byte $00,$cf,$09,$c0,$00,$03
@1_env33:
	.byte $c0,$c2,$00,$01
@1_env34:
	.byte $00,$c0,$bf,$be,$02,$bf,$c1,$c2,$02,$c1,$00,$01
@1_env35:
	.byte $06,$c3,$c4,$c3,$00,$03,$c2,$c1,$c1,$c0,$00,$09
@1_env36:
	.byte $0a,$c2,$c3,$c4,$02,$c3,$c3,$c2,$00,$07,$c2,$04,$c1,$07,$c0,$04,$c0,$00,$10
@1_env37:
	.byte $09,$c8,$cb,$c8,$c7,$c6,$c5,$00,$06,$c4,$c3,$c2,$00,$0b
@1_env38:
	.byte $c3,$08,$c2,$00,$02
@1_env39:
	.byte $00,$c2,$0d,$c3,$5b,$c2,$00,$05
@1_env40:
	.byte $c0,$bd,$ba,$b7,$b4,$b1,$ae,$ab,$a8,$a5,$00,$09
@1_env41:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@1_env42:
	.byte $00,$c0,$bf,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$c1,$00,$01
@1_env43:
	.byte $c0,$c0,$c3,$bb,$00,$00
@1_env44:
	.byte $07,$c2,$c4,$c5,$c4,$00,$04,$c4,$c4,$c3,$04,$c2,$07,$c1,$0a,$c0,$00,$0f
@1_env45:
	.byte $00,$cf,$05,$c0,$00,$03
@1_env46:
	.byte $0d,$ca,$c7,$c6,$c7,$c8,$c7,$c7,$c5,$c5,$c7,$00,$0a,$c5,$c5,$c4,$c3,$c2,$00,$11
@1_env47:
	.byte $c0,$c0,$cc,$cc,$00,$00
@1_env48:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@1_env49:
	.byte $cc,$c0,$00,$01

@1_samples:
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4f,$40,$00 ; 00 arpeggiosquare.dmc (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$45,$2e,$01 ; 01 b1 bass.dmc (Pitch:5)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$47,$2e,$01 ; 02 b1 bass.dmc (Pitch:7)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$5f,$45,$00,$00 ; 03 b2 bass.dmc (Pitch:5)
	.byte $62+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$47,$00,$01 ; 04 b3 bass.dmc (Pitch:7)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4a,$00,$00 ; 05 dash.dmc (Pitch:10)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4d,$00,$00 ; 06 dash.dmc (Pitch:13)
	.byte $79+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0f,$40,$00 ; 07 Hebereke Kick.dmc (Pitch:15)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0c,$40,$00 ; 08 Hebereke Snare.dmc (Pitch:12)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0d,$40,$00 ; 09 Hebereke Snare.dmc (Pitch:13)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0e,$40,$00 ; 0a Hebereke Snare.dmc (Pitch:14)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0f,$40,$00 ; 0b Hebereke Snare.dmc (Pitch:15)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$00 ; 0c OrchHitA.dmc (Pitch:7)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$00 ; 0d OrchHitA.dmc (Pitch:8)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$00 ; 0e OrchHitA.dmc (Pitch:10)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$00 ; 0f OrchHitA.dmc (Pitch:11)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$00 ; 10 OrchHitA.dmc (Pitch:12)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 11 OrchHitA.dmc (Pitch:14)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 12 OrchHitA.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 13 OrchHitF.dmc (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 14 OrchHitF.dmc (Pitch:15)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$00 ; 15 OrchHitF#.dmc (Pitch:13)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 16 OrchHitF#.dmc (Pitch:14)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 17 OrchHitF#.dmc (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 18 OrchHitG.dmc (Pitch:1)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$02,$00,$01 ; 19 OrchHitG.dmc (Pitch:2)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 1a OrchHitG.dmc (Pitch:3)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 1b OrchHitG.dmc (Pitch:4)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$05,$00,$01 ; 1c OrchHitG.dmc (Pitch:5)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 1d OrchHitG.dmc (Pitch:6)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 1e OrchHitG.dmc (Pitch:7)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 1f OrchHitG.dmc (Pitch:9)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 20 OrchHitG.dmc (Pitch:10)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 21 OrchHitG.dmc (Pitch:12)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$01 ; 22 OrchHitG.dmc (Pitch:13)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 23 OrchHitG.dmc (Pitch:14)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 24 OrchHitG.dmc (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 25 OrchHitG#.dmc (Pitch:1)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 26 OrchHitG#.dmc (Pitch:3)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 27 OrchHitG#.dmc (Pitch:4)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 28 OrchHitG#.dmc (Pitch:6)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 29 OrchHitG#.dmc (Pitch:7)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$01 ; 2a OrchHitG#.dmc (Pitch:8)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 2b OrchHitG#.dmc (Pitch:9)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 2c OrchHitG#.dmc (Pitch:10)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$01 ; 2d OrchHitG#.dmc (Pitch:11)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 2e OrchHitG#.dmc (Pitch:12)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 2f OrchHitG#.dmc (Pitch:14)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 30 OrchHitG#.dmc (Pitch:15)
	.byte $74+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0d,$00,$00 ; 31 Pac_Kick44 (Pitch:13)
	.byte $74+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0e,$00,$00 ; 32 Pac_Kick44 (Pitch:14)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$00,$00 ; 33 Pac_Kick64 (Pitch:13)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0e,$00,$00 ; 34 Pac_Kick64 (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$44,$0f,$00,$01 ; 35 taunt.dmc (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$2f,$07,$00,$00 ; 36 untitled.dmc (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$34,$08,$00,$00 ; 37 untitled1.dmc (Pitch:8)

@1_song0ch0:
	.byte $45, $01, $ff, $ff, $ff, $ff
@1_song0ch0loop:
	.byte $00, $42
	.word @1_song0ch0loop
@1_song0ch1:
	.byte $ff, $ff, $ff, $ff
@1_song0ch1loop:
	.byte $00, $42
	.word @1_song0ch1loop
@1_song0ch2:
	.byte $ff, $ff, $ff, $ff
@1_song0ch2loop:
	.byte $00, $42
	.word @1_song0ch2loop
@1_song0ch3:
	.byte $ff, $ff, $ff, $ff
@1_song0ch3loop:
	.byte $00, $42
	.word @1_song0ch3loop
@1_song0ch4:
	.byte $34, $35, $32, $37, $33, $38, $06, $07, $36, $08, $0c, $0b, $0a, $09, $01, $13, $31, $25, $18, $15, $12, $30, $24, $17
	.byte $14, $23, $16, $11, $2f, $22, $10, $2e, $0f, $2d, $21, $2c, $20, $0e, $2b, $0d, $2a, $1f, $29, $1e, $1d, $28, $1c, $27
	.byte $1b, $1a, $26, $19, $05, $03, $04, $02, $00, $ff, $ff, $ff, $8d
@1_song0ch4loop:
	.byte $00, $42
	.word @1_song0ch4loop
@1_song1ch0:
	.byte $45, $03, $4d, $00, $88, $1e, $bd, $bf, $bf, $ab, $44, $85, $4e, $03, $84, $1c, $81, $1e, $81, $21, $81, $23, $95, $25
	.byte $a1, $44
@1_song1ref27:
	.byte $81, $25, $81, $23, $81, $21, $81, $1e, $81, $1c, $81, $1e, $81, $21, $81, $23, $81, $25, $81, $28, $81, $2a, $81, $2d
	.byte $85, $2a, $81, $2d, $81, $2a, $81, $2f, $a7, $48, .lobyte(@1_env34), .hibyte(@1_env34), $8d, $44, $81, $48, .lobyte(@1_env0)
	.byte .hibyte(@1_env0), $49, $2a, $81, $2f, $85, $2d, $81, $2a, $81, $28
	.byte $41, $0c
	.word @1_song1ref27
	.byte $85, $1c, $81, $1e, $85, $1c, $81, $25, $a1, $44, $81, $28, $85, $44, $00, $25, $85, $44, $00, $23, $85, $44, $00, $21
	.byte $85, $44, $00, $20, $85, $2a, $99, $44, $81, $2a, $9d, $44, $81, $00, $81, $2a, $85, $00, $85, $23, $85, $b3, $44, $81
	.byte $00, $85, $7c, $4d, $ff
@1_song1ref135:
	.byte $82
@1_song1ref136:
	.byte $19, $85, $1e, $85, $21, $85, $25, $85, $25, $85, $2a, $85, $2d, $85, $31, $85, $4d, $ff
	.byte $41, $10
	.word @1_song1ref136
@1_song1ref157:
	.byte $4d, $ff
@1_song1ref159:
	.byte $19, $85, $1c, $85, $1e, $85, $23, $85, $25, $85, $28, $85, $2a, $85, $2f, $85
	.byte $41, $10
	.word @1_song1ref157
@1_song1ref178:
	.byte $4d, $ff
@1_song1ref180:
	.byte $19, $85, $1e, $85, $25, $85, $28, $85, $25, $85, $2a, $85, $31, $85, $34, $85
	.byte $41, $10
	.word @1_song1ref178
@1_song1ref199:
	.byte $4d, $ff
@1_song1ref201:
	.byte $20, $85, $28, $85, $2a, $85, $2d, $85, $2c, $85, $34, $85, $4d, $ff, $36, $85, $4d, $ff, $39, $85
	.byte $41, $10
	.word @1_song1ref199
	.byte $4d, $ff
	.byte $41, $10
	.word @1_song1ref136
	.byte $4d, $ff
	.byte $41, $10
	.word @1_song1ref136
	.byte $41, $10
	.word @1_song1ref157
	.byte $41, $10
	.word @1_song1ref157
	.byte $41, $10
	.word @1_song1ref178
	.byte $41, $10
	.word @1_song1ref178
	.byte $41, $10
	.word @1_song1ref199
	.byte $41, $10
	.word @1_song1ref199
	.byte $7e, $90, $06, $95, $08, $95, $09, $8d, $87, $0b, $95, $09, $8d, $08, $8d, $7d, $12, $95, $14, $95, $15, $8d, $87, $17
	.byte $95, $7c, $19, $8d, $1c, $8d, $7b, $1e, $95, $20, $95, $21, $8d, $87, $23, $95, $25, $8d, $28, $8b, $44, $7a
@1_song1ref298:
	.byte $2d, $85
@1_song1ref300:
	.byte $2c, $85, $2a, $85, $2d, $85, $2c, $85, $2a, $85
	.byte $41, $0c
	.word @1_song1ref298
	.byte $2d, $85, $2c, $85, $2a, $85, $2d, $85, $2a, $91, $48, .lobyte(@1_env42), .hibyte(@1_env42), $ab, $83, $43, $4f, $0b, $36
	.byte $25, $83, $44, $9d
@1_song1ch0loop:
	.byte $00, $42
	.word @1_song1ch0loop
@1_song1ch1:
	.byte $4d, $00, $88, $19, $bd, $bf, $bf, $bf, $8e, $1e, $bd, $bf, $20, $bd, $bf, $7b, $25, $bd, $9f, $84, $25, $99, $44, $81
	.byte $25, $9d, $44, $81, $00, $81, $25, $85, $00, $85, $20, $85, $b3, $44, $81, $00, $85, $8b, $79, $4d, $fe
	.byte $41, $0d
	.word @1_song1ref135
	.byte $81, $4d, $fe, $83, $31, $85
	.byte $41, $0d
	.word @1_song1ref136
	.byte $81, $83, $31, $85, $4d, $fe
	.byte $41, $0d
	.word @1_song1ref159
	.byte $81, $83, $4d, $fe, $2f, $85
	.byte $41, $0d
	.word @1_song1ref159
	.byte $81, $4d, $fe, $83, $a4, $2f, $85
	.byte $41, $0d
	.word @1_song1ref180
	.byte $81, $4d, $fe, $83, $82, $34, $85
	.byte $41, $0d
	.word @1_song1ref180
	.byte $81, $4d, $fe, $83, $34, $85, $4d, $fe
	.byte $41, $0d
	.word @1_song1ref201
	.byte $81, $4d, $fe, $83, $39, $85, $4d, $fe
	.byte $41, $0d
	.word @1_song1ref201
	.byte $81, $7d, $4d, $00, $a8
@1_song1ref463:
	.byte $21, $87, $44, $81, $00, $1c, $87, $44, $81, $00, $1e, $8d, $48, .lobyte(@1_env3), .hibyte(@1_env3), $89, $44, $81, $48
	.byte .lobyte(@1_env0), .hibyte(@1_env0), $49, $00, $21, $83, $44, $1c, $85, $44, $81, $00, $81, $1e, $85, $44, $81, $00, $81
	.byte $21, $85, $44, $81, $00, $81, $23, $85, $85, $44, $21, $83, $44, $23, $83, $44, $21, $83, $44, $23, $83, $44, $25, $83
	.byte $44, $23, $83, $44, $21, $85, $87, $48, .lobyte(@1_env3), .hibyte(@1_env3), $8f, $44, $81, $00, $81, $48, .lobyte(@1_env0)
	.byte .hibyte(@1_env0), $49, $1c, $9d, $4d, $00
	.byte $41, $42
	.word @1_song1ref463
	.byte $48, .lobyte(@1_env0), .hibyte(@1_env0), $49, $81, $2a, $87, $48, .lobyte(@1_env3), .hibyte(@1_env3), $93, $44, $77, $8b, $48
	.byte .lobyte(@1_env0), .hibyte(@1_env0), $49, $90, $06, $95, $08, $95, $09, $81, $93, $0b, $95, $09, $8d, $08, $81, $8b, $12
	.byte $95, $14, $95, $15, $81, $91, $17, $95, $19, $8d, $1c, $83, $76, $89, $1e, $95, $20, $95, $21, $83, $99, $23, $95, $25
	.byte $89, $44, $8b
	.byte $41, $0c
	.word @1_song1ref298
	.byte $2d, $81, $83
	.byte $41, $0a
	.word @1_song1ref300
	.byte $2d, $85, $2c, $85, $2a, $81, $1e, $91, $48, .lobyte(@1_env42), .hibyte(@1_env42), $ab, $83, $43, $4f, $11, $2a, $1c, $83
	.byte $44, $9d
@1_song1ch1loop:
	.byte $00, $42
	.word @1_song1ch1loop
@1_song1ch2:
	.byte $8a
@1_song1ref648:
	.byte $12, $85, $1e, $81, $12, $85, $1e, $81, $15, $85, $12, $85, $21, $85, $12, $89, $00, $81
	.byte $41, $0b
	.word @1_song1ref648
	.byte $89, $00, $81, $12, $89, $00, $81
	.byte $41, $0b
	.word @1_song1ref648
	.byte $89, $00, $81, $12, $89, $00, $81, $0e, $85, $1a, $81, $0e, $85, $1a, $81, $12, $85, $0e, $89, $00, $81, $0e, $89
@1_song1ref702:
	.byte $00, $81
@1_song1ref704:
	.byte $aa
@1_song1ref705:
	.byte $23, $8d, $8a
@1_song1ref708:
	.byte $1e, $83, $00, $14, $8b, $00, $20, $83, $00, $15, $87, $00, $15, $81, $1a, $83, $00, $21, $83, $00, $19, $83, $00, $23
	.byte $81, $17, $83, $00, $1e, $81, $15, $83, $00, $10, $81, $00, $81, $12, $85, $1a, $85, $23, $81, $00, $81, $1c, $87, $00
	.byte $1a, $89, $19, $85, $17, $8d, $15, $89, $1e, $81, $14, $81, $00, $81, $18, $81, $00, $81, $12, $85, $1e, $81, $00, $81
	.byte $12, $81, $1e, $81, $12, $81, $00, $81, $12, $8d
	.byte $41, $42
	.word @1_song1ref708
	.byte $aa, $2e, $81, $2e, $81, $2e, $85, $28, $81, $28, $81, $28, $85
	.byte $41, $54
	.word @1_song1ref705
	.byte $41, $36
	.word @1_song1ref708
	.byte $aa, $23, $89, $8a, $1e, $81, $aa, $23, $81, $00, $81, $8a, $18, $81, $00, $81, $aa, $23, $85, $8a, $1e, $81, $00, $81
	.byte $aa, $23, $81, $8a, $1e, $81, $12, $81
	.byte $41, $56
	.word @1_song1ref702
	.byte $41, $50
	.word @1_song1ref708
	.byte $41, $54
	.word @1_song1ref704
	.byte $41, $50
	.word @1_song1ref708
	.byte $aa, $23, $81, $8c, $12, $b9, $a9
@1_song1ch2loop:
	.byte $00, $42
	.word @1_song1ch2loop
@1_song1ch3:
@1_song1ref868:
	.byte $9a, $14, $85, $9c, $21, $85
@1_song1ref874:
	.byte $a0, $14, $85, $9c, $21, $81, $a0, $15, $85
@1_song1ref883:
	.byte $16, $81, $9a, $14, $85, $a0, $14, $85, $9c, $21, $81, $a0, $14, $81
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
@1_song1ref903:
	.byte $9a, $14, $85, $9c, $21, $85, $a0, $14, $85, $9c, $21, $81, $a0, $15, $81, $70, $50, $04, $b0, $8c, $1f, $9d, $7a, $50
	.byte $f9, $10, $1f, $8d, $7f
	.byte $41, $10
	.word @1_song1ref874
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $0a
	.word @1_song1ref903
	.byte $9a, $14, $81, $14, $81, $14, $85, $a0, $14, $81, $14, $81, $14, $85, $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @1_song1ref874
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $0a
	.word @1_song1ref903
	.byte $9a, $14, $81, $a0
	.byte $41, $0a
	.word @1_song1ref883
	.byte $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @1_song1ref874
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @1_song1ref874
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $41, $14
	.word @1_song1ref868
	.byte $7a, $50, $fe, $00, $8c, $1f, $b7, $85, $00, $a7
@1_song1ch3loop:
	.byte $00, $42
	.word @1_song1ch3loop
@1_song1ch4:
	.byte $51, $47, $34, $bd, $51, $47, $34, $bd, $51, $47, $34, $bd, $51, $47, $34
@1_song1ref1103:
	.byte $bd
@1_song1ref1104:
	.byte $2e, $95, $2e, $95, $2e, $8d, $87, $34, $8d, $34, $8d
@1_song1ref1115:
	.byte $35, $8d, $34, $85, $87, $34, $8d, $34, $8d, $35, $8d, $34, $85, $87, $34, $8d, $34, $8d, $35, $8d, $34, $85
	.byte $41, $0f
	.word @1_song1ref1104
	.byte $2e, $a1, $35, $81
	.byte $41, $0d
	.word @1_song1ref1115
	.byte $41, $21
	.word @1_song1ref1104
	.byte $41, $18
	.word @1_song1ref1104
	.byte $2e, $8d, $2e, $8d, $2e, $8d, $2e, $8d, $2e, $95, $01, $a5, $2e, $95, $01, $a5, $2e, $95, $01, $a5, $2e, $8d, $2e, $8d
	.byte $2e, $9d, $2e, $95, $2e, $95, $2e, $8d, $01, $bd, $01, $bd, $01
	.byte $41, $22
	.word @1_song1ref1103
	.byte $41, $21
	.word @1_song1ref1104
	.byte $8d, $00, $af, $a9
@1_song1ch4loop:
	.byte $00, $42
	.word @1_song1ch4loop
@1_song2ch0:
	.byte $45, $06
@1_song2ch0loop:
	.byte $ff, $42
	.word @1_song2ch0loop
@1_song2ch1:
@1_song2ch1loop:
	.byte $ff, $42
	.word @1_song2ch1loop
@1_song2ch2:
@1_song2ch2loop:
	.byte $ff, $42
	.word @1_song2ch2loop
@1_song2ch3:
@1_song2ch3loop:
	.byte $ff, $42
	.word @1_song2ch3loop
@1_song2ch4:
@1_song2ch4loop:
	.byte $ff, $42
	.word @1_song2ch4loop
@1_song3ch0:
	.byte $45, $02
@1_song3ref3:
	.byte $4d, $00, $4e, $00, $96, $28, $9d, $2b, $9d, $2f, $9d, $2e, $9d, $44, $d1, $28, $81, $28, $81, $28, $81, $28, $8d, $43
	.byte $4f, $18, $34, $19
@1_song3ref31:
	.byte $8d, $44, $ad, $4e, $02, $3b, $85, $44, $95, $36, $85, $44, $8d, $3b, $85, $3a, $85, $44, $85, $8f, $36, $85, $44, $8d
	.byte $77, $3b, $85, $3a, $85, $44, $8d, $36, $85, $44, $8d, $74, $3b, $85, $3a, $85, $44, $8d, $7f, $4e, $00, $27, $9d, $2a
	.byte $9d, $2e, $9d, $2d, $9d, $44, $d1, $27, $81, $27, $81, $27, $81, $27, $8d, $43, $4f, $18, $33, $19
	.byte $41, $26
	.word @1_song3ref31
@1_song3ch0loop:
	.byte $7f
@1_song3ref104:
	.byte $4e, $00, $92, $15, $81, $00, $81, $7d, $15, $81, $00, $81, $7b, $15, $81, $00, $81, $79, $15, $81, $00, $81, $7f, $15
	.byte $95, $44, $85, $15, $81, $00, $81, $15, $81, $15, $81, $15, $81, $00, $81, $15, $81, $00, $81, $15, $95, $43, $4f, $3f
	.byte $21, $1b, $85, $96, $32, $85, $46, $01, $34, $89, $46, $00, $32, $89, $30, $85, $32, $85, $30, $85, $2d, $85, $2b, $85
	.byte $2d, $85, $28, $85, $29, $85, $28, $85, $44, $95, $7a, $50, $fc, $00, $8a, $03, $a5, $d7, $7f, $4d, $00, $4e, $00, $96
@1_song3ref200:
	.byte $26, $85, $28, $81, $44, $81, $2b, $85, $2d, $81, $44, $81, $30, $81, $2d, $81, $2f, $81, $30, $81, $35, $85, $37, $85
	.byte $39, $85, $44, $85, $00, $ad
	.byte $41, $28
	.word @1_song3ref104
@1_song3ref233:
	.byte $96, $2f, $85, $46, $01, $30, $89, $46, $00, $2f, $89, $2d, $85, $2f, $85, $2d, $85, $2b, $85, $28, $85, $2b, $85, $27
	.byte $85, $28, $85, $27, $85, $44, $95, $8f, $72, $4e, $03, $8c, $02, $bd, $71, $af, $7f, $4d, $00, $4e, $00, $96
@1_song3ref279:
	.byte $26, $85, $28, $81, $44, $81, $28, $85, $2b, $81, $44, $81, $2d, $81, $2b, $81, $2d, $81, $2f, $81, $2f, $85, $30, $85
	.byte $2f, $85, $44, $85, $00, $ad
	.byte $41, $63
	.word @1_song3ref104
	.byte $41, $28
	.word @1_song3ref104
	.byte $41, $3c
	.word @1_song3ref233
	.byte $79, $50, $ff, $10, $4d, $00, $8a, $09, $fd, $79, $50, $ff, $10, $4d, $00, $10, $f1, $80, $02, $89, $79, $50, $ff, $10
	.byte $4d, $00, $8a, $0f, $fd, $79, $50, $ff, $10, $4d, $00, $0e, $fd, $79, $50, $ff, $10, $4d, $00, $08, $fd, $79, $50, $ff
	.byte $10, $4d, $00, $0f, $fd, $79, $50, $ff, $10, $4d, $00, $0e, $fd, $79, $50, $ff, $30, $4d, $00, $0d, $dd, $7f, $80, $1c
	.byte $8b, $00, $8f, $73, $4d, $00, $8c, $1c, $bd, $1e, $bd, $4d, $00, $21, $bd, $4d, $ff, $87, $4d, $fe, $87, $4d, $fd, $87
	.byte $4d, $fc, $87, $4d, $fb, $87, $4d, $fa, $87, $4d, $f9, $87, $4d, $f8, $87, $4d, $f7, $87, $4d, $f6, $87, $4d, $f5, $87
	.byte $4d, $f4, $87, $4d, $f3, $87, $4d, $f2, $87, $4d, $f1, $87, $4d, $f0, $87, $4d, $ef, $87, $4d, $ee, $87, $4d, $ed, $87
	.byte $4d, $ec, $87, $4d, $eb, $87, $4d, $ea, $87, $4d, $e9, $87, $4d, $e8, $87, $4d, $e7, $87, $4d, $e6, $87, $4d, $e5, $87
	.byte $4d, $e4, $87, $4d, $e3, $87, $4d, $e2, $87, $4d, $e1, $87, $4d, $e0, $87, $4d, $df, $87, $4d, $de, $87, $4d, $dd, $87
	.byte $4d, $dc, $87, $4d, $db, $87, $4d, $da, $87, $4d, $d9, $87, $4d, $d8, $87, $4d, $00, $1b, $bd, $1c, $bd, $20, $bd, $4d
	.byte $00, $87, $4d, $01, $87, $4d, $02, $87, $4d, $03, $87, $4d, $04, $87, $4d, $05, $87, $4d, $06, $87, $4d, $07, $87, $4d
	.byte $08, $87, $4d, $09, $87, $4d, $0a, $87, $4d, $0b, $87, $4d, $0c, $87, $4d, $0d, $87, $4d, $0e, $87, $4d, $0f, $87, $4d
	.byte $10, $87, $4d, $11, $87, $4d, $12, $87, $4d, $13, $87, $4d, $14, $87, $4d, $15, $87, $4d, $16, $87, $4d, $17, $87, $4d
	.byte $18, $87, $4d, $19, $87, $4d, $1a, $87, $4d, $1b, $87, $4d, $1c, $87, $4d, $1d, $87, $4d, $1e, $87, $4d, $1f, $87, $4d
	.byte $20, $87, $4d, $21, $87, $4d, $22, $87, $4d, $23, $87, $4d, $24, $87, $4d, $25, $87, $4d, $26, $87, $4d, $27, $87, $7f
	.byte $41, $4c
	.word @1_song3ref3
	.byte $41, $26
	.word @1_song3ref31
	.byte $42
	.word @1_song3ch0loop
@1_song3ch1:
	.byte $4e, $00, $00, $95, $71
@1_song3ref668:
	.byte $4d, $01, $8c, $28, $9d, $2b, $9d, $2f, $9d, $2e, $85, $9b, $4d, $00, $00, $b5, $7f, $96, $27, $81, $27, $81, $27, $81
	.byte $27, $8d, $43, $4f, $13, $33, $19
@1_song3ref699:
	.byte $8d, $44, $bd, $71, $4e, $02, $8c, $3b, $85, $00, $95, $36, $85, $00, $8d, $3b, $85, $3a, $85, $00, $95, $36, $85, $00
	.byte $8d, $3b, $85, $3a, $85, $00, $8d, $36, $85, $00, $8d, $3b, $85, $3a, $85, $4e, $00, $00, $95, $4d, $01, $27, $9d, $2a
	.byte $9d, $2e, $9d, $2d, $85, $9b, $4d, $00, $00, $b5, $7f, $96, $26, $81, $26, $81, $26, $81, $26, $8d, $43, $4f, $13, $32
	.byte $19
	.byte $41, $23
	.word @1_song3ref699
@1_song3ch1loop:
@1_song3ref776:
	.byte $7f, $4e, $00, $92, $10, $81, $00, $81, $7d, $10, $81, $00, $81, $7b, $10, $81, $00, $81, $79, $10, $81, $00, $81, $7f
	.byte $10, $95, $44, $85, $10, $81, $00, $81, $10, $81, $10, $81, $10, $81, $00, $81, $10, $81, $00, $81, $10, $95, $43, $4f
	.byte $54, $1c, $16, $85, $7a, $50, $fc, $30, $8a, $04, $99, $71, $8c, $32, $85, $34, $89, $32, $89, $30, $85, $32, $85, $30
	.byte $85, $2d, $85, $2b, $85, $2d, $85, $28, $85, $29, $85, $28, $81, $8f, $72, $4e, $03, $03, $bd, $71, $af, $7a, $50, $fc
	.byte $40, $8a, $02, $95, $71, $4e, $00, $8c
	.byte $41, $1d
	.word @1_song3ref200
	.byte $95
	.byte $41, $28
	.word @1_song3ref776
@1_song3ref887:
	.byte $7a, $50, $fc, $30, $8a, $03, $99, $71, $8c, $2f, $85, $46, $01, $30, $89, $46, $00, $2f, $89, $2d, $85, $2f, $85, $2d
	.byte $85, $2b, $85, $28, $85, $2b, $85, $27, $85, $28, $85, $27, $81, $7a, $50, $fc, $00, $8a, $02, $a5, $d7, $7a, $50, $fc
	.byte $40, $01, $95, $71, $8c
	.byte $41, $1d
	.word @1_song3ref279
	.byte $95
	.byte $41, $48
	.word @1_song3ref776
	.byte $71, $4e, $00, $8c
	.byte $41, $1d
	.word @1_song3ref200
	.byte $95
	.byte $41, $28
	.word @1_song3ref776
	.byte $41, $1f
	.word @1_song3ref887
	.byte $71, $8c
	.byte $41, $1d
	.word @1_song3ref279
	.byte $95, $bf, $7f, $80, $10, $8d, $13, $8d, $18, $8d, $17, $8d, $df, $13, $9d, $16, $dd, $10, $9d, $0f, $bd, $17, $b5, $16
	.byte $81, $15, $81, $14, $f5, $17, $81, $19, $81, $1b, $f5, $19, $81, $1b, $81, $1c, $b5, $1c, $81, $1f, $81, $21, $b5, $23
	.byte $81, $21, $81, $20, $bd, $00, $9d, $21, $8d, $00, $8d, $78, $8a, $09, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73
	.byte $8f, $72, $8f, $71, $8f, $ff, $78, $09, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff
	.byte $78, $08, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff, $78, $08, $8d, $77, $8f, $76
	.byte $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff, $4e, $00, $00, $95
	.byte $41, $4d
	.word @1_song3ref668
	.byte $41, $23
	.word @1_song3ref699
	.byte $42
	.word @1_song3ch1loop
@1_song3ch2:
	.byte $8a, $09, $fd, $ff, $09, $fd, $ff, $08, $fd, $ff, $08, $fd, $ff
@1_song3ch2loop:
	.byte $8c
@1_song3ref1126:
	.byte $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb
	.byte $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb
	.byte $41, $30
	.word @1_song3ref1126
	.byte $41, $30
	.word @1_song3ref1126
	.byte $8a, $09, $fd, $09, $fd, $09, $fd, $09, $fd, $08, $fd, $08, $fd, $08, $fd, $08, $fd, $09, $fd, $ff, $09, $fd, $ff, $08
	.byte $fd, $ff, $08, $fd, $08, $fd, $42
	.word @1_song3ch2loop
@1_song3ch3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $70, $50, $02, $80, $8c, $20, $bd
@1_song3ch3loop:
	.byte $7f
@1_song3ref1230:
	.byte $9a, $14, $85, $9c, $23, $85, $23, $85, $21, $85, $23, $85, $23, $85, $21, $8d, $a0, $14, $9d, $9c, $21, $85, $23, $85
	.byte $23, $85, $23, $85, $9a, $14, $85, $9c, $23, $85, $23, $85, $21, $85, $23, $85, $23, $85, $21, $8d, $a0, $14, $9d, $9c
	.byte $21, $85, $23, $85, $23, $85, $23, $85
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $41, $30
	.word @1_song3ref1230
	.byte $75, $50, $fc, $40, $8c, $1e, $81, $83, $50, $fc, $30, $83, $83, $50, $fc, $20, $83, $83, $50, $fc, $10, $83, $83, $50
	.byte $fc, $00, $83, $db, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $50, $02, $80, $20, $bd
	.byte $42
	.word @1_song3ch3loop
@1_song3ch4:
	.byte $32, $bd, $32, $9d, $32, $9d, $d3, $38, $a9, $51, $80, $ff, $51, $80, $ff, $32, $bd, $32, $9d, $32, $9d, $d3, $37, $a9
	.byte $51, $80, $ff, $51, $80, $ff
@1_song3ch4loop:
@1_song3ref1401:
	.byte $35, $85, $34, $85, $34, $85, $35, $85, $34, $85, $34, $85, $35, $8d, $34, $8d, $34, $8d, $35, $85, $34, $85, $34, $85
	.byte $34, $85, $35, $85, $34, $85, $34, $85, $35, $85, $34, $85, $34, $85, $35, $8d, $34, $8d, $34, $8d, $35, $85, $34, $85
	.byte $34, $85, $34, $85
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
	.byte $41, $34
	.word @1_song3ref1401
@1_song3ref1486:
	.byte $33, $85, $32, $85, $32, $85, $33, $85, $32, $85, $32, $85, $33, $8d, $32, $8d, $32, $8d, $33, $85, $32, $85, $32, $85
	.byte $32, $85, $33, $85, $32, $85, $32, $85, $33, $85, $32, $85, $32, $85, $33, $8d, $32, $8d, $32, $8d, $33, $85, $32, $85
	.byte $32, $85, $32, $85
	.byte $41, $34
	.word @1_song3ref1486
	.byte $41, $34
	.word @1_song3ref1486
	.byte $41, $34
	.word @1_song3ref1486
	.byte $41, $2b
	.word @1_song3ref1486
	.byte $81, $38, $a1, $32, $85
	.byte $41, $34
	.word @1_song3ref1486
	.byte $41, $2b
	.word @1_song3ref1486
	.byte $81, $37, $a1, $32, $85
	.byte $41, $34
	.word @1_song3ref1486
	.byte $42
	.word @1_song3ch4loop
@1_song4ch0:
	.byte $45, $03
@1_song4ch0loop:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $98
@1_song4ref13:
	.byte $34, $89, $44, $81, $32, $89, $44, $81, $34, $89, $44, $81, $32, $89, $44, $81, $35, $85, $44, $34, $83, $32, $85, $44
	.byte $35, $83, $34, $8f, $44, $85, $00, $83
	.byte $41, $20
	.word @1_song4ref13
	.byte $41, $20
	.word @1_song4ref13
	.byte $41, $1a
	.word @1_song4ref13
@1_song4ref54:
	.byte $30, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d
	.byte $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $35, $8f, $44, $85, $00, $83, $37, $85
	.byte $44, $35, $83, $32, $85, $44, $35, $83, $30, $85, $44, $2e, $83, $2d, $85, $44, $2e, $83, $30, $85, $44, $2e, $83, $2d
	.byte $85, $44, $2b, $83, $29, $8b, $44, $35, $85, $44, $85, $00, $bd, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $41, $20
	.word @1_song4ref13
	.byte $41, $20
	.word @1_song4ref13
	.byte $41, $20
	.word @1_song4ref13
	.byte $41, $1a
	.word @1_song4ref13
	.byte $41, $5c
	.word @1_song4ref54
	.byte $42
	.word @1_song4ch0loop
@1_song4ch1:
@1_song4ch1loop:
	.byte $4b, $7e, $81, $00, $8b, $84
@1_song4ref171:
	.byte $29, $81, $44, $81, $00, $29, $81, $44, $81, $00, $8b, $29, $81, $44, $81, $00, $85, $8f, $29, $81, $44, $81, $00, $29
	.byte $81, $44, $81, $00, $8b, $32, $81, $44, $81, $00, $30, $81, $44, $81, $00, $8b
	.byte $41, $28
	.word @1_song4ref171
	.byte $41, $28
	.word @1_song4ref171
	.byte $41, $28
	.word @1_song4ref171
	.byte $41, $28
	.word @1_song4ref171
	.byte $41, $28
	.word @1_song4ref171
	.byte $41, $28
	.word @1_song4ref171
	.byte $41, $28
	.word @1_song4ref171
	.byte $26, $81, $44, $81, $00, $26, $81, $44, $81, $00, $85, $29, $81, $44, $81, $00, $85, $29, $81, $44, $81, $00, $8b, $26
	.byte $81, $44, $81, $00, $26, $81, $44, $29, $81, $44, $81, $00, $85, $26, $81, $44, $81, $00, $85, $8f, $2b, $81, $44, $81
	.byte $00, $2b, $81, $44, $81, $00, $8b, $2b, $81, $44, $81, $00, $85, $2b, $81, $44, $81, $00, $85, $2c, $81, $44, $81, $00
	.byte $85, $2d, $81, $44, $81, $00, $95, $7f, $4a, .lobyte(@1_env27), .hibyte(@1_env27)
@1_song4ref315:
	.byte $1f, $81, $44, $81, $00, $85, $4c, $1f, $81, $44, $81, $00, $85, $4c, $1d, $81, $44, $81, $4c, $1d, $81, $44, $81, $00
	.byte $8d, $4c, $1f, $81, $44, $81, $00, $85, $4c, $1f, $81, $44, $81, $4c, $1f, $81, $44, $81, $00, $85, $4c, $1c, $81, $44
	.byte $81, $4c, $1c, $81, $44, $81, $00, $85, $4c
	.byte $41, $30
	.word @1_song4ref315
	.byte $4c
	.byte $41, $30
	.word @1_song4ref315
	.byte $4c
	.byte $41, $30
	.word @1_song4ref315
	.byte $4c
	.byte $41, $30
	.word @1_song4ref315
	.byte $4c
	.byte $41, $30
	.word @1_song4ref315
	.byte $4c
	.byte $41, $30
	.word @1_song4ref315
	.byte $4c
	.byte $41, $30
	.word @1_song4ref315
	.byte $4c
	.byte $41, $26
	.word @1_song4ref315
	.byte $4c, $1d, $8d, $44, $85, $4c, $1d, $95, $44, $85, $4c, $1f, $95, $44, $85, $4c, $1d, $83, $44, $83, $00, $81, $4c, $1f
	.byte $83, $44, $83, $00, $81, $4c, $1c, $44, $83, $4c, $1c, $44, $83, $00, $8d, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $42
	.word @1_song4ch1loop
@1_song4ch2:
@1_song4ch2loop:
	.byte $8c
@1_song4ref455:
	.byte $11, $8d, $00, $87, $a6, $29, $83, $8c, $18, $8d, $a6, $29, $8d, $8c, $11, $8d, $00, $87, $a6, $29, $83, $8c, $18, $85
	.byte $00, $85, $a6, $29, $8c, $10, $83, $00, $85
	.byte $41, $19
	.word @1_song4ref455
	.byte $41, $19
	.word @1_song4ref455
	.byte $41, $19
	.word @1_song4ref455
	.byte $41, $19
	.word @1_song4ref455
	.byte $41, $19
	.word @1_song4ref455
	.byte $41, $19
	.word @1_song4ref455
	.byte $41, $19
	.word @1_song4ref455
	.byte $1a, $8d, $00, $87, $a6, $29, $83, $8c, $15, $8d, $a6, $29, $8d, $8c, $1a, $8d, $00, $87, $a6, $29, $83, $8c, $15, $8d
	.byte $a6, $29, $8d, $8c, $13, $8d, $00, $87, $a6, $29, $83, $8c, $17, $8d, $a6, $29, $8d, $8c, $1b, $87, $00, $83, $1c, $87
	.byte $a6, $29, $83, $8c, $1d, $8d, $a6, $29, $8d, $8c
@1_song4ref567:
	.byte $11, $8d, $00, $8d, $18, $8d, $00, $8d, $11, $8d, $00, $8d, $18, $85, $00, $85, $10, $85, $00, $85, $11, $8d, $00, $8d
	.byte $18, $8d, $00, $8d, $11, $8d, $00, $8d, $18, $85, $00, $85, $10, $85, $00, $85
	.byte $41, $28
	.word @1_song4ref567
	.byte $41, $28
	.word @1_song4ref567
	.byte $41, $28
	.word @1_song4ref567
	.byte $1a, $8d, $00, $8d, $15, $8d, $00, $8d, $1a, $8d, $00, $8d, $15, $8d, $00, $8d, $13, $8d, $00, $8d, $15, $8d, $00, $8d
	.byte $13, $87, $00, $83, $15, $87, $00, $83, $11, $8d, $00, $8d
	.byte $41, $28
	.word @1_song4ref567
	.byte $41, $28
	.word @1_song4ref567
	.byte $42
	.word @1_song4ch2loop
@1_song4ch3:
@1_song4ch3loop:
	.byte $7f
@1_song4ref663:
	.byte $9a, $14, $8d, $9e, $1f, $81, $50, $e2, $30, $83, $81, $7f, $a0, $14, $83, $9c, $21, $87, $21, $83, $a0, $14, $8d, $9a
	.byte $14, $8d, $9e, $1f, $81, $50, $e2, $30, $83, $81, $7f, $a0, $14, $83, $9c, $21, $87, $21, $83, $a0, $14, $8d
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
@1_song4ref736:
	.byte $9a, $14, $85, $9c, $21, $85, $a0, $14, $85, $14, $81, $14, $81, $9c, $21, $81, $a0, $14, $81, $14, $85, $14, $81, $14
	.byte $81, $14, $81, $14, $81, $9a, $14, $85, $9c, $21, $85, $a0, $14, $85, $14, $81, $14, $81, $9c, $21, $81, $a0, $14, $81
	.byte $14, $85, $14, $81, $14, $81, $14, $81, $14, $81
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $30
	.word @1_song4ref736
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $41, $1c
	.word @1_song4ref663
	.byte $42
	.word @1_song4ch3loop
@1_song4ch4:
@1_song4ch4loop:
@1_song4ref837:
	.byte $35, $8d, $35, $8d, $35, $87, $35, $93, $35, $8d, $35, $8d, $35, $87, $35, $93, $35, $8d, $35, $8d, $35, $87, $35, $93
	.byte $35, $8d, $35, $8d, $35, $87, $35, $93
	.byte $41, $20
	.word @1_song4ref837
	.byte $41, $20
	.word @1_song4ref837
	.byte $41, $20
	.word @1_song4ref837
	.byte $41, $20
	.word @1_song4ref837
@1_song4ref881:
	.byte $08, $8d, $35, $85, $35, $81, $35, $85, $35, $81, $35, $85, $35, $81, $35, $81, $35, $81, $35, $81, $08, $8d, $35, $85
	.byte $35, $81, $35, $85, $35, $81, $35, $85, $35, $81, $35, $81, $35, $81, $35, $81
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $28
	.word @1_song4ref881
	.byte $41, $20
	.word @1_song4ref837
	.byte $41, $20
	.word @1_song4ref837
	.byte $42
	.word @1_song4ch4loop
@1_song5ch0:
	.byte $45, $02
@1_song5ch0loop:
	.byte $7f, $4d, $01
@1_song5ref7:
	.byte $a4
@1_song5ref8:
	.byte $19, $83, $44, $89, $20, $83, $44, $89, $1f, $83, $44, $89, $19, $83, $44, $83, $1c, $83, $44, $89, $1c, $83, $44, $89
	.byte $1c, $83, $44, $89, $1c, $83, $1e, $83, $44, $89, $4d, $01
	.byte $41, $22
	.word @1_song5ref8
@1_song5ref47:
	.byte $17, $83, $44, $89, $20, $83, $44, $89, $1e, $83, $44, $89, $17, $83, $44, $83, $1b, $83, $44, $89, $1b, $83, $44, $89
	.byte $1b, $83, $44, $89, $1c, $83, $1e, $83, $44, $89, $17, $83, $44, $89, $20, $83, $44, $89, $1e, $83, $44, $89, $17, $83
	.byte $44, $83, $1b, $83, $44, $89, $1e, $83, $44, $89, $20, $83, $44, $89, $23, $83, $25, $83, $44, $89, $4d, $01
	.byte $41, $22
	.word @1_song5ref8
	.byte $4d, $01
	.byte $41, $22
	.word @1_song5ref8
	.byte $41, $3c
	.word @1_song5ref47
	.byte $4f, $7f, $2c, $14, $89, $00, $95, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $8b
	.byte $76, $4d, $ff, $a2
@1_song5ref156:
	.byte $2c, $8f, $33, $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $83, $8b, $4d, $ff, $2c, $8f, $33
	.byte $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $83, $8b, $2a, $8f, $33, $8f, $31, $8f, $2a, $89
	.byte $2e, $8f, $2e, $8f, $2e, $8f, $2f, $83, $31, $83, $8b, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f, $31, $8f, $33
	.byte $8f, $36, $83, $38, $83, $8b, $4d, $ff
	.byte $41, $4c
	.word @1_song5ref156
	.byte $4d, $ff
	.byte $41, $4b
	.word @1_song5ref156
	.byte $42
	.word @1_song5ch0loop
@1_song5ch1:
@1_song5ch1loop:
	.byte $7f, $4d, $ff
	.byte $41, $22
	.word @1_song5ref7
	.byte $4d, $ff
	.byte $41, $22
	.word @1_song5ref8
	.byte $41, $44
	.word @1_song5ref47
	.byte $4d, $ff
	.byte $41, $22
	.word @1_song5ref8
	.byte $4d, $ff
	.byte $41, $22
	.word @1_song5ref8
	.byte $41, $3c
	.word @1_song5ref47
	.byte $4f, $7f, $2c, $14, $89, $00, $95, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $4d
	.byte $00, $a2
@1_song5ref301:
	.byte $2c, $8f, $33, $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $8f, $4d, $00, $2c, $8f, $33, $8f
	.byte $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $8f, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f
	.byte $2e, $8f, $2e, $8f, $2f, $83, $31, $8f, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f, $31, $8f, $33, $8f, $36, $83
	.byte $38, $8f, $4d, $00
	.byte $41, $48
	.word @1_song5ref301
	.byte $4d, $00
	.byte $41, $48
	.word @1_song5ref301
	.byte $42
	.word @1_song5ch1loop
@1_song5ch2:
@1_song5ch2loop:
	.byte $8c
@1_song5ref390:
	.byte $1d, $0d, $87, $00, $83, $0d, $89, $00, $83, $47, $02, $25, $00, $8d, $0b, $8f, $1d, $0d, $87, $00, $83, $8a, $0d, $89
	.byte $00, $83, $47, $02, $8c, $25, $00, $9f, $1d, $0d, $87, $00, $83, $0d, $89, $00, $83, $47, $02, $25, $00, $8d, $0b, $8f
	.byte $1d, $0d, $87, $00, $83, $10, $8f, $25, $12, $8d, $14, $8f, $1d, $0b, $87, $00, $83, $0b, $89, $00, $83, $47, $02, $25
	.byte $00, $8d, $0a, $8f, $1d, $0b, $87, $00, $83, $0b, $89, $00, $83, $47, $02, $25, $00, $9f, $1d, $0b, $87, $00, $83, $0b
	.byte $89, $00, $83, $47, $02, $25, $00, $8d, $0a, $8f, $1d, $0b, $8d, $0f, $8f, $25, $12, $8d, $14, $8f
	.byte $41, $66
	.word @1_song5ref390
	.byte $41, $66
	.word @1_song5ref390
	.byte $41, $66
	.word @1_song5ref390
	.byte $41, $66
	.word @1_song5ref390
	.byte $41, $66
	.word @1_song5ref390
@1_song5ref521:
	.byte $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f
	.byte $41, $18
	.word @1_song5ref521
	.byte $42
	.word @1_song5ch2loop
@1_song5ch3:
@1_song5ch3loop:
@1_song5ref552:
	.byte $9a, $14, $89, $9c, $23, $83, $21, $89, $23, $83, $a0, $14, $89, $9c, $23, $83, $21, $89, $23, $83, $9a, $14, $89, $9c
	.byte $23, $83, $9e, $21, $89, $9c, $23, $83, $a0, $14, $89, $9c, $23, $83, $9e, $21, $89, $9c, $23, $83
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $19
	.word @1_song5ref552
	.byte $a1
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $20
	.word @1_song5ref552
	.byte $41, $19
	.word @1_song5ref552
	.byte $a1, $42
	.word @1_song5ch3loop
@1_song5ch4:
@1_song5ch4loop:
@1_song5ref683:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
	.byte $41, $18
	.word @1_song5ref683
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $42
	.word @1_song5ch4loop
@1_song6ch0:
	.byte $45, $02
@1_song6ch0loop:
	.byte $7f, $4d, $ff, $94
@1_song6ref8:
	.byte $28, $83, $44, $91, $79, $28, $83, $44, $81, $7f, $23, $83, $44, $89, $79, $28, $83, $44, $23, $83, $44, $81, $7f, $27
	.byte $83, $44, $89, $79, $23, $85, $27, $83, $44, $89, $77, $23, $85, $27, $83, $44, $8b, $7f, $4d, $ff
	.byte $41, $23
	.word @1_song6ref8
	.byte $7f, $4d, $ff
	.byte $41, $23
	.word @1_song6ref8
	.byte $7f, $4d, $ff
	.byte $41, $23
	.word @1_song6ref8
	.byte $00, $ff, $9d, $7f, $4d, $fe, $29, $44, $81, $00, $81, $2b, $44, $81, $00, $81, $4d, $fe, $29, $44, $81, $00, $81, $2b
	.byte $44, $81, $00, $81, $29, $44, $81, $00, $81, $4d, $fe, $27, $44, $81, $00, $81, $24, $44, $81, $00, $81, $23, $44, $81
	.byte $00, $81, $25, $87, $48, .lobyte(@1_env41), .hibyte(@1_env41), $9d, $43, $4f, $02, $31, $2f, $a3, $48, .lobyte(@1_env0), .hibyte(@1_env0)
	.byte $49, $43, $23, $00, $ff, $9d, $00, $ff, $9d, $4d, $ff, $86
@1_song6ref144:
	.byte $24, $91, $1f, $91, $22, $91, $44, $91, $24, $91, $1f, $91, $22, $91, $44, $91
@1_song6ref160:
	.byte $24, $87, $26, $87, $24, $87, $26, $87, $24, $87, $22, $87, $1f, $87, $1d, $87, $1f, $c3, $44, $87, $4d, $ff
	.byte $41, $20
	.word @1_song6ref144
	.byte $20, $87, $4d, $00, $43, $4f, $fb, $2c, $37, $c1, $4e, $03, $43, $2b, $75, $48, .lobyte(@1_env0), .hibyte(@1_env0), $49
	.byte $8c
@1_song6ref205:
	.byte $30, $87, $72, $89, $75, $4f, $0e, $3c, $37, $83, $43, $2b, $81, $72, $89, $75, $4f, $f2, $37, $3a, $81, $43, $2e, $83
	.byte $72, $93, $00, $87, $75, $4e, $03, $30, $87, $72, $89, $75, $4f, $0e, $3c, $37, $83, $43, $2b, $81, $72, $89, $75, $4f
	.byte $f2, $37, $3a, $81, $43, $2e, $83, $72, $93, $00, $87, $75, $48, .lobyte(@1_env0), .hibyte(@1_env0), $49, $30, $87, $4f
	.byte $f9, $3c, $3e, $81, $43, $32, $83, $4f, $07, $3e, $3c, $81, $43, $30, $83
@1_song6ref287:
	.byte $4f, $f9, $3c, $3e, $81, $43, $32, $83, $4f, $07, $3e, $3c, $81, $43, $30, $83, $4f, $08, $3c, $3a, $81, $43, $2e, $83
	.byte $4f, $07, $3a, $37, $85, $43, $2b, $4f, $06, $37, $36, $81, $43, $2a, $83, $4f, $fa, $36, $37, $81, $43, $2b, $8d, $48
	.byte .lobyte(@1_env41), .hibyte(@1_env41), $b1, $43, $4f, $03, $37, $36, $87, $48, .lobyte(@1_env0), .hibyte(@1_env0), $49
	.byte $41, $42
	.word @1_song6ref205
	.byte $48, .lobyte(@1_env0), .hibyte(@1_env0), $49
	.byte $41, $1e
	.word @1_song6ref205
	.byte $75, $48, .lobyte(@1_env0), .hibyte(@1_env0), $49, $4f, $f5, $36, $37, $43, $2b, $85, $4f, $f9, $37, $3b, $87, $4f, $f8
	.byte $3b, $3c, $43, $30, $85
	.byte $41, $13
	.word @1_song6ref287
	.byte $00, $cd, $48, .lobyte(@1_env0), .hibyte(@1_env0), $49
	.byte $41, $42
	.word @1_song6ref205
	.byte $48, .lobyte(@1_env0), .hibyte(@1_env0), $49
	.byte $41, $1e
	.word @1_song6ref205
	.byte $42
	.word @1_song6ch0loop
@1_song6ch1:
@1_song6ch1loop:
	.byte $ff, $8f, $c7, $70, $50, $02, $90, $90, $04, $c5, $7f, $04, $83, $44, $89, $04, $83, $44, $f5, $c7, $70, $50, $02, $90
	.byte $04, $c5, $7f, $04, $83, $44, $89, $04, $83, $44, $ff, $85, $ff, $9f, $ff, $9f, $ff, $9f, $85, $7a, $50, $02, $f0, $4d
	.byte $00, $86
@1_song6ref455:
	.byte $24, $91, $1f, $91, $22, $91, $44, $91, $24, $91, $1f, $91, $22, $91, $44, $8b, $85
	.byte $41, $13
	.word @1_song6ref160
	.byte $81, $85, $7a, $50, $02, $f0, $4d, $00
	.byte $41, $11
	.word @1_song6ref455
	.byte $41, $10
	.word @1_song6ref160
	.byte $20, $87, $43, $4f, $fb, $2c, $35, $bb, $43, $29, $4d, $01, $4e, $03, $8d, $71, $8c, $30, $91, $2b, $91, $2e, $9b, $00
	.byte $87, $30, $91, $2b, $91, $2e, $97, $8f, $30, $87, $32, $87, $30, $87, $32, $87, $30, $87, $2e, $87, $2b, $87, $2a, $87
	.byte $2b, $91, $48, .lobyte(@1_env41), .hibyte(@1_env41), $ab, $7c, $4d, $00, $90
@1_song6ref547:
	.byte $40, $0c, $87, $40, $0c, $87, $00, $87, $40, $0c, $9b, $40, $0a, $91, $40, $0c, $87, $40, $0c, $87, $00, $87, $03, $9b
	.byte $05, $91, $4d, $00
	.byte $41, $14
	.word @1_song6ref547
	.byte $4d, $00
	.byte $41, $14
	.word @1_song6ref547
	.byte $4d, $00
	.byte $41, $14
	.word @1_song6ref547
	.byte $4d, $00
	.byte $41, $14
	.word @1_song6ref547
	.byte $4d, $00
	.byte $41, $14
	.word @1_song6ref547
	.byte $4d, $00
	.byte $41, $14
	.word @1_song6ref547
	.byte $42
	.word @1_song6ch1loop
@1_song6ch2:
@1_song6ch2loop:
	.byte $ff, $8f, $ff, $8f, $8c, $10, $83, $00, $89, $10, $83, $00, $f5, $ff, $8f, $10, $83, $00, $89, $10, $83, $00, $ff, $85
	.byte $ff, $9f
@1_song6ref633:
	.byte $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47, $01, $31, $00, $8d, $1d, $47, $01, $2a, $00, $83, $47
	.byte $01, $2a, $00, $85, $1d, $47, $01, $31, $00, $83, $47, $01, $23, $00, $85
	.byte $41, $19
	.word @1_song6ref633
	.byte $41, $19
	.word @1_song6ref633
@1_song6ref678:
	.byte $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47
	.byte $01, $2a, $00, $83, $1d, $47, $01, $2a, $46, $00, $1d, $46, $00, $2a, $00, $1d, $47, $01, $2a, $00, $83, $1d, $47, $01
	.byte $23, $00, $83
	.byte $41, $19
	.word @1_song6ref633
	.byte $41, $19
	.word @1_song6ref633
	.byte $41, $19
	.word @1_song6ref633
	.byte $41, $1f
	.word @1_song6ref678
	.byte $41, $19
	.word @1_song6ref633
	.byte $41, $19
	.word @1_song6ref633
	.byte $41, $19
	.word @1_song6ref633
	.byte $41, $19
	.word @1_song6ref633
	.byte $ff, $9f, $ff, $9f, $7f
@1_song6ref758:
	.byte $4d, $00, $0c, $87, $0c, $87, $00, $87, $0c, $9b, $0a, $91, $0c, $87, $0c, $87, $00, $87, $0f, $9b, $11, $91
	.byte $41, $14
	.word @1_song6ref758
	.byte $41, $14
	.word @1_song6ref758
	.byte $41, $14
	.word @1_song6ref758
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $42
	.word @1_song6ch2loop
@1_song6ch3:
@1_song6ch3loop:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $9f, $ff, $9f, $9a
@1_song6ref812:
	.byte $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91
	.byte $14, $91, $14, $91, $14, $87, $14, $81, $46, $00, $14, $83, $14, $87, $14, $87
	.byte $41, $26
	.word @1_song6ref812
	.byte $41, $1d
	.word @1_song6ref812
	.byte $91, $14, $91, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $cf, $70, $50, $02, $f0, $8c, $21, $cd, $00, $a5, $f7
	.byte $00, $a5, $f7, $00, $a5, $f7, $42
	.word @1_song6ch3loop
@1_song6ch4:
@1_song6ch4loop:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
@1_song6ref900:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $10
	.word @1_song6ref900
	.byte $ff, $9f, $42
	.word @1_song6ch4loop
