; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_2=music_data_2_
.endif

music_data_2_:
	.byte 6
	.word @2instruments
	.word @2samples-5
	.word @2song0ch0,@2song0ch1,@2song0ch2,@2song0ch3,@2song0ch4,307,256 ; 00 : DPCM ALIGNER (NOT FOR PLAYBACK)
	.word @2song1ch0,@2song1ch1,@2song1ch2,@2song1ch3,@2song1ch4,307,256 ; 01 : Oregano Mirage 1
	.word @2song2ch0,@2song2ch1,@2song2ch2,@2song2ch3,@2song2ch4,307,256 ; 02 : A Grain of Bread in a Grain of Sand 1
	.word @2song3ch0,@2song3ch1,@2song3ch2,@2song3ch3,@2song3ch4,307,256 ; 03 : Unexpectancy (3) 1
	.word @2song4ch0,@2song4ch1,@2song4ch2,@2song4ch3,@2song4ch4,307,256 ; 04 : bye bye there! 1
	.word @2song5ch0,@2song5ch1,@2song5ch2,@2song5ch3,@2song5ch4,307,256 ; 05 : Hip to be Italian 1

.export music_data_2_
.global FAMISTUDIO_DPCM_PTR

@2instruments:
	.word @2env12,@2env27,@2env20,@2env0 ; 00 : 0 12 arp 1
	.word @2env10,@2env17,@2env20,@2env0 ; 01 : blank 1
	.word @2env16,@2env17,@2env8,@2env0 ; 02 : distort guitar
	.word @2env7,@2env1,@2env21,@2env0 ; 03 : electric guit 1
	.word @2env14,@2env4,@2env3,@2env0 ; 04 : funny guitar 1
	.word @2env24,@2env17,@2env20,@2env0 ; 05 : Instrument 1
	.word @2env29,@2env17,@2env2,@2env0 ; 06 : New instrument 1
	.word @2env28,@2env19,@2env20,@2env0 ; 07 : noise (get it) kick
	.word @2env11,@2env5,@2env20,@2env0 ; 08 : noise hat
	.word @2env13,@2env5,@2env20,@2env0 ; 09 : noise open hat 1
	.word @2env15,@2env18,@2env20,@2env0 ; 0a : noise snare
	.word @2env10,@2env17,@2env20,@2env0 ; 0b : NOT REAL 1
	.word @2env25,@2env17,@2env22,@2env0 ; 0c : secret square

@2env0:
	.byte $00,$c0,$7f,$00,$02
@2env1:
	.byte $c0,$b8,$b4,$b8,$c0,$00,$04
@2env2:
	.byte $c3,$7f,$00,$00
@2env3:
	.byte $c2,$c0,$00,$01
@2env4:
	.byte $c7,$c0,$00,$01
@2env5:
	.byte $be,$c0,$00,$01
@2env6:
	.byte $00,$c0,$bf,$be,$be,$bf,$c1,$c2,$c2,$c1,$00,$01
@2env7:
	.byte $06,$c1,$c2,$c5,$00,$03,$c3,$c2,$c1,$c1,$c0,$00,$0a
@2env8:
	.byte $c3,$07,$c2,$07,$c1,$07,$c0,$07,$c1,$07,$c2,$06,$c2,$00,$00
@2env9:
	.byte $00,$c0,$bf,$03,$c0,$c0,$c1,$02,$c1,$00,$01
@2env10:
	.byte $00,$cf,$7f,$00,$02
@2env11:
	.byte $00,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@2env12:
	.byte $00,$c2,$c4,$00,$02
@2env13:
	.byte $00,$c5,$c4,$c3,$00,$03
@2env14:
	.byte $06,$c7,$c5,$c4,$00,$03,$c3,$c2,$c1,$c0,$00,$09
@2env15:
	.byte $00,$ca,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$0b
@2env16:
	.byte $06,$cf,$cb,$c8,$00,$03,$c5,$c3,$c2,$c2,$c1,$02,$c0,$c0,$00,$0d
@2env17:
	.byte $c0,$7f,$00,$01
@2env18:
	.byte $c6,$ca,$00,$01
@2env19:
	.byte $c6,$cd,$00,$01
@2env20:
	.byte $7f,$00,$00
@2env21:
	.byte $c2,$7f,$00,$00
@2env22:
	.byte $c0,$c2,$00,$01
@2env23:
	.byte $00,$c0,$bf,$be,$02,$bf,$c1,$c2,$02,$c1,$00,$01
@2env24:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1f
@2env25:
	.byte $0a,$c2,$c3,$c4,$02,$c3,$c3,$c2,$00,$07,$c2,$04,$c1,$07,$c0,$04,$c0,$00,$10
@2env26:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01
@2env27:
	.byte $c0,$c0,$cc,$cc,$00,$00
@2env28:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@2env29:
	.byte $06,$c5,$c8,$c6,$00,$03,$c5,$c4,$c3,$c3,$c2,$03,$c1,$06,$c0,$00,$0e
@2env30:
	.byte $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01

@2samples:
	.byte $70+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4f,$40,$01 ; 00 arpeggiosquare.dmc (Pitch:15)
	.byte $56+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$45,$2e,$01 ; 01 b1 bass.dmc (Pitch:5)
	.byte $56+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$47,$2e,$01 ; 02 b1 bass.dmc (Pitch:7)
	.byte $44+.lobyte(FAMISTUDIO_DPCM_PTR),$5f,$45,$00,$00 ; 03 b2 bass.dmc (Pitch:5)
	.byte $5c+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$47,$00,$00 ; 04 b3 bass.dmc (Pitch:7)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4a,$00,$00 ; 05 dash.dmc (Pitch:10)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4d,$00,$00 ; 06 dash.dmc (Pitch:13)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0c,$40,$00 ; 07 Hebereke Snare.dmc (Pitch:12)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0d,$40,$00 ; 08 Hebereke Snare.dmc (Pitch:13)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0e,$40,$00 ; 09 Hebereke Snare.dmc (Pitch:14)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0f,$40,$00 ; 0a Hebereke Snare.dmc (Pitch:15)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$00 ; 0b OrchHitA.dmc (Pitch:7)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$00 ; 0c OrchHitA.dmc (Pitch:8)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$00 ; 0d OrchHitA.dmc (Pitch:10)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$00 ; 0e OrchHitA.dmc (Pitch:11)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$00 ; 0f OrchHitA.dmc (Pitch:12)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 10 OrchHitA.dmc (Pitch:14)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 11 OrchHitA.dmc (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 12 OrchHitF.dmc (Pitch:14)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 13 OrchHitF.dmc (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$01 ; 14 OrchHitF#.dmc (Pitch:13)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 15 OrchHitF#.dmc (Pitch:14)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 16 OrchHitF#.dmc (Pitch:15)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 17 OrchHitG.dmc (Pitch:1)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$02,$00,$01 ; 18 OrchHitG.dmc (Pitch:2)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 19 OrchHitG.dmc (Pitch:3)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 1a OrchHitG.dmc (Pitch:4)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$05,$00,$01 ; 1b OrchHitG.dmc (Pitch:5)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 1c OrchHitG.dmc (Pitch:6)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 1d OrchHitG.dmc (Pitch:7)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 1e OrchHitG.dmc (Pitch:9)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 1f OrchHitG.dmc (Pitch:10)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 20 OrchHitG.dmc (Pitch:12)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$01 ; 21 OrchHitG.dmc (Pitch:13)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 22 OrchHitG.dmc (Pitch:14)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 23 OrchHitG.dmc (Pitch:15)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$00 ; 24 OrchHitG#.dmc (Pitch:1)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$00 ; 25 OrchHitG#.dmc (Pitch:3)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$00 ; 26 OrchHitG#.dmc (Pitch:4)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$00 ; 27 OrchHitG#.dmc (Pitch:6)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$00 ; 28 OrchHitG#.dmc (Pitch:7)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$00 ; 29 OrchHitG#.dmc (Pitch:8)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$00 ; 2a OrchHitG#.dmc (Pitch:9)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$00 ; 2b OrchHitG#.dmc (Pitch:10)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$00 ; 2c OrchHitG#.dmc (Pitch:11)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$00 ; 2d OrchHitG#.dmc (Pitch:12)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 2e OrchHitG#.dmc (Pitch:14)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 2f OrchHitG#.dmc (Pitch:15)
	.byte $78+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0d,$00,$00 ; 30 Pac_Kick44 (Pitch:13)
	.byte $78+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0e,$00,$00 ; 31 Pac_Kick44 (Pitch:14)
	.byte $73+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$00,$00 ; 32 Pac_Kick50 (Pitch:13)
	.byte $73+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0e,$00,$00 ; 33 Pac_Kick50 (Pitch:14)
	.byte $44+.lobyte(FAMISTUDIO_DPCM_PTR),$44,$0f,$00,$01 ; 34 taunt.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2f,$07,$00,$00 ; 35 untitled.dmc (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$34,$08,$00,$01 ; 36 untitled1.dmc (Pitch:8)

@2song0ch0:
	.byte $45, $01, $ff, $ff, $ff, $ff
@2song0ch0loop:
	.byte $00, $42
	.word @2song0ch0loop
@2song0ch1:
	.byte $ff, $ff, $ff, $ff
@2song0ch1loop:
	.byte $00, $42
	.word @2song0ch1loop
@2song0ch2:
	.byte $ff, $ff, $ff, $ff
@2song0ch2loop:
	.byte $00, $42
	.word @2song0ch2loop
@2song0ch3:
	.byte $ff, $ff, $ff, $ff
@2song0ch3loop:
	.byte $00, $42
	.word @2song0ch3loop
@2song0ch4:
	.byte $33, $34, $31, $36, $32, $37, $06, $07, $35, $0b, $0a, $09, $08, $01, $12, $30, $24, $17, $14, $11, $2f, $23, $16, $13
	.byte $22, $15, $10, $2e, $21, $0f, $2d, $0e, $2c, $20, $2b, $1f, $0d, $2a, $0c, $29, $1e, $28, $1d, $1c, $27, $1b, $26, $1a
	.byte $19, $25, $18, $05, $03, $04, $02, $00, $ff, $ff, $ff, $8f
@2song0ch4loop:
	.byte $00, $42
	.word @2song0ch4loop
@2song1ch0:
@2song1ch0loop:
	.byte $81, $75
@2song1ref4:
	.byte $8c
@2song1ref5:
	.byte $08
@2song1ref6:
	.byte $00, $08, $81, $0f, $81, $08, $81, $0f, $81, $14, $85, $17, $00, $17, $81, $0b, $81, $17, $81, $00, $81, $17, $00, $17
	.byte $89, $12, $81, $06, $81, $00, $81, $17, $81, $00, $81, $0b, $81, $06, $81, $00, $81, $19, $81, $0d, $81, $08, $81, $10
	.byte $85, $00, $81, $12, $81, $00
@2song1ref60:
	.byte $81, $08, $83, $0b, $83, $0f, $81, $09, $83, $0d, $83, $10
	.byte $41, $0c
	.word @2song1ref60
	.byte $41, $0c
	.word @2song1ref60
@2song1ref78:
	.byte $81, $0f, $81, $10, $81, $0f, $81, $0d, $81, $0f, $81, $10, $81, $0f, $81, $0d, $7f, $84
@2song1ref96:
	.byte $08, $85, $44, $81, $08, $85, $44, $89, $0b, $85, $44, $81, $0b, $85, $44, $89, $06, $85, $44, $81, $06, $85, $44, $89
	.byte $01, $85, $44, $81, $01, $85, $44, $89
	.byte $41, $0f
	.word @2song1ref96
	.byte $85, $06, $85, $44, $85, $0b, $85, $44, $85, $0d, $85, $44, $85, $10, $89, $12, $85, $42
	.word @2song1ch0loop
@2song1ch1:
@2song1ch1loop:
	.byte $7c
	.byte $41, $43
	.word @2song1ref4
	.byte $41, $0c
	.word @2song1ref60
	.byte $41, $0c
	.word @2song1ref60
	.byte $41, $10
	.word @2song1ref78
	.byte $81, $7f, $00, $85, $86, $27, $81, $44, $81, $27, $81, $2c, $81, $44, $81, $2a, $81, $44, $81, $27, $25, $23, $85, $20
	.byte $81, $23, $81, $44, $81, $25, $81, $27, $81, $25, $81, $23, $81, $20, $81, $44, $81, $23, $81, $27, $81, $25, $85, $2a
	.byte $81, $2a, $44, $2a, $89, $44, $85, $87, $2c, $83, $4f, $40, $38, $2c, $43, $20, $81, $2c, $89, $2a, $99, $00, $c1, $42
	.word @2song1ch1loop
@2song1ch2:
@2song1ch2loop:
	.byte $ff, $7f, $47, $02, $82
@2song1ref245:
	.byte $1d, $00, $83, $47, $02, $25, $00, $83, $47, $02, $1d, $00, $83, $47, $02, $25, $00, $83, $47, $02
	.byte $41, $0c
	.word @2song1ref245
	.byte $47, $02
	.byte $41, $0b
	.word @2song1ref245
	.byte $a3, $88
	.byte $41, $39
	.word @2song1ref5
	.byte $41, $37
	.word @2song1ref6
	.byte $42
	.word @2song1ch2loop
@2song1ch3:
@2song1ch3loop:
	.byte $7f
@2song1ref286:
	.byte $90, $21, $23, $92, $20, $81, $90, $21, $23, $92, $20, $81, $90, $21, $23, $92, $20, $81
	.byte $41, $0c
	.word @2song1ref286
	.byte $41, $0c
	.word @2song1ref286
	.byte $41, $0c
	.word @2song1ref286
	.byte $41, $0c
	.word @2song1ref286
	.byte $90, $21
@2song1ref318:
	.byte $23, $92, $20, $81, $8e, $14, $90, $23, $92, $20, $81, $94, $14, $90, $23, $92, $20, $81, $8e, $14, $90, $23, $92, $20
	.byte $81, $94, $14, $90
	.byte $41, $10
	.word @2song1ref318
	.byte $90
	.byte $41, $10
	.word @2song1ref318
	.byte $90, $23, $92, $20, $81, $00, $9d
@2song1ref360:
	.byte $8e, $14, $90, $23, $92, $20, $90, $23, $94, $14, $81, $90, $23, $92, $20, $8e, $14, $90, $23, $92, $20, $90, $23, $94
	.byte $14, $81, $90, $23, $92, $20
	.byte $41, $10
	.word @2song1ref360
	.byte $41, $10
	.word @2song1ref360
	.byte $41, $10
	.word @2song1ref360
	.byte $41, $10
	.word @2song1ref360
	.byte $41, $10
	.word @2song1ref360
	.byte $41, $10
	.word @2song1ref360
	.byte $41, $10
	.word @2song1ref360
	.byte $42
	.word @2song1ch3loop
@2song1ch4:
	.byte $45, $05
@2song1ch4loop:
	.byte $45, $05, $ff, $45, $05, $ff, $ff, $45, $05, $ff, $42
	.word @2song1ch4loop
@2song2ch0:
	.byte $45, $02
@2song2ch0loop:
	.byte $7f, $4d, $ff
@2song2ref7:
	.byte $48, .lobyte(@2env0), .hibyte(@2env0), $49, $98
@2song2ref12:
	.byte $20, $89, $48, .lobyte(@2env26), .hibyte(@2env26), $9d, $44, $89, $48, .lobyte(@2env0), .hibyte(@2env0), $49, $1e, $83
	.byte $44, $83, $48, .lobyte(@2env26), .hibyte(@2env26), $85, $48, .lobyte(@2env0), .hibyte(@2env0), $49, $21, $89, $48, .lobyte(@2env26)
	.byte .hibyte(@2env26), $9d, $44, $89, $48, .lobyte(@2env0), .hibyte(@2env0), $49, $1e, $83, $44, $83, $48, .lobyte(@2env26)
	.byte .hibyte(@2env26), $85, $4d, $ff, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $4d, $ff, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
@2song2ref74:
	.byte $48, .lobyte(@2env0), .hibyte(@2env0), $49, $27, $83, $44, $83, $48, .lobyte(@2env26), .hibyte(@2env26), $85, $48, .lobyte(@2env0)
	.byte .hibyte(@2env0), $49, $28, $83, $44, $83, $48, .lobyte(@2env26), .hibyte(@2env26), $85, $48, .lobyte(@2env0), .hibyte(@2env0)
	.byte $49, $27, $83, $44, $83, $48, .lobyte(@2env26), .hibyte(@2env26), $85, $48, .lobyte(@2env0), .hibyte(@2env0), $49, $25
	.byte $83, $44, $83, $48, .lobyte(@2env26), .hibyte(@2env26), $85
	.byte $41, $14
	.word @2song2ref74
	.byte $4d, $ff, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $4d, $ff, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $4d, $ff, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $41, $14
	.word @2song2ref74
	.byte $41, $0a
	.word @2song2ref74
@2song2ref158:
	.byte $48, .lobyte(@2env0), .hibyte(@2env0), $49, $a3, $00, $ff, $8d, $00, $ff, $8d, $00, $ff, $8d, $00, $ff, $8d, $42
	.word @2song2ch0loop
@2song2ch1:
@2song2ch1loop:
	.byte $7f, $4d, $01
	.byte $41, $14
	.word @2song2ref7
	.byte $4d, $01, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $4d, $01, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $41, $14
	.word @2song2ref74
	.byte $41, $14
	.word @2song2ref74
	.byte $4d, $01, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $4d, $01, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $4d, $01, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $41, $14
	.word @2song2ref12
	.byte $41, $14
	.word @2song2ref74
	.byte $41, $0a
	.word @2song2ref74
	.byte $41, $0d
	.word @2song2ref158
	.byte $42
	.word @2song2ch1loop
@2song2ch2:
@2song2ch2loop:
	.byte $82
@2song2ref250:
	.byte $1d, $08, $99, $0c, $83, $25, $0c, $8d, $0f, $8f, $1d, $09, $99, $0d, $83, $25, $0d, $8d, $10, $8f
	.byte $41, $14
	.word @2song2ref250
	.byte $41, $14
	.word @2song2ref250
@2song2ref276:
	.byte $1d, $0f, $8d, $0f, $8f, $25, $0a, $8d, $0a, $8f, $1d, $03, $8d, $03, $8f, $25, $09, $8d, $09, $8f
	.byte $41, $14
	.word @2song2ref250
	.byte $41, $14
	.word @2song2ref250
	.byte $41, $14
	.word @2song2ref250
	.byte $41, $10
	.word @2song2ref276
	.byte $00, $9f
	.byte $41, $14
	.word @2song2ref250
	.byte $41, $14
	.word @2song2ref250
	.byte $41, $14
	.word @2song2ref250
	.byte $41, $14
	.word @2song2ref276
	.byte $42
	.word @2song2ch2loop
@2song2ch3:
@2song2ch3loop:
@2song2ref326:
	.byte $8e, $14, $89, $90, $23, $83, $21, $89, $23, $83, $94, $14, $89, $90, $23, $83, $21, $89, $23, $83, $8e, $14, $89, $90
	.byte $23, $83, $92, $21, $89, $90, $23, $83, $94, $14, $89, $90, $23, $83, $92, $21, $89, $90, $23, $83
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $19
	.word @2song2ref326
	.byte $a1
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $20
	.word @2song2ref326
	.byte $41, $20
	.word @2song2ref326
	.byte $42
	.word @2song2ch3loop
@2song2ch4:
@2song2ch4loop:
@2song2ref408:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
	.byte $41, $0a
	.word @2song2ref408
	.byte $ff, $8f, $ff, $8f, $42
	.word @2song2ch4loop
@2song3ch0:
	.byte $45, $02
@2song3ch0loop:
	.byte $74, $8a
@2song3ref6:
	.byte $25, $87, $4f, $e5, $31, $33, $43, $27, $8f, $4f, $1b, $33, $31, $43, $25, $85, $4f, $e5, $31, $33, $43, $27, $8f, $4f
	.byte $1b, $33, $31, $43, $25, $85, $4f, $e5, $31, $33, $43, $27, $8f, $4f, $1b, $33, $31, $43, $25, $85, $4f, $e5, $31, $33
	.byte $43, $27, $8f, $4f, $1b, $33, $31, $43, $25, $85, $4f, $e5, $31, $33, $43, $27, $85, $4f, $1b, $33, $31, $43, $25, $85
	.byte $4f, $e5, $31, $33, $43, $27, $85
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $41, $23
	.word @2song3ref6
	.byte $82, $1b, $4f, $dc, $27, $2e, $85, $43, $22, $9b, $48, .lobyte(@2env9), .hibyte(@2env9), $f7, $72, $ff, $9b, $48, .lobyte(@2env0)
	.byte .hibyte(@2env0), $49, $83, $7f, $4e, $02, $86
@2song3ref162:
	.byte $1b, $87, $1e, $83, $7c, $4e, $02, $1b, $87, $1e, $81, $7f, $1e, $87, $20, $83, $7c, $1e, $87, $20, $81, $7f, $20, $87
	.byte $22, $83, $7c, $20, $87, $22, $81, $7f, $22, $87, $23, $83, $7c, $22, $87, $23, $81, $7f, $22, $8d, $7c, $22, $95, $7f
	.byte $4e, $02
	.byte $41, $24
	.word @2song3ref162
	.byte $7f, $4e, $02
	.byte $41, $24
	.word @2song3ref162
	.byte $7f, $4e, $02
	.byte $41, $20
	.word @2song3ref162
	.byte $7f, $25, $8d, $7c, $25, $95, $7f, $4e, $02
	.byte $41, $24
	.word @2song3ref162
	.byte $7f, $4e, $02
	.byte $41, $24
	.word @2song3ref162
	.byte $7f, $4e, $02
	.byte $41, $24
	.word @2song3ref162
	.byte $7f, $4e, $02, $1b, $87, $1e, $83, $77, $4e, $02, $1b, $87, $1e, $81, $7f, $1e, $87, $20, $83, $77, $1e, $87, $20, $81
	.byte $7f, $20, $87, $22, $83, $77, $20, $87, $22, $81, $7f, $22, $87, $23, $83, $77, $22, $87, $23, $81, $7f, $25, $8d, $77
	.byte $25, $81, $75, $4e, $00, $82
@2song3ref305:
	.byte $25, $87, $27, $87, $2a, $91, $48, .lobyte(@2env23), .hibyte(@2env23), $9d, $48, .lobyte(@2env0), .hibyte(@2env0), $49
	.byte $89, $25, $87, $27, $87, $2c, $91, $48, .lobyte(@2env23), .hibyte(@2env23), $9d, $48, .lobyte(@2env0), .hibyte(@2env0)
	.byte $49, $89, $25, $87, $27, $87, $2e, $8b, $2c, $89, $2a, $8b, $2c, $8b, $2a, $89, $27, $8b, $2a, $91, $48, .lobyte(@2env23)
	.byte .hibyte(@2env23), $9d, $48, .lobyte(@2env0), .hibyte(@2env0), $49, $89
	.byte $41, $1f
	.word @2song3ref305
	.byte $91, $48, .lobyte(@2env23), .hibyte(@2env23), $ab, $48, .lobyte(@2env0), .hibyte(@2env0), $49, $89
	.byte $41, $24
	.word @2song3ref305
	.byte $41, $15
	.word @2song3ref305
	.byte $91, $48, .lobyte(@2env23), .hibyte(@2env23), $bb, $72, $cd, $48, .lobyte(@2env0), .hibyte(@2env0), $49, $81, $73
@2song3ref394:
	.byte $4f, $7f, $3a, $27
@2song3ref398:
	.byte $43, $1b, $46, $00, $4f, $80, $27, $2e, $43, $22, $81, $4f, $b9, $2e, $33, $43, $27, $46, $00, $4f, $7f, $33, $27, $43
	.byte $1b, $81, $4f, $80, $27, $2e, $43, $22, $46, $00, $4f, $80, $2e, $33, $43, $27, $81, $4f, $7f, $33, $27, $43, $1b, $46
	.byte $00, $4f, $80, $27, $2e, $43, $22, $81, $4f, $7f, $2e, $27
	.byte $41, $14
	.word @2song3ref398
	.byte $41, $13
	.word @2song3ref398
@2song3ref464:
	.byte $4f, $7f, $2e, $25, $43, $19, $46, $00, $4f, $80, $25, $2c, $43, $20, $81, $4f, $b0, $2c, $31, $43, $25, $46, $00, $4f
	.byte $7f, $31, $25, $43, $19, $81, $4f, $80, $25, $31, $43, $25, $46, $00, $4f, $7f, $31, $2c, $43, $20, $81, $4f, $7f, $2c
	.byte $25, $43, $19, $46, $00, $4f, $80, $25, $2c, $43, $20, $81
	.byte $41, $15
	.word @2song3ref394
	.byte $41, $14
	.word @2song3ref398
	.byte $41, $13
	.word @2song3ref398
	.byte $41, $14
	.word @2song3ref464
	.byte $41, $15
	.word @2song3ref394
	.byte $41, $14
	.word @2song3ref398
	.byte $41, $13
	.word @2song3ref398
	.byte $41, $14
	.word @2song3ref464
	.byte $41, $15
	.word @2song3ref394
	.byte $41, $14
	.word @2song3ref398
	.byte $41, $13
	.word @2song3ref398
	.byte $41, $14
	.word @2song3ref464
	.byte $41, $15
	.word @2song3ref394
	.byte $41, $14
	.word @2song3ref398
	.byte $41, $13
	.word @2song3ref398
	.byte $41, $14
	.word @2song3ref464
	.byte $41, $15
	.word @2song3ref394
	.byte $41, $14
	.word @2song3ref398
	.byte $41, $13
	.word @2song3ref398
	.byte $41, $14
	.word @2song3ref464
	.byte $41, $15
	.word @2song3ref394
	.byte $41, $14
	.word @2song3ref398
	.byte $41, $13
	.word @2song3ref398
	.byte $41, $14
	.word @2song3ref464
	.byte $41, $15
	.word @2song3ref394
	.byte $41, $14
	.word @2song3ref398
	.byte $41, $13
	.word @2song3ref398
	.byte $41, $14
	.word @2song3ref464
	.byte $42
	.word @2song3ch0loop
@2song3ch1:
@2song3ch1loop:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $84
@2song3ref621:
	.byte $03, $ff, $9d, $40, $0c, $ff, $9d, $40, $0b, $ff, $9d, $40, $0b, $ff, $9d, $03, $ff, $9d, $40, $0c, $ff, $9d, $40, $0b
	.byte $ff, $9d, $40, $0b, $ff, $9d
	.byte $41, $15
	.word @2song3ref621
	.byte $ff, $9f
@2song3ref656:
	.byte $03, $8b, $44, $83, $03, $8b, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83
	.byte $03, $81, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83, $03, $81, $44, $83, $01, $a5
	.byte $41, $2a
	.word @2song3ref656
	.byte $41, $2a
	.word @2song3ref656
	.byte $41, $2a
	.word @2song3ref656
	.byte $41, $2a
	.word @2song3ref656
	.byte $41, $2a
	.word @2song3ref656
	.byte $41, $2a
	.word @2song3ref656
	.byte $41, $2a
	.word @2song3ref656
@2song3ref719:
	.byte $40, $0b, $91, $44, $87, $40, $0b, $91, $44, $9b, $01, $91, $44, $87, $01, $91, $44, $9b, $40, $0a, $91, $44, $87, $40
	.byte $0a, $91, $44, $9b, $03, $91, $44, $87, $03, $87, $01, $91, $44, $87, $01, $87
	.byte $41, $24
	.word @2song3ref719
	.byte $41, $24
	.word @2song3ref719
	.byte $41, $17
	.word @2song3ref719
	.byte $87, $40, $0a, $91, $44, $87, $40, $0a, $91, $44, $87, $40, $0a, $87, $44, $87, $40, $0a, $87, $44, $87, $7f, $86
@2song3ref791:
	.byte $1b, $87, $22, $87, $44, $87, $22, $91, $48, .lobyte(@2env6), .hibyte(@2env6), $93, $48, .lobyte(@2env0), .hibyte(@2env0)
	.byte $49, $44, $87, $25, $87, $22, $87, $44, $87, $22, $91, $48, .lobyte(@2env6), .hibyte(@2env6), $93, $48, .lobyte(@2env0)
	.byte .hibyte(@2env0), $49, $44, $87, $25, $87, $44, $87, $25, $87, $44, $87, $22, $87, $44, $87, $22, $87, $44, $87, $26
	.byte $87, $43, $4f, $fe, $32, $33, $87, $48, .lobyte(@2env30), .hibyte(@2env30), $81, $43, $27, $ad, $48, .lobyte(@2env0), .hibyte(@2env0)
	.byte $49, $44, $87
	.byte $41, $16
	.word @2song3ref791
	.byte $28, $81, $43, $4f, $fd, $34, $35, $83, $48, .lobyte(@2env30), .hibyte(@2env30), $83, $43, $29, $83, $48, .lobyte(@2env0)
	.byte .hibyte(@2env0), $49, $44, $87, $2a, $87, $44, $87, $29, $87, $44, $87, $27, $91, $48, .lobyte(@2env30), .hibyte(@2env30)
	.byte $97, $48, .lobyte(@2env0), .hibyte(@2env0), $49, $44, $83, $19, $a5, $1b, $9b, $1d, $9b, $1e, $9b, $20, $9b, $22, $a5
	.byte $22, $9b, $20, $9b, $1e, $9b, $20, $9b, $1e, $91, $1d, $91, $1b, $9b, $1d, $9b, $1e, $9b, $20, $9b, $22, $a5, $27, $9b
	.byte $25, $9b, $27, $91, $29, $9b, $2a, $9b, $29, $91, $42
	.word @2song3ch1loop
@2song3ch2:
@2song3ch2loop:
@2song3ref958:
	.byte $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d
	.byte $41, $15
	.word @2song3ref958
	.byte $84, $12, $ff, $9d, $12, $ff, $9d, $0f, $ff, $9d, $82, $0c, $ff, $9d, $0b, $ff, $9d, $ff, $9f
@2song3ref1001:
	.byte $1d, $00, $85, $1d, $00, $85, $25, $00, $85, $1d, $00, $85, $1d, $00, $85, $1d, $00, $85, $25, $00, $85, $1d, $00, $85
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $41, $18
	.word @2song3ref1001
	.byte $1d, $00, $ff, $9b
@2song3ref1116:
	.byte $1d, $0f, $87, $00, $85, $25, $0f, $87, $00, $85, $1d, $0f, $83, $00, $0f, $87, $25, $0d, $85, $0f, $87, $1d, $00, $85
	.byte $0f, $87, $25, $0f, $85, $0f, $87, $1d, $0d, $8f, $25, $0d, $8f
	.byte $41, $25
	.word @2song3ref1116
	.byte $41, $25
	.word @2song3ref1116
	.byte $41, $25
	.word @2song3ref1116
	.byte $41, $25
	.word @2song3ref1116
	.byte $41, $25
	.word @2song3ref1116
	.byte $41, $25
	.word @2song3ref1116
	.byte $41, $25
	.word @2song3ref1116
	.byte $42
	.word @2song3ch2loop
@2song3ch3:
@2song3ch3loop:
	.byte $41, $15
	.word @2song3ref958
	.byte $41, $15
	.word @2song3ref958
	.byte $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $f7, $70, $50, $04, $a0, $82, $21, $a5, $77, $50, $fe, $00, $1c, $b5, $e7
	.byte $cf, $7f, $8e, $14, $81, $00, $83, $14, $81, $00, $8d, $14, $81, $00, $83, $14, $81, $00, $8d, $14, $81, $00, $83, $14
	.byte $81, $00, $83
@2song3ref1235:
	.byte $14, $87, $14, $87, $94, $14, $87, $8e, $14, $87, $14, $87, $14, $87, $94, $14, $87, $8e, $14, $87, $14, $87, $14, $87
	.byte $94, $14, $87, $8e, $14, $87
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $41, $18
	.word @2song3ref1235
	.byte $14, $f5, $70, $50, $04, $a0, $82, $21, $a5, $7f
@2song3ref1332:
	.byte $8e, $14, $87, $90, $21, $87, $94, $14, $87, $90, $21, $87, $8e, $14, $81, $46, $00, $90, $1f, $83, $21, $81, $46, $00
	.byte $1f, $83, $94, $14, $87, $90, $21, $87
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $41, $14
	.word @2song3ref1332
	.byte $42
	.word @2song3ch3loop
@2song3ch4:
@2song3ch4loop:
	.byte $41, $15
	.word @2song3ref958
	.byte $41, $15
	.word @2song3ref958
	.byte $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $00, $ff, $9d, $cf, $0b, $87, $0b, $91, $0a, $87, $0a, $91
	.byte $08, $87, $08, $87
@2song3ref1447:
	.byte $05, $f5, $03, $a5, $05, $f5, $03, $a5, $05, $f5, $03, $a5, $05, $f5, $03, $a5, $05, $f5, $03, $a5, $05, $f5, $03, $a5
	.byte $05, $f5, $03, $a5, $05, $f5, $03, $a5
@2song3ref1479:
	.byte $04, $9b, $04, $af, $03, $9b, $03, $af, $02, $9b, $02, $af, $05, $9b, $05, $87, $03, $9b, $03, $87
	.byte $41, $14
	.word @2song3ref1479
	.byte $41, $14
	.word @2song3ref1479
	.byte $04, $9b, $04, $af, $03, $9b, $03, $af, $02, $9b, $02, $9b, $02, $9b, $02, $9b, $02, $91, $02, $91
	.byte $41, $20
	.word @2song3ref1447
	.byte $42
	.word @2song3ch4loop
@2song4ch0:
	.byte $45, $02
@2song4ch0loop:
	.byte $4d, $ff, $91, $77, $4e, $03
@2song4ref10:
	.byte $8c
@2song4ref11:
	.byte $0d, $81, $00, $85, $0d, $81, $00, $81, $0d, $81, $00, $85, $0d, $81, $00, $81, $0d, $81, $44, $89, $0d, $81, $44, $89
	.byte $0b, $81, $44, $89, $0b, $81, $44, $81, $0d, $81, $00, $85, $0d, $81, $00, $81, $0d, $81, $00, $85, $0d, $81, $00, $81
	.byte $10, $91, $44, $81, $12, $8b, $4d, $ff, $91, $4e, $03
	.byte $41, $37
	.word @2song4ref11
	.byte $4e, $03
	.byte $41, $37
	.word @2song4ref11
	.byte $4e, $03
	.byte $41, $37
	.word @2song4ref11
	.byte $4e, $03
	.byte $41, $37
	.word @2song4ref11
	.byte $4e, $03
	.byte $41, $36
	.word @2song4ref11
	.byte $42
	.word @2song4ch0loop
@2song4ch1:
@2song4ch1loop:
	.byte $41, $31
	.word @2song4ref10
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2song4ref11
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2song4ref11
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2song4ref11
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2song4ref11
	.byte $89, $44, $89, $12, $97, $44, $83
	.byte $41, $31
	.word @2song4ref11
	.byte $89, $44, $89, $12, $97, $44, $83, $42
	.word @2song4ch1loop
@2song4ch2:
@2song4ch2loop:
	.byte $96
@2song4ref162:
	.byte $0d, $81, $00, $85, $82, $0d, $81, $00, $81, $0d, $81, $96, $0d, $00, $83, $82, $0d, $81, $00, $81, $0d, $85, $96, $0d
	.byte $83, $00, $82, $0d, $8d, $96, $0b, $8b, $00, $82, $0b, $85, $96, $0d, $81, $00, $85, $82, $0d, $81, $00, $81, $0d, $81
	.byte $96, $0d, $00, $83, $82, $0d, $81, $00, $81, $10, $85, $96, $10, $8d, $82, $12, $85, $96, $12, $95
	.byte $41, $36
	.word @2song4ref162
	.byte $41, $36
	.word @2song4ref162
	.byte $41, $36
	.word @2song4ref162
	.byte $41, $36
	.word @2song4ref162
	.byte $41, $36
	.word @2song4ref162
	.byte $42
	.word @2song4ch2loop
@2song4ch3:
@2song4ch3loop:
	.byte $8e
@2song4ref250:
	.byte $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95, $14, $95
	.byte $41, $14
	.word @2song4ref250
	.byte $41, $14
	.word @2song4ref250
	.byte $14, $95, $14, $95
@2song4ref280:
	.byte $1c, $89, $90, $21, $83, $23, $83, $8e, $1c, $89, $90, $21, $83, $23, $83, $8e, $1c, $89, $90, $21, $89, $8e, $1c, $83
	.byte $90, $21, $83, $22, $89, $8e
	.byte $41, $16
	.word @2song4ref280
	.byte $8e
	.byte $41, $16
	.word @2song4ref280
	.byte $8e
	.byte $41, $16
	.word @2song4ref280
	.byte $42
	.word @2song4ch3loop
@2song4ch4:
@2song4ch4loop:
	.byte $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $42
	.word @2song4ch4loop
@2song5ch0:
	.byte $45, $02
@2song5ch0loop:
	.byte $ff, $ff, $ff, $ff, $ff, $42
	.word @2song5ch0loop
@2song5ch1:
@2song5ch1loop:
	.byte $ff, $80, $11, $fd, $10, $fd, $11, $8d, $00, $ed, $ff, $42
	.word @2song5ch1loop
@2song5ch2:
@2song5ch2loop:
	.byte $82, $1d, $00, $9b, $1d, $00, $9b, $1d, $00, $9b, $1d, $00, $9b, $ff, $ff, $ff, $ff, $42
	.word @2song5ch2loop
@2song5ch3:
@2song5ch3loop:
@2song5ref49:
	.byte $8e, $14, $8d, $90, $21, $8d, $8e, $14, $8d, $90, $21, $8d
	.byte $41, $08
	.word @2song5ref49
	.byte $ff, $ff, $ff, $ff, $42
	.word @2song5ch3loop
@2song5ch4:
@2song5ch4loop:
	.byte $ff, $ff, $ff, $ff, $11, $85, $11, $a5, $11, $85, $11, $a5, $11, $85, $11, $95, $42
	.word @2song5ch4loop
