song_time_for_a_smackdown_1 = 0
song_pizza_deluxe_1 = 1
song_mondays_1 = 2
song_funiculi_holiday_1 = 3
song_hmm_look_what_u_done_did_you_found_a_secret_v2_1 = 4
song_oregano_mirage_1 = 5
song_a_grain_of_bread_in_a_grain_of_sand_1 = 6
song_bye_bye_there_1 = 7
song_max = 8

.if SONG_STRINGS
song_strings:
.asciiz "Time for a Smackdown! 1"
.asciiz "Pizza Deluxe! 1"
.asciiz "Mondays 1"
.asciiz "Funiculi Holiday 1"
.asciiz "hmm look what u done did you found a secret :) V2 1"
.asciiz "Oregano Mirage 1"
.asciiz "A Grain of Bread in a Grain of Sand 1"
.asciiz "bye bye there! 1"
.endif
