; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_1=music_data_1_
.endif

music_data_1_:
	.byte 8
	.word @1instruments
	.word @1samples-5
	.word @1song0ch0,@1song0ch1,@1song0ch2,@1song0ch3,@1song0ch4,307,256 ; 00 : DPCM ALIGNER (NOT FOR PLAYBACK)
	.word @1song1ch0,@1song1ch1,@1song1ch2,@1song1ch3,@1song1ch4,323,269 ; 01 : Time for a Smackdown!
	.word @1song2ch0,@1song2ch1,@1song2ch2,@1song2ch3,@1song2ch4,307,256 ; 02 : Pizza Deluxe! 1
	.word @1song3ch0,@1song3ch1,@1song3ch2,@1song3ch3,@1song3ch4,307,256 ; 03 : Mondays 1
	.word @1song4ch0,@1song4ch1,@1song4ch2,@1song4ch3,@1song4ch4,307,256 ; 04 : Funiculi Holiday 1
	.word @1song5ch0,@1song5ch1,@1song5ch2,@1song5ch3,@1song5ch4,307,256 ; 05 : hmm look what u done did you found a secret :) V2 1
	.word @1song6ch0,@1song6ch1,@1song6ch2,@1song6ch3,@1song6ch4,307,256 ; 06 : It's Pizza Time! 1
	.word @1song7ch0,@1song7ch1,@1song7ch2,@1song7ch3,@1song7ch4,307,256 ; 07 : The Death That I Deservioli 1

.export music_data_1_
.global FAMISTUDIO_DPCM_PTR

@1instruments:
	.word @1env21,@1env48,@1env32,@1env0 ; 00 : 0 12 arp 1
	.word @1env9,@1env27,@1env33,@1env0 ; 01 : 5B square lmao.
	.word @1env10,@1env27,@1env4,@1env0 ; 02 : A piano
	.word @1env46,@1env27,@1env32,@1env0 ; 03 : ah 1
	.word @1env23,@1env19,@1env35,@1env14 ; 04 : Arp Strings
	.word @1env18,@1env28,@1env3,@1env0 ; 05 : bass
	.word @1env18,@1env27,@1env32,@1env0 ; 06 : blank
	.word @1env18,@1env27,@1env32,@1env0 ; 07 : blank 1
	.word @1env41,@1env45,@1env35,@1env14 ; 08 : Chord like arps
	.word @1env26,@1env27,@1env17,@1env0 ; 09 : distort guitar
	.word @1env16,@1env1,@1env33,@1env0 ; 0a : electric guit 1
	.word @1env24,@1env8,@1env6,@1env0 ; 0b : funny guitar 1
	.word @1env38,@1env27,@1env35,@1env0 ; 0c : funnyclick.mp4 1
	.word @1env37,@1env27,@1env32,@1env0 ; 0d : Instrument 1
	.word @1env15,@1env27,@1env3,@1env0 ; 0e : Instrument 2
	.word @1env29,@1env27,@1env32,@1env0 ; 0f : main 1
	.word @1env49,@1env31,@1env32,@1env0 ; 10 : noise (get it) kick
	.word @1env20,@1env12,@1env32,@1env0 ; 11 : noise hat
	.word @1env22,@1env12,@1env32,@1env0 ; 12 : noise open hat 1
	.word @1env25,@1env30,@1env32,@1env0 ; 13 : noise snare
	.word @1env18,@1env27,@1env32,@1env0 ; 14 : Orchestral Hits
	.word @1env11,@1env27,@1env5,@1env0 ; 15 : secret bell 1
	.word @1env39,@1env27,@1env35,@1env0 ; 16 : secret square
	.word @1env47,@1env27,@1env40,@1env0 ; 17 : slightly better electric guitar
	.word @1env34,@1env42,@1env32,@1env0 ; 18 : Tri Toms

@1env0:
	.byte $00,$c0,$7f,$00,$02
@1env1:
	.byte $c0,$b8,$b4,$b8,$c0,$00,$04
@1env2:
	.byte $00,$c0,$bd,$bb,$ba,$bb,$be,$c2,$c5,$c6,$c5,$c3,$00,$01
@1env3:
	.byte $c2,$c3,$00,$01
@1env4:
	.byte $c3,$7f,$00,$00
@1env5:
	.byte $c2,$c1,$00,$01
@1env6:
	.byte $c2,$c0,$00,$01
@1env7:
	.byte $00,$c0,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$00,$01
@1env8:
	.byte $c7,$c0,$00,$01
@1env9:
	.byte $00,$c9,$c6,$c1,$c3,$c4,$c5,$c2,$c3,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0f
@1env10:
	.byte $0a,$c9,$c7,$c6,$c5,$c3,$c4,$c3,$00,$07,$c2,$02,$c1,$c1,$00,$0d
@1env11:
	.byte $00,$c3,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$09
@1env12:
	.byte $be,$c0,$00,$01
@1env13:
	.byte $00,$c0,$bf,$be,$be,$bf,$c1,$c2,$c2,$c1,$00,$01
@1env14:
	.byte $80,$bf,$c0,$c0,$00,$03
@1env15:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$10
@1env16:
	.byte $06,$c1,$c2,$c5,$00,$03,$c3,$c2,$c1,$c1,$c0,$00,$0a
@1env17:
	.byte $c3,$07,$c2,$07,$c1,$07,$c0,$07,$c1,$07,$c2,$06,$c2,$00,$00
@1env18:
	.byte $00,$cf,$7f,$00,$02
@1env19:
	.byte $c0,$c0,$b7,$c3,$00,$00
@1env20:
	.byte $00,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@1env21:
	.byte $00,$c2,$c4,$00,$02
@1env22:
	.byte $00,$c5,$c4,$c3,$00,$03
@1env23:
	.byte $08,$c1,$1e,$c2,$20,$c2,$00,$05,$c2,$02,$c1,$05,$c0,$00,$0c
@1env24:
	.byte $06,$c7,$c5,$c4,$00,$03,$c3,$c2,$c1,$c0,$00,$09
@1env25:
	.byte $00,$ca,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$0b
@1env26:
	.byte $06,$cf,$cb,$c8,$00,$03,$c5,$c3,$c2,$c2,$c1,$02,$c0,$c0,$00,$0d
@1env27:
	.byte $c0,$7f,$00,$01
@1env28:
	.byte $c5,$c0,$00,$01
@1env29:
	.byte $07,$c2,$c4,$c3,$c2,$00,$04,$c1,$02,$c0,$c0,$00,$0a
@1env30:
	.byte $c6,$ca,$00,$01
@1env31:
	.byte $c6,$cd,$00,$01
@1env32:
	.byte $7f,$00,$00
@1env33:
	.byte $c2,$7f,$00,$00
@1env34:
	.byte $00,$cf,$09,$c0,$00,$03
@1env35:
	.byte $c0,$c2,$00,$01
@1env36:
	.byte $00,$c0,$bf,$be,$02,$bf,$c1,$c2,$02,$c1,$00,$01
@1env37:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1f
@1env38:
	.byte $06,$c3,$c4,$c3,$00,$03,$c2,$c1,$c1,$c0,$00,$09
@1env39:
	.byte $0a,$c2,$c3,$c4,$02,$c3,$c3,$c2,$00,$07,$c2,$04,$c1,$07,$c0,$04,$c0,$00,$10
@1env40:
	.byte $c3,$08,$c2,$00,$02
@1env41:
	.byte $00,$c2,$0d,$c3,$5b,$c2,$00,$05
@1env42:
	.byte $c0,$bd,$ba,$b7,$b4,$b1,$ae,$ab,$a8,$a5,$00,$09
@1env43:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@1env44:
	.byte $00,$c0,$bf,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$c1,$00,$01
@1env45:
	.byte $c0,$c0,$c3,$bb,$00,$00
@1env46:
	.byte $07,$c2,$c4,$c5,$c4,$00,$04,$c4,$c4,$c3,$04,$c2,$07,$c1,$0a,$c0,$00,$0f
@1env47:
	.byte $0d,$ca,$c7,$c6,$c7,$c8,$c7,$c7,$c5,$c5,$c7,$00,$0a,$c5,$c5,$c4,$c3,$c2,$00,$11
@1env48:
	.byte $c0,$c0,$cc,$cc,$00,$00
@1env49:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@1env50:
	.byte $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01

@1samples:
	.byte $70+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4f,$40,$01 ; 00 arpeggiosquare.dmc (Pitch:15)
	.byte $56+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$45,$2e,$01 ; 01 b1 bass.dmc (Pitch:5)
	.byte $56+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$47,$2e,$01 ; 02 b1 bass.dmc (Pitch:7)
	.byte $44+.lobyte(FAMISTUDIO_DPCM_PTR),$5f,$45,$00,$00 ; 03 b2 bass.dmc (Pitch:5)
	.byte $5c+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$47,$00,$00 ; 04 b3 bass.dmc (Pitch:7)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4a,$00,$00 ; 05 dash.dmc (Pitch:10)
	.byte $30+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4d,$00,$00 ; 06 dash.dmc (Pitch:13)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0c,$40,$00 ; 07 Hebereke Snare.dmc (Pitch:12)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0d,$40,$00 ; 08 Hebereke Snare.dmc (Pitch:13)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0e,$40,$00 ; 09 Hebereke Snare.dmc (Pitch:14)
	.byte $3b+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0f,$40,$00 ; 0a Hebereke Snare.dmc (Pitch:15)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$00 ; 0b OrchHitA.dmc (Pitch:7)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$00 ; 0c OrchHitA.dmc (Pitch:8)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$00 ; 0d OrchHitA.dmc (Pitch:10)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$00 ; 0e OrchHitA.dmc (Pitch:11)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$00 ; 0f OrchHitA.dmc (Pitch:12)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 10 OrchHitA.dmc (Pitch:14)
	.byte $1e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 11 OrchHitA.dmc (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 12 OrchHitF.dmc (Pitch:14)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 13 OrchHitF.dmc (Pitch:15)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$01 ; 14 OrchHitF#.dmc (Pitch:13)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 15 OrchHitF#.dmc (Pitch:14)
	.byte $20+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 16 OrchHitF#.dmc (Pitch:15)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 17 OrchHitG.dmc (Pitch:1)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$02,$00,$01 ; 18 OrchHitG.dmc (Pitch:2)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 19 OrchHitG.dmc (Pitch:3)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 1a OrchHitG.dmc (Pitch:4)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$05,$00,$01 ; 1b OrchHitG.dmc (Pitch:5)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 1c OrchHitG.dmc (Pitch:6)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 1d OrchHitG.dmc (Pitch:7)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 1e OrchHitG.dmc (Pitch:9)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 1f OrchHitG.dmc (Pitch:10)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 20 OrchHitG.dmc (Pitch:12)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$01 ; 21 OrchHitG.dmc (Pitch:13)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 22 OrchHitG.dmc (Pitch:14)
	.byte $32+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 23 OrchHitG.dmc (Pitch:15)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$00 ; 24 OrchHitG#.dmc (Pitch:1)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$00 ; 25 OrchHitG#.dmc (Pitch:3)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$00 ; 26 OrchHitG#.dmc (Pitch:4)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$00 ; 27 OrchHitG#.dmc (Pitch:6)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$00 ; 28 OrchHitG#.dmc (Pitch:7)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$00 ; 29 OrchHitG#.dmc (Pitch:8)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$00 ; 2a OrchHitG#.dmc (Pitch:9)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$00 ; 2b OrchHitG#.dmc (Pitch:10)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$00 ; 2c OrchHitG#.dmc (Pitch:11)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$00 ; 2d OrchHitG#.dmc (Pitch:12)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 2e OrchHitG#.dmc (Pitch:14)
	.byte $0c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 2f OrchHitG#.dmc (Pitch:15)
	.byte $78+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0d,$00,$00 ; 30 Pac_Kick44 (Pitch:13)
	.byte $78+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0e,$00,$00 ; 31 Pac_Kick44 (Pitch:14)
	.byte $73+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$00,$00 ; 32 Pac_Kick64 (Pitch:13)
	.byte $73+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0e,$00,$00 ; 33 Pac_Kick64 (Pitch:14)
	.byte $44+.lobyte(FAMISTUDIO_DPCM_PTR),$44,$0f,$00,$01 ; 34 taunt.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2f,$07,$00,$00 ; 35 untitled.dmc (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$34,$08,$00,$01 ; 36 untitled1.dmc (Pitch:8)

@1song0ch0:
	.byte $45, $01, $ff, $ff, $ff, $ff
@1song0ch0loop:
	.byte $00, $42
	.word @1song0ch0loop
@1song0ch1:
	.byte $ff, $ff, $ff, $ff
@1song0ch1loop:
	.byte $00, $42
	.word @1song0ch1loop
@1song0ch2:
	.byte $ff, $ff, $ff, $ff
@1song0ch2loop:
	.byte $00, $42
	.word @1song0ch2loop
@1song0ch3:
	.byte $ff, $ff, $ff, $ff
@1song0ch3loop:
	.byte $00, $42
	.word @1song0ch3loop
@1song0ch4:
	.byte $33, $34, $31, $36, $32, $37, $06, $07, $35, $0b, $0a, $09, $08, $01, $12, $30, $24, $17, $14, $11, $2f, $23, $16, $13
	.byte $22, $15, $10, $2e, $21, $0f, $2d, $0e, $2c, $20, $2b, $1f, $0d, $2a, $0c, $29, $1e, $28, $1d, $1c, $27, $1b, $26, $1a
	.byte $19, $25, $18, $05, $03, $04, $02, $00, $ff, $ff, $ff, $8f
@1song0ch4loop:
	.byte $00, $42
	.word @1song0ch4loop
@1song1ch0:
	.byte $45, $03, $4d, $00, $88, $1e, $bd, $bf, $bf, $ab, $44, $85, $4e, $03, $84, $1c, $81, $1e, $81, $21, $81, $23, $95, $25
	.byte $a1, $44
@1song1ref27:
	.byte $81, $25, $81, $23, $81, $21, $81, $1e, $81, $1c, $81, $1e, $81, $21, $81, $23, $81, $25, $81, $28, $81, $2a, $81, $2d
	.byte $85, $2a, $81, $2d, $81, $2a, $81, $2f, $a7, $48, .lobyte(@1env36), .hibyte(@1env36), $8d, $44, $81, $48, .lobyte(@1env0)
	.byte .hibyte(@1env0), $49, $2a, $81, $2f, $85, $2d, $81, $2a, $81, $28
	.byte $41, $0c
	.word @1song1ref27
	.byte $85, $1c, $81, $1e, $85, $1c, $81, $25, $a1, $44, $81, $28, $85, $44, $00, $25, $85, $44, $00, $23, $85, $44, $00, $21
	.byte $85, $44, $00, $20, $85, $2a, $99, $44, $81, $2a, $9d, $44, $81, $00, $81, $2a, $85, $00, $85, $23, $85, $b3, $44, $81
	.byte $00, $85, $7c, $4d, $ff
@1song1ref135:
	.byte $82
@1song1ref136:
	.byte $19, $85, $1e, $85, $21, $85, $25, $85, $25, $85, $2a, $85, $2d, $85, $31, $85, $4d, $ff
	.byte $41, $10
	.word @1song1ref136
@1song1ref157:
	.byte $4d, $ff
@1song1ref159:
	.byte $19, $85, $1c, $85, $1e, $85, $23, $85, $25, $85, $28, $85, $2a, $85, $2f, $85
	.byte $41, $10
	.word @1song1ref157
@1song1ref178:
	.byte $4d, $ff
@1song1ref180:
	.byte $19, $85, $1e, $85, $25, $85, $28, $85, $25, $85, $2a, $85, $31, $85, $34, $85
	.byte $41, $10
	.word @1song1ref178
@1song1ref199:
	.byte $4d, $ff
@1song1ref201:
	.byte $20, $85, $28, $85, $2a, $85, $2d, $85, $2c, $85, $34, $85, $4d, $ff, $36, $85, $4d, $ff, $39, $85
	.byte $41, $10
	.word @1song1ref199
	.byte $4d, $ff
	.byte $41, $10
	.word @1song1ref136
	.byte $4d, $ff
	.byte $41, $10
	.word @1song1ref136
	.byte $41, $10
	.word @1song1ref157
	.byte $41, $10
	.word @1song1ref157
	.byte $41, $10
	.word @1song1ref178
	.byte $41, $10
	.word @1song1ref178
	.byte $41, $10
	.word @1song1ref199
	.byte $41, $10
	.word @1song1ref199
	.byte $7e, $92, $06, $95, $08, $95, $09, $8d, $87, $0b, $95, $09, $8d, $08, $8d, $7d, $12, $95, $14, $95, $15, $8d, $87, $17
	.byte $95, $7c, $19, $8d, $1c, $8d, $7b, $1e, $95, $20, $95, $21, $8d, $87, $23, $95, $25, $8d, $28, $8b, $44, $7a
@1song1ref298:
	.byte $2d, $85
@1song1ref300:
	.byte $2c, $85, $2a, $85, $2d, $85, $2c, $85, $2a, $85
	.byte $41, $0c
	.word @1song1ref298
	.byte $2d, $85, $2c, $85, $2a, $85, $2d, $85, $2a, $91, $48, .lobyte(@1env44), .hibyte(@1env44), $ab, $83, $43, $4f, $0b, $36
	.byte $25, $83, $44, $9d
@1song1ch0loop:
	.byte $00, $42
	.word @1song1ch0loop
@1song1ch1:
	.byte $4d, $00, $88, $19, $bd, $bf, $bf, $bf, $90, $1e, $bd, $bf, $20, $bd, $bf, $7b, $25, $bd, $9f, $84, $25, $99, $44, $81
	.byte $25, $9d, $44, $81, $00, $81, $25, $85, $00, $85, $20, $85, $b3, $44, $81, $00, $85, $8b, $79, $4d, $fe
	.byte $41, $0d
	.word @1song1ref135
	.byte $81, $4d, $fe, $83, $31, $85
	.byte $41, $0d
	.word @1song1ref136
	.byte $81, $83, $31, $85, $4d, $fe
	.byte $41, $0d
	.word @1song1ref159
	.byte $81, $83, $4d, $fe, $2f, $85
	.byte $41, $0d
	.word @1song1ref159
	.byte $81, $4d, $fe, $83, $ac, $2f, $85
	.byte $41, $0d
	.word @1song1ref180
	.byte $81, $4d, $fe, $83, $82, $34, $85
	.byte $41, $0d
	.word @1song1ref180
	.byte $81, $4d, $fe, $83, $34, $85, $4d, $fe
	.byte $41, $0d
	.word @1song1ref201
	.byte $81, $4d, $fe, $83, $39, $85, $4d, $fe
	.byte $41, $0d
	.word @1song1ref201
	.byte $81, $7d, $4d, $00, $ae
@1song1ref463:
	.byte $21, $87, $44, $81, $00, $1c, $87, $44, $81, $00, $1e, $8d, $48, .lobyte(@1env2), .hibyte(@1env2), $89, $44, $81, $48
	.byte .lobyte(@1env0), .hibyte(@1env0), $49, $00, $21, $83, $44, $1c, $85, $44, $81, $00, $81, $1e, $85, $44, $81, $00, $81
	.byte $21, $85, $44, $81, $00, $81, $23, $85, $85, $44, $21, $83, $44, $23, $83, $44, $21, $83, $44, $23, $83, $44, $25, $83
	.byte $44, $23, $83, $44, $21, $85, $87, $48, .lobyte(@1env2), .hibyte(@1env2), $8f, $44, $81, $00, $81, $48, .lobyte(@1env0)
	.byte .hibyte(@1env0), $49, $1c, $9d, $4d, $00
	.byte $41, $42
	.word @1song1ref463
	.byte $48, .lobyte(@1env0), .hibyte(@1env0), $49, $81, $2a, $87, $48, .lobyte(@1env2), .hibyte(@1env2), $93, $44, $77, $8b, $48
	.byte .lobyte(@1env0), .hibyte(@1env0), $49, $92, $06, $95, $08, $95, $09, $81, $93, $0b, $95, $09, $8d, $08, $81, $8b, $12
	.byte $95, $14, $95, $15, $81, $91, $17, $95, $19, $8d, $1c, $83, $76, $89, $1e, $95, $20, $95, $21, $83, $99, $23, $95, $25
	.byte $89, $44, $8b
	.byte $41, $0c
	.word @1song1ref298
	.byte $2d, $81, $83
	.byte $41, $0a
	.word @1song1ref300
	.byte $2d, $85, $2c, $85, $2a, $81, $1e, $91, $48, .lobyte(@1env44), .hibyte(@1env44), $ab, $83, $43, $4f, $11, $2a, $1c, $83
	.byte $44, $9d
@1song1ch1loop:
	.byte $00, $42
	.word @1song1ch1loop
@1song1ch2:
	.byte $8a
@1song1ref648:
	.byte $12, $85, $1e, $81, $12, $85, $1e, $81, $15, $85, $12, $85, $21, $85, $12, $89, $00, $81
	.byte $41, $0b
	.word @1song1ref648
	.byte $89, $00, $81, $12, $89, $00, $81
	.byte $41, $0b
	.word @1song1ref648
	.byte $89, $00, $81, $12, $89, $00, $81, $0e, $85, $1a, $81, $0e, $85, $1a, $81, $12, $85, $0e, $89, $00, $81, $0e, $89
@1song1ref702:
	.byte $00, $81
@1song1ref704:
	.byte $b0
@1song1ref705:
	.byte $23, $8d, $8a
@1song1ref708:
	.byte $1e, $83, $00, $14, $8b, $00, $20, $83, $00, $15, $87, $00, $15, $81, $1a, $83, $00, $21, $83, $00, $19, $83, $00, $23
	.byte $81, $17, $83, $00, $1e, $81, $15, $83, $00, $10, $81, $00, $81, $12, $85, $1a, $85, $23, $81, $00, $81, $1c, $87, $00
	.byte $1a, $89, $19, $85, $17, $8d, $15, $89, $1e, $81, $14, $81, $00, $81, $18, $81, $00, $81, $12, $85, $1e, $81, $00, $81
	.byte $12, $81, $1e, $81, $12, $81, $00, $81, $12, $8d
	.byte $41, $42
	.word @1song1ref708
	.byte $b0, $2e, $81, $2e, $81, $2e, $85, $28, $81, $28, $81, $28, $85
	.byte $41, $54
	.word @1song1ref705
	.byte $41, $36
	.word @1song1ref708
	.byte $b0, $23, $89, $8a, $1e, $81, $b0, $23, $81, $00, $81, $8a, $18, $81, $00, $81, $b0, $23, $85, $8a, $1e, $81, $00, $81
	.byte $b0, $23, $81, $8a, $1e, $81, $12, $81
	.byte $41, $56
	.word @1song1ref702
	.byte $41, $50
	.word @1song1ref708
	.byte $41, $54
	.word @1song1ref704
	.byte $41, $50
	.word @1song1ref708
	.byte $b0, $23, $81, $8c, $12, $b9, $a7, $00
@1song1ch2loop:
	.byte $00, $42
	.word @1song1ch2loop
@1song1ch3:
@1song1ref869:
	.byte $a0, $14, $85, $a2, $21, $85
@1song1ref875:
	.byte $a6, $14, $85, $a2, $21, $81, $a6, $15, $85
@1song1ref884:
	.byte $16, $81, $a0, $14, $85, $a6, $14, $85, $a2, $21, $81, $a6, $14, $81
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
@1song1ref904:
	.byte $a0, $14, $85, $a2, $21, $85, $a6, $14, $85, $a2, $21, $81, $a6, $15, $81, $70, $50, $04, $b0, $8c, $1f, $9d, $7a, $50
	.byte $f9, $10, $1f, $8d, $7f
	.byte $41, $10
	.word @1song1ref875
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $0a
	.word @1song1ref904
	.byte $a0, $14, $81, $14, $81, $14, $85, $a6, $14, $81, $14, $81, $14, $85, $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @1song1ref875
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $0a
	.word @1song1ref904
	.byte $a0, $14, $81, $a6
	.byte $41, $0a
	.word @1song1ref884
	.byte $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @1song1ref875
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @1song1ref875
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $41, $14
	.word @1song1ref869
	.byte $7a, $50, $fe, $00, $8c, $1f, $b7, $85, $a9
@1song1ch3loop:
	.byte $00, $42
	.word @1song1ch3loop
@1song1ch4:
	.byte $51, $47, $33, $bd, $51, $47, $33, $bd, $51, $47, $33, $bd, $51, $47, $33
@1song1ref1103:
	.byte $bd
@1song1ref1104:
	.byte $2d, $95, $2d, $95, $2d, $8d, $87, $33, $8d, $33, $8d
@1song1ref1115:
	.byte $34, $8d, $33, $85, $87, $33, $8d, $33, $8d, $34, $8d, $33, $85, $87, $33, $8d, $33, $8d, $34, $8d, $33, $85
	.byte $41, $0f
	.word @1song1ref1104
	.byte $2d, $a1, $34, $81
	.byte $41, $0d
	.word @1song1ref1115
	.byte $41, $21
	.word @1song1ref1104
	.byte $41, $18
	.word @1song1ref1104
	.byte $2d, $8d, $2d, $8d, $2d, $8d, $2d, $8d, $2d, $95, $01, $a5, $2d, $95, $01, $a5, $2d, $95, $01, $a5, $2d, $8d, $2d, $8d
	.byte $2d, $9d, $2d, $95, $2d, $95, $2d, $8d, $01, $bd, $01, $bd, $01
	.byte $41, $22
	.word @1song1ref1103
	.byte $41, $21
	.word @1song1ref1104
	.byte $8d, $00, $af, $a9
@1song1ch4loop:
	.byte $00, $42
	.word @1song1ch4loop
@1song2ch0:
	.byte $45, $06
@1song2ch0loop:
	.byte $ff, $42
	.word @1song2ch0loop
@1song2ch1:
@1song2ch1loop:
	.byte $ff, $42
	.word @1song2ch1loop
@1song2ch2:
@1song2ch2loop:
	.byte $ff, $42
	.word @1song2ch2loop
@1song2ch3:
@1song2ch3loop:
	.byte $ff, $42
	.word @1song2ch3loop
@1song2ch4:
@1song2ch4loop:
	.byte $ff, $42
	.word @1song2ch4loop
@1song3ch0:
	.byte $45, $02
@1song3ref3:
	.byte $4d, $00, $4e, $00, $9e, $28, $9d, $2b, $9d, $2f, $9d, $2e, $9d, $44, $d1, $28, $81, $28, $81, $28, $81, $28, $8d, $43
	.byte $4f, $18, $34, $19
@1song3ref31:
	.byte $8d, $44, $ad, $4e, $02, $3b, $85, $44, $95, $36, $85, $44, $8d, $3b, $85, $3a, $85, $44, $85, $8f, $36, $85, $44, $8d
	.byte $77, $3b, $85, $3a, $85, $44, $8d, $36, $85, $44, $8d, $74, $3b, $85, $3a, $85, $44, $8d, $7f, $4e, $00, $27, $9d, $2a
	.byte $9d, $2e, $9d, $2d, $9d, $44, $d1, $27, $81, $27, $81, $27, $81, $27, $8d, $43, $4f, $18, $33, $19
	.byte $41, $26
	.word @1song3ref31
@1song3ch0loop:
	.byte $7f
@1song3ref104:
	.byte $4e, $00, $96, $15, $81, $00, $81, $7d, $15, $81, $00, $81, $7b, $15, $81, $00, $81, $79, $15, $81, $00, $81, $7f, $15
	.byte $95, $44, $85, $15, $81, $00, $81, $15, $81, $15, $81, $15, $81, $00, $81, $15, $81, $00, $81, $15, $95, $43, $4f, $3f
	.byte $21, $1b, $85, $9e, $32, $85, $46, $01, $34, $89, $46, $00, $32, $89, $30, $85, $32, $85, $30, $85, $2d, $85, $2b, $85
	.byte $2d, $85, $28, $85, $29, $85, $28, $85, $44, $95, $7a, $50, $fc, $00, $8a, $03, $a5, $d7, $7f, $4d, $00, $4e, $00, $9e
@1song3ref200:
	.byte $26, $85, $28, $81, $44, $81, $2b, $85, $2d, $81, $44, $81, $30, $81, $2d, $81, $2f, $81, $30, $81, $35, $85, $37, $85
	.byte $39, $85, $44, $85, $00, $ad
	.byte $41, $28
	.word @1song3ref104
@1song3ref233:
	.byte $9e, $2f, $85, $46, $01, $30, $89, $46, $00, $2f, $89, $2d, $85, $2f, $85, $2d, $85, $2b, $85, $28, $85, $2b, $85, $27
	.byte $85, $28, $85, $27, $85, $44, $95, $8f, $72, $4e, $03, $8e, $02, $bd, $71, $af, $7f, $4d, $00, $4e, $00, $9e
@1song3ref279:
	.byte $26, $85, $28, $81, $44, $81, $28, $85, $2b, $81, $44, $81, $2d, $81, $2b, $81, $2d, $81, $2f, $81, $2f, $85, $30, $85
	.byte $2f, $85, $44, $85, $00, $ad
	.byte $41, $63
	.word @1song3ref104
	.byte $41, $28
	.word @1song3ref104
	.byte $41, $3c
	.word @1song3ref233
	.byte $79, $50, $ff, $10, $4d, $00, $8a, $09, $fd, $79, $50, $ff, $10, $4d, $00, $10, $f1, $80, $02, $89, $79, $50, $ff, $10
	.byte $4d, $00, $8a, $0f, $fd, $79, $50, $ff, $10, $4d, $00, $0e, $fd, $79, $50, $ff, $10, $4d, $00, $08, $fd, $79, $50, $ff
	.byte $10, $4d, $00, $0f, $fd, $79, $50, $ff, $10, $4d, $00, $0e, $fd, $79, $50, $ff, $30, $4d, $00, $0d, $dd, $7f, $80, $1c
	.byte $8b, $00, $8f, $73, $4d, $00, $8e, $1c, $bd, $1e, $bd, $4d, $00, $21, $bd, $4d, $ff, $87, $4d, $fe, $87, $4d, $fd, $87
	.byte $4d, $fc, $87, $4d, $fb, $87, $4d, $fa, $87, $4d, $f9, $87, $4d, $f8, $87, $4d, $f7, $87, $4d, $f6, $87, $4d, $f5, $87
	.byte $4d, $f4, $87, $4d, $f3, $87, $4d, $f2, $87, $4d, $f1, $87, $4d, $f0, $87, $4d, $ef, $87, $4d, $ee, $87, $4d, $ed, $87
	.byte $4d, $ec, $87, $4d, $eb, $87, $4d, $ea, $87, $4d, $e9, $87, $4d, $e8, $87, $4d, $e7, $87, $4d, $e6, $87, $4d, $e5, $87
	.byte $4d, $e4, $87, $4d, $e3, $87, $4d, $e2, $87, $4d, $e1, $87, $4d, $e0, $87, $4d, $df, $87, $4d, $de, $87, $4d, $dd, $87
	.byte $4d, $dc, $87, $4d, $db, $87, $4d, $da, $87, $4d, $d9, $87, $4d, $d8, $87, $4d, $00, $1b, $bd, $1c, $bd, $20, $bd, $4d
	.byte $00, $87, $4d, $01, $87, $4d, $02, $87, $4d, $03, $87, $4d, $04, $87, $4d, $05, $87, $4d, $06, $87, $4d, $07, $87, $4d
	.byte $08, $87, $4d, $09, $87, $4d, $0a, $87, $4d, $0b, $87, $4d, $0c, $87, $4d, $0d, $87, $4d, $0e, $87, $4d, $0f, $87, $4d
	.byte $10, $87, $4d, $11, $87, $4d, $12, $87, $4d, $13, $87, $4d, $14, $87, $4d, $15, $87, $4d, $16, $87, $4d, $17, $87, $4d
	.byte $18, $87, $4d, $19, $87, $4d, $1a, $87, $4d, $1b, $87, $4d, $1c, $87, $4d, $1d, $87, $4d, $1e, $87, $4d, $1f, $87, $4d
	.byte $20, $87, $4d, $21, $87, $4d, $22, $87, $4d, $23, $87, $4d, $24, $87, $4d, $25, $87, $4d, $26, $87, $4d, $27, $87, $7f
	.byte $41, $4c
	.word @1song3ref3
	.byte $41, $26
	.word @1song3ref31
	.byte $42
	.word @1song3ch0loop
@1song3ch1:
	.byte $4e, $00, $00, $95, $71
@1song3ref668:
	.byte $4d, $01, $8e, $28, $9d, $2b, $9d, $2f, $9d, $2e, $85, $9b, $4d, $00, $00, $b5, $7f, $9e, $27, $81, $27, $81, $27, $81
	.byte $27, $8d, $43, $4f, $13, $33, $19
@1song3ref699:
	.byte $8d, $44, $bd, $71, $4e, $02, $8e, $3b, $85, $00, $95, $36, $85, $00, $8d, $3b, $85, $3a, $85, $00, $95, $36, $85, $00
	.byte $8d, $3b, $85, $3a, $85, $00, $8d, $36, $85, $00, $8d, $3b, $85, $3a, $85, $4e, $00, $00, $95, $4d, $01, $27, $9d, $2a
	.byte $9d, $2e, $9d, $2d, $85, $9b, $4d, $00, $00, $b5, $7f, $9e, $26, $81, $26, $81, $26, $81, $26, $8d, $43, $4f, $13, $32
	.byte $19
	.byte $41, $23
	.word @1song3ref699
@1song3ch1loop:
@1song3ref776:
	.byte $7f, $4e, $00, $96, $10, $81, $00, $81, $7d, $10, $81, $00, $81, $7b, $10, $81, $00, $81, $79, $10, $81, $00, $81, $7f
	.byte $10, $95, $44, $85, $10, $81, $00, $81, $10, $81, $10, $81, $10, $81, $00, $81, $10, $81, $00, $81, $10, $95, $43, $4f
	.byte $54, $1c, $16, $85, $7a, $50, $fc, $30, $8a, $04, $99, $71, $8e, $32, $85, $34, $89, $32, $89, $30, $85, $32, $85, $30
	.byte $85, $2d, $85, $2b, $85, $2d, $85, $28, $85, $29, $85, $28, $81, $8f, $72, $4e, $03, $03, $bd, $71, $af, $7a, $50, $fc
	.byte $40, $8a, $02, $95, $71, $4e, $00, $8e
	.byte $41, $1d
	.word @1song3ref200
	.byte $95
	.byte $41, $28
	.word @1song3ref776
@1song3ref887:
	.byte $7a, $50, $fc, $30, $8a, $03, $99, $71, $8e, $2f, $85, $46, $01, $30, $89, $46, $00, $2f, $89, $2d, $85, $2f, $85, $2d
	.byte $85, $2b, $85, $28, $85, $2b, $85, $27, $85, $28, $85, $27, $81, $7a, $50, $fc, $00, $8a, $02, $a5, $d7, $7a, $50, $fc
	.byte $40, $01, $95, $71, $8e
	.byte $41, $1d
	.word @1song3ref279
	.byte $95
	.byte $41, $48
	.word @1song3ref776
	.byte $71, $4e, $00, $8e
	.byte $41, $1d
	.word @1song3ref200
	.byte $95
	.byte $41, $28
	.word @1song3ref776
	.byte $41, $1f
	.word @1song3ref887
	.byte $71, $8e
	.byte $41, $1d
	.word @1song3ref279
	.byte $95, $bf, $7f, $80, $10, $8d, $13, $8d, $18, $8d, $17, $8d, $df, $13, $9d, $16, $dd, $10, $9d, $0f, $bd, $17, $b5, $16
	.byte $81, $15, $81, $14, $f5, $17, $81, $19, $81, $1b, $f5, $19, $81, $1b, $81, $1c, $b5, $1c, $81, $1f, $81, $21, $b5, $23
	.byte $81, $21, $81, $20, $bd, $00, $9d, $21, $8d, $00, $8d, $78, $8a, $09, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73
	.byte $8f, $72, $8f, $71, $8f, $ff, $78, $09, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff
	.byte $78, $08, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff, $78, $08, $8d, $77, $8f, $76
	.byte $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff, $4e, $00, $00, $95
	.byte $41, $4d
	.word @1song3ref668
	.byte $41, $23
	.word @1song3ref699
	.byte $42
	.word @1song3ch1loop
@1song3ch2:
	.byte $8a, $09, $fd, $ff, $09, $fd, $ff, $08, $fd, $ff, $08, $fd, $ff
@1song3ch2loop:
	.byte $8e
@1song3ref1126:
	.byte $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb
	.byte $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb
	.byte $41, $30
	.word @1song3ref1126
	.byte $41, $30
	.word @1song3ref1126
	.byte $8a, $09, $fd, $09, $fd, $09, $fd, $09, $fd, $08, $fd, $08, $fd, $08, $fd, $08, $fd, $09, $fd, $ff, $09, $fd, $ff, $08
	.byte $fd, $ff, $08, $fd, $08, $fd, $42
	.word @1song3ch2loop
@1song3ch3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $70, $50, $02, $80, $8e, $20, $bd
@1song3ch3loop:
	.byte $7f
@1song3ref1230:
	.byte $a0, $14, $85, $a2, $23, $85, $23, $85, $21, $85, $23, $85, $23, $85, $21, $8d, $a6, $14, $9d, $a2, $21, $85, $23, $85
	.byte $23, $85, $23, $85, $a0, $14, $85, $a2, $23, $85, $23, $85, $21, $85, $23, $85, $23, $85, $21, $8d, $a6, $14, $9d, $a2
	.byte $21, $85, $23, $85, $23, $85, $23, $85
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $41, $30
	.word @1song3ref1230
	.byte $75, $50, $fc, $40, $8e, $1e, $81, $83, $50, $fc, $30, $83, $83, $50, $fc, $20, $83, $83, $50, $fc, $10, $83, $83, $50
	.byte $fc, $00, $83, $db, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $50, $02, $80, $20, $bd
	.byte $42
	.word @1song3ch3loop
@1song3ch4:
	.byte $31, $bd, $31, $9d, $31, $9d, $d3, $37, $a9, $51, $80, $ff, $51, $80, $ff, $31, $bd, $31, $9d, $31, $9d, $d3, $36, $a9
	.byte $51, $80, $ff, $51, $80, $ff
@1song3ch4loop:
@1song3ref1401:
	.byte $32, $85, $31, $85, $31, $85, $32, $85, $31, $85, $31, $85, $32, $8d, $31, $8d, $31, $8d, $32, $85, $31, $85, $31, $85
	.byte $31, $85, $32, $85, $31, $85, $31, $85, $32, $85, $31, $85, $31, $85, $32, $8d, $31, $8d, $31, $8d, $32, $85, $31, $85
	.byte $31, $85, $31, $85
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $2b
	.word @1song3ref1401
	.byte $81, $37, $a1, $31, $85
	.byte $41, $34
	.word @1song3ref1401
	.byte $41, $2b
	.word @1song3ref1401
	.byte $81, $36, $a1, $31, $85
	.byte $41, $34
	.word @1song3ref1401
	.byte $42
	.word @1song3ch4loop
@1song4ch0:
	.byte $45, $06
@1song4ch0loop:
	.byte $ff, $42
	.word @1song4ch0loop
@1song4ch1:
@1song4ch1loop:
	.byte $ff, $42
	.word @1song4ch1loop
@1song4ch2:
@1song4ch2loop:
	.byte $ff, $42
	.word @1song4ch2loop
@1song4ch3:
@1song4ch3loop:
	.byte $ff, $42
	.word @1song4ch3loop
@1song4ch4:
@1song4ch4loop:
	.byte $ff, $42
	.word @1song4ch4loop
@1song5ch0:
	.byte $45, $02
@1song5ch0loop:
	.byte $7f, $4d, $01
@1song5ref7:
	.byte $ac
@1song5ref8:
	.byte $19, $83, $44, $89, $20, $83, $44, $89, $1f, $83, $44, $89, $19, $83, $44, $83, $1c, $83, $44, $89, $1c, $83, $44, $89
	.byte $1c, $83, $44, $89, $1c, $83, $1e, $83, $44, $89, $4d, $01
	.byte $41, $22
	.word @1song5ref8
@1song5ref47:
	.byte $17, $83, $44, $89, $20, $83, $44, $89, $1e, $83, $44, $89, $17, $83, $44, $83, $1b, $83, $44, $89, $1b, $83, $44, $89
	.byte $1b, $83, $44, $89, $1c, $83, $1e, $83, $44, $89, $17, $83, $44, $89, $20, $83, $44, $89, $1e, $83, $44, $89, $17, $83
	.byte $44, $83, $1b, $83, $44, $89, $1e, $83, $44, $89, $20, $83, $44, $89, $23, $83, $25, $83, $44, $89, $4d, $01
	.byte $41, $22
	.word @1song5ref8
	.byte $4d, $01
	.byte $41, $22
	.word @1song5ref8
	.byte $41, $3c
	.word @1song5ref47
	.byte $4f, $7f, $2c, $14, $89, $00, $95, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $8b
	.byte $76, $4d, $ff, $aa
@1song5ref156:
	.byte $2c, $8f, $33, $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $83, $8b, $4d, $ff, $2c, $8f, $33
	.byte $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $83, $8b, $2a, $8f, $33, $8f, $31, $8f, $2a, $89
	.byte $2e, $8f, $2e, $8f, $2e, $8f, $2f, $83, $31, $83, $8b, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f, $31, $8f, $33
	.byte $8f, $36, $83, $38, $83, $8b, $4d, $ff
	.byte $41, $4c
	.word @1song5ref156
	.byte $4d, $ff
	.byte $41, $4b
	.word @1song5ref156
	.byte $42
	.word @1song5ch0loop
@1song5ch1:
@1song5ch1loop:
	.byte $7f, $4d, $ff
	.byte $41, $22
	.word @1song5ref7
	.byte $4d, $ff
	.byte $41, $22
	.word @1song5ref8
	.byte $41, $44
	.word @1song5ref47
	.byte $4d, $ff
	.byte $41, $22
	.word @1song5ref8
	.byte $4d, $ff
	.byte $41, $22
	.word @1song5ref8
	.byte $41, $3c
	.word @1song5ref47
	.byte $4f, $7f, $2c, $14, $89, $00, $95, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $4d
	.byte $00, $aa
@1song5ref301:
	.byte $2c, $8f, $33, $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $8f, $4d, $00, $2c, $8f, $33, $8f
	.byte $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $8f, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f
	.byte $2e, $8f, $2e, $8f, $2f, $83, $31, $8f, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f, $31, $8f, $33, $8f, $36, $83
	.byte $38, $8f, $4d, $00
	.byte $41, $48
	.word @1song5ref301
	.byte $4d, $00
	.byte $41, $48
	.word @1song5ref301
	.byte $42
	.word @1song5ch1loop
@1song5ch2:
@1song5ch2loop:
	.byte $8e
@1song5ref390:
	.byte $1d, $0d, $87, $00, $83, $0d, $89, $00, $83, $47, $02, $25, $00, $8d, $0b, $8f, $1d, $0d, $87, $00, $83, $8a, $0d, $89
	.byte $00, $83, $47, $02, $8e, $25, $00, $9f, $1d, $0d, $87, $00, $83, $0d, $89, $00, $83, $47, $02, $25, $00, $8d, $0b, $8f
	.byte $1d, $0d, $87, $00, $83, $10, $8f, $25, $12, $8d, $14, $8f, $1d, $0b, $87, $00, $83, $0b, $89, $00, $83, $47, $02, $25
	.byte $00, $8d, $0a, $8f, $1d, $0b, $87, $00, $83, $0b, $89, $00, $83, $47, $02, $25, $00, $9f, $1d, $0b, $87, $00, $83, $0b
	.byte $89, $00, $83, $47, $02, $25, $00, $8d, $0a, $8f, $1d, $0b, $8d, $0f, $8f, $25, $12, $8d, $14, $8f
	.byte $41, $66
	.word @1song5ref390
	.byte $41, $66
	.word @1song5ref390
	.byte $41, $66
	.word @1song5ref390
	.byte $41, $66
	.word @1song5ref390
	.byte $41, $66
	.word @1song5ref390
@1song5ref521:
	.byte $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f
	.byte $41, $18
	.word @1song5ref521
	.byte $42
	.word @1song5ch2loop
@1song5ch3:
@1song5ch3loop:
@1song5ref552:
	.byte $a0, $14, $89, $a2, $23, $83, $21, $89, $23, $83, $a6, $14, $89, $a2, $23, $83, $21, $89, $23, $83, $a0, $14, $89, $a2
	.byte $23, $83, $a4, $21, $89, $a2, $23, $83, $a6, $14, $89, $a2, $23, $83, $a4, $21, $89, $a2, $23, $83
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $19
	.word @1song5ref552
	.byte $a1
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $20
	.word @1song5ref552
	.byte $41, $19
	.word @1song5ref552
	.byte $a1, $42
	.word @1song5ch3loop
@1song5ch4:
@1song5ch4loop:
@1song5ref683:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
	.byte $41, $18
	.word @1song5ref683
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $42
	.word @1song5ch4loop
@1song6ch0:
	.byte $45, $02
@1song6ch0loop:
	.byte $7f, $4d, $ff, $98
@1song6ref8:
	.byte $28, $83, $44, $91, $77, $28, $83, $44, $81, $7f, $23, $83, $44, $91, $77, $23, $83, $44, $81, $7f, $27, $83, $44, $91
	.byte $77, $27, $83, $44, $91, $74, $27, $83, $44, $8b, $7f, $4d, $ff
	.byte $41, $1c
	.word @1song6ref8
	.byte $7f, $4d, $ff
	.byte $41, $1c
	.word @1song6ref8
	.byte $7f, $4d, $ff
	.byte $41, $1c
	.word @1song6ref8
	.byte $ff, $9f, $7f, $29, $81, $00, $83, $2b, $81, $00, $83, $4d, $ff, $29, $81, $00, $83, $2b, $81, $00, $83, $29, $81, $00
	.byte $83, $27, $81, $00, $83, $25, $81, $00, $83, $24, $81, $00, $83, $25, $87, $48, .lobyte(@1env43), .hibyte(@1env43), $9d
	.byte $43, $4f, $02, $31, $2f, $a3, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $43, $23, $00, $ff, $9d, $00, $ff, $9d, $86
@1song6ref122:
	.byte $24, $91, $1f, $91, $22, $91, $44, $91, $24, $91, $1f, $91, $22, $91, $44, $91
@1song6ref138:
	.byte $24, $87, $26, $87, $24, $87, $26, $87, $24, $87, $22, $87, $1f, $87, $1d, $87, $1f, $c3, $44, $87
	.byte $41, $20
	.word @1song6ref122
	.byte $20, $87, $4d, $00, $43, $4f, $fb, $2c, $37, $c1, $4e, $03, $43, $2b, $75, $48, .lobyte(@1env0), .hibyte(@1env0), $49
	.byte $8e
@1song6ref181:
	.byte $30, $87, $72, $89, $75, $4f, $0e, $3c, $37, $83, $43, $2b, $81, $72, $89, $75, $4f, $f2, $37, $3a, $81, $43, $2e, $83
	.byte $72, $93, $00, $87, $75, $4e, $03, $30, $87, $72, $89, $75, $4f, $0e, $3c, $37, $83, $43, $2b, $81, $72, $89, $75, $4f
	.byte $f2, $37, $3a, $81, $43, $2e, $83, $72, $93, $00, $87, $75, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $30, $87, $4f
	.byte $f9, $3c, $3e, $81, $43, $32, $83, $4f, $07, $3e, $3c, $81, $43, $30, $83
@1song6ref263:
	.byte $4f, $f9, $3c, $3e, $81, $43, $32, $83, $4f, $07, $3e, $3c, $81, $43, $30, $83, $4f, $08, $3c, $3a, $81, $43, $2e, $83
	.byte $4f, $07, $3a, $37, $85, $43, $2b, $4f, $06, $37, $36, $81, $43, $2a, $83, $4f, $fa, $36, $37, $81, $43, $2b, $8d, $48
	.byte .lobyte(@1env43), .hibyte(@1env43), $b1, $43, $4f, $03, $37, $36, $87, $48, .lobyte(@1env0), .hibyte(@1env0), $49
	.byte $41, $42
	.word @1song6ref181
	.byte $48, .lobyte(@1env0), .hibyte(@1env0), $49
	.byte $41, $1e
	.word @1song6ref181
	.byte $75, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $4f, $f5, $36, $37, $43, $2b, $85, $4f, $f9, $37, $3b, $87, $4f, $f8
	.byte $3b, $3c, $43, $30, $85
	.byte $41, $13
	.word @1song6ref263
	.byte $00, $cd, $48, .lobyte(@1env0), .hibyte(@1env0), $49
	.byte $41, $42
	.word @1song6ref181
	.byte $48, .lobyte(@1env0), .hibyte(@1env0), $49
	.byte $41, $1e
	.word @1song6ref181
	.byte $42
	.word @1song6ch0loop
@1song6ch1:
@1song6ch1loop:
	.byte $ff, $8f, $c7, $70, $50, $02, $90, $92, $04, $c5, $7f, $04, $83, $44, $89, $04, $83, $44, $f5, $c7, $70, $50, $02, $90
	.byte $04, $c5, $7f, $04, $83, $44, $89, $04, $83, $44, $ff, $85, $ff, $9f, $ff, $9f, $ff, $9f, $85, $7a, $50, $02, $f0, $4d
	.byte $00, $86
@1song6ref431:
	.byte $24, $91, $1f, $91, $22, $91, $44, $91, $24, $91, $1f, $91, $22, $91, $44, $8b, $85
	.byte $41, $13
	.word @1song6ref138
	.byte $81, $85, $7a, $50, $02, $f0, $4d, $00
	.byte $41, $11
	.word @1song6ref431
	.byte $41, $10
	.word @1song6ref138
	.byte $20, $87, $43, $4f, $fb, $2c, $35, $bb, $43, $29, $4d, $01, $4e, $03, $8d, $71, $8e, $30, $91, $2b, $91, $2e, $9b, $00
	.byte $87, $30, $91, $2b, $91, $2e, $97, $8f, $30, $87, $32, $87, $30, $87, $32, $87, $30, $87, $2e, $87, $2b, $87, $2a, $87
	.byte $2b, $91, $48, .lobyte(@1env43), .hibyte(@1env43), $ab, $7c, $4d, $00, $92
@1song6ref523:
	.byte $40, $0c, $87, $40, $0c, $87, $00, $87, $40, $0c, $9b, $40, $0a, $91, $40, $0c, $87, $40, $0c, $87, $00, $87, $03, $9b
	.byte $05, $91, $4d, $00
	.byte $41, $14
	.word @1song6ref523
	.byte $4d, $00
	.byte $41, $14
	.word @1song6ref523
	.byte $4d, $00
	.byte $41, $14
	.word @1song6ref523
	.byte $4d, $00
	.byte $41, $14
	.word @1song6ref523
	.byte $4d, $00
	.byte $41, $14
	.word @1song6ref523
	.byte $4d, $00
	.byte $41, $14
	.word @1song6ref523
	.byte $42
	.word @1song6ch1loop
@1song6ch2:
@1song6ch2loop:
	.byte $ff, $8f, $ff, $8f, $8e, $10, $83, $00, $89, $10, $83, $00, $f5, $ff, $8f, $10, $83, $00, $89, $10, $83, $00, $ff, $85
	.byte $ff, $9f
@1song6ref609:
	.byte $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47, $01, $31, $00, $8d, $1d, $47, $01, $2a, $00, $83, $47
	.byte $01, $2a, $00, $85, $1d, $47, $01, $31, $00, $83, $47, $01, $23, $00, $85
	.byte $41, $19
	.word @1song6ref609
	.byte $41, $19
	.word @1song6ref609
@1song6ref654:
	.byte $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47
	.byte $01, $2a, $00, $83, $1d, $47, $01, $2a, $46, $00, $1d, $46, $00, $2a, $00, $1d, $47, $01, $2a, $00, $83, $1d, $47, $01
	.byte $23, $00, $83
	.byte $41, $19
	.word @1song6ref609
	.byte $41, $19
	.word @1song6ref609
	.byte $41, $19
	.word @1song6ref609
	.byte $41, $1f
	.word @1song6ref654
	.byte $41, $19
	.word @1song6ref609
	.byte $41, $19
	.word @1song6ref609
	.byte $41, $19
	.word @1song6ref609
	.byte $41, $19
	.word @1song6ref609
	.byte $ff, $9f, $ff, $9f, $7f
@1song6ref734:
	.byte $4d, $00, $0c, $87, $0c, $87, $00, $87, $0c, $9b, $0a, $91, $0c, $87, $0c, $87, $00, $87, $0f, $9b, $11, $91
	.byte $41, $14
	.word @1song6ref734
	.byte $41, $14
	.word @1song6ref734
	.byte $41, $14
	.word @1song6ref734
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $42
	.word @1song6ch2loop
@1song6ch3:
@1song6ch3loop:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $9f, $ff, $9f, $a0
@1song6ref788:
	.byte $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91
	.byte $14, $91, $14, $91, $14, $87, $14, $81, $46, $00, $14, $83, $14, $87, $14, $87
	.byte $41, $26
	.word @1song6ref788
	.byte $41, $1d
	.word @1song6ref788
	.byte $91, $14, $91, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $cf, $70, $50, $02, $f0, $8e, $21, $cd, $00, $a5, $f7
	.byte $00, $a5, $f7, $00, $a5, $f7, $42
	.word @1song6ch3loop
@1song6ch4:
@1song6ch4loop:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
@1song6ref876:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $10
	.word @1song6ref876
	.byte $ff, $9f, $42
	.word @1song6ch4loop
@1song7ch0:
	.byte $45, $02
@1song7ch0loop:
	.byte $74, $9a
@1song7ref6:
	.byte $1b, $89
@1song7ref8:
	.byte $4f, $80, $27, $2e, $43, $22, $87, $4f, $b9, $2e, $33, $43, $27, $87, $4f, $6b, $33, $27, $81, $43, $1b, $85
	.byte $41, $0a
	.word @1song7ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87
	.byte $41, $0c
	.word @1song7ref6
	.byte $41, $0a
	.word @1song7ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87
	.byte $41, $0c
	.word @1song7ref6
	.byte $41, $0a
	.word @1song7ref8
@1song7ref59:
	.byte $4f, $80, $27, $2e, $43, $22, $87, $4f, $7f, $2e, $25, $43, $19, $87, $4f, $80, $25, $2c, $43, $20, $87, $4f, $b0, $2c
	.byte $31, $43, $25, $87, $4f, $77, $31, $25, $81, $43, $19, $85, $4f, $89, $25, $31, $81, $43, $25, $85, $4f, $50, $31, $2c
	.byte $43, $20, $87, $4f, $7f, $2c, $25, $43, $19, $87, $4f, $80, $25, $2c, $43, $20, $87
	.byte $41, $0c
	.word @1song7ref6
	.byte $41, $0a
	.word @1song7ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87
	.byte $41, $0c
	.word @1song7ref6
	.byte $41, $0a
	.word @1song7ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87
	.byte $41, $0c
	.word @1song7ref6
	.byte $41, $0a
	.word @1song7ref8
	.byte $41, $1d
	.word @1song7ref59
	.byte $4f, $6b, $2c, $27, $43, $1b, $87
	.byte $41, $0a
	.word @1song7ref8
	.byte $41, $0a
	.word @1song7ref8
	.byte $4f, $80, $27, $2e, $43, $22, $87, $4f, $7f, $2e, $27, $43, $1b, $85, $46, $00, $4f, $9a, $27, $2e, $81, $43, $22, $85
	.byte $4f, $b9, $2e, $33, $43, $27, $85, $46, $00, $4f, $7f, $33, $27, $81, $43, $1b, $85, $4f, $80, $27, $2e, $43, $22, $85
	.byte $46, $00, $4f, $80, $2e, $33, $43, $27, $87, $4f, $6b, $33, $27, $81, $43, $1b, $83, $46, $00, $4f, $9a, $27, $2e, $81
	.byte $43, $22, $85, $4f, $7f, $2e, $27, $43, $1b, $85
@1song7ref254:
	.byte $4f, $80, $27, $2e, $43, $22, $85, $4f, $b9, $2e, $33, $43, $27, $85, $4f, $6b, $33, $27, $81, $43, $1b, $83
	.byte $41, $0a
	.word @1song7ref254
	.byte $4f, $80, $27, $2e, $43, $22, $85, $4f, $7f, $2e, $25, $43, $19, $83, $46, $00, $4f, $8e, $25, $2c, $81, $43, $20, $83
	.byte $4f, $b0, $2c, $31, $43, $25, $83, $46, $00, $4f, $7f, $31, $25, $81, $43, $19, $83, $4f, $89, $25, $31, $81, $43, $25
	.byte $81, $46, $00, $4f, $7f, $31, $2c, $43, $20, $85, $4f, $7f, $2c, $25, $43, $19, $83, $46, $00, $4f, $8e, $25, $2c, $81
	.byte $43, $20, $83, $4f, $6b, $2c, $27, $43, $1b, $83
@1song7ref361:
	.byte $4f, $80, $27, $2e, $43, $22, $83, $4f, $b9, $2e, $33, $43, $27, $83, $4f, $6b, $33, $27, $81, $43, $1b, $81
	.byte $41, $0a
	.word @1song7ref361
	.byte $4f, $80, $27, $2e, $43, $22, $83, $4f, $7f, $2e, $27, $43, $1b, $81, $46, $00, $4f, $9a, $27, $2e, $81, $43, $22, $81
	.byte $4f, $b9, $2e, $33, $43, $27, $81, $46, $00, $4f, $7f, $33, $27, $81
@1song7ref424:
	.byte $43, $1b, $81, $4f, $80, $27, $2e, $43, $22, $81, $46, $00, $4f, $80, $2e, $33, $43, $27, $83, $4f, $6b, $33, $27, $81
	.byte $43, $1b, $4f, $80, $27, $2e, $43, $22, $83, $4f, $7f, $2e, $27
	.byte $41, $0d
	.word @1song7ref424
	.byte $81, $46, $00, $4f, $80, $2e, $33, $43, $27, $83, $4f, $6b, $33, $27, $81, $43, $1b, $46, $00, $4f, $9a, $27, $2e, $81
	.byte $43, $22, $73, $8e, $4f, $7f, $2e, $25, $43, $19, $81, $72, $4f, $80, $25, $2c, $43, $20, $81, $71, $4f, $b0, $2c, $31
	.byte $43, $25, $81, $4f, $77, $31, $25, $81, $43, $19, $4f, $89, $25, $31, $81, $43, $25, $4f, $50, $31, $2c, $43, $20, $81
	.byte $72, $4f, $7f, $2c, $25, $43, $19, $81, $73
@1song7ref545:
	.byte $4f, $80, $25, $2c, $43, $20, $81
@1song7ref552:
	.byte $4f, $6b, $2c, $27
@1song7ref556:
	.byte $43, $1b, $46, $00, $4f, $80, $27, $2e, $43, $22, $81, $4f, $b9, $2e, $33, $43, $27, $46, $00, $4f, $7f, $33, $27, $43
	.byte $1b, $81, $4f, $80, $27, $2e, $43, $22, $46, $00, $4f, $80, $2e, $33, $43, $27, $81, $4f, $7f, $33, $27, $43, $1b, $46
	.byte $00, $4f, $80, $27, $2e, $43, $22, $81, $4f, $7f, $2e, $27
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
@1song7ref622:
	.byte $4f, $7f, $2e, $25, $43, $19, $46, $00, $4f, $80, $25, $2c, $43, $20, $81, $4f, $b0, $2c, $31, $43, $25, $46, $00, $4f
	.byte $7f, $31, $25, $43, $19, $81, $4f, $80, $25, $31, $43, $25, $46, $00, $4f, $7f, $31, $2c, $43, $20, $81, $4f, $7f, $2c
	.byte $25, $43, $19, $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
@1song7ref757:
	.byte $46, $00, $4f, $80, $25, $2c, $43, $20, $81, $75, $9a, $4f, $80, $2c, $3a, $43, $2e, $85, $4f, $12, $3a, $38, $43, $2c
	.byte $85, $4f, $ee, $38, $3a, $43, $2e, $85, $4f, $12, $3a, $38, $43, $2c, $85, $4f, $1e, $38, $35, $43, $29, $85, $4f, $f5
	.byte $35, $36, $43, $2a, $85, $4f, $0b, $36, $35, $43, $29, $85, $4f, $32, $35, $31, $43, $25, $85, $4f, $e5, $31, $33, $43
	.byte $27, $85, $4f, $1b, $33, $31, $43, $25, $85, $74, $4f, $e5, $31, $33, $43, $27, $85, $4f, $1b, $33, $31, $43, $25, $85
	.byte $73, $4f, $e5, $31, $33, $43, $27, $85, $4f, $1b, $33, $31, $43, $25, $85, $72, $4f, $e5, $31, $33, $43, $27, $85, $4f
	.byte $1b, $33, $31, $43, $25, $85, $73, $8e
	.byte $41, $15
	.word @1song7ref552
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $46, $00
	.byte $41, $18
	.word @1song7ref545
	.byte $41, $14
	.word @1song7ref556
	.byte $41, $13
	.word @1song7ref556
	.byte $41, $11
	.word @1song7ref622
	.byte $41, $33
	.word @1song7ref757
	.byte $7c, $92
@1song7ref986:
	.byte $4f, $7f, $31, $11, $87, $43, $05
@1song7ref993:
	.byte $44, $85, $05, $43, $05, $85, $44, $87, $05, $43, $05, $85, $05, $43, $05, $85, $4f, $7f, $11, $0f, $43, $03, $85, $4f
	.byte $80, $0f, $11, $43, $05, $85, $44, $87, $4f, $7f, $11, $0f, $43, $03, $85, $4f, $80, $0f, $11, $43, $05, $85, $4f, $80
	.byte $11, $14, $43, $08, $ad, $4f, $7f, $14, $11, $43, $05, $87
	.byte $41, $1b
	.word @1song7ref993
	.byte $4f, $80, $11, $16, $43, $0a, $99, $4f, $84, $16, $18, $43, $0c, $8f
	.byte $41, $21
	.word @1song7ref986
	.byte $42
	.word @1song7ch0loop
@1song7ch1:
@1song7ch1loop:
	.byte $89, $71
@1song7ref1079:
	.byte $4d, $01, $9a
@1song7ref1082:
	.byte $1b, $89, $22, $89, $27, $89, $1b, $89, $22, $89, $27, $89, $1b, $89, $22, $89, $4d, $01
	.byte $41, $10
	.word @1song7ref1082
	.byte $4d, $01
	.byte $41, $10
	.word @1song7ref1082
@1song7ref1108:
	.byte $8e, $19, $89, $20, $89, $25, $89, $19, $89, $25, $89, $20, $89, $19, $89, $20, $89
	.byte $41, $10
	.word @1song7ref1079
	.byte $4d, $01
	.byte $41, $10
	.word @1song7ref1082
	.byte $4d, $01
	.byte $41, $10
	.word @1song7ref1082
	.byte $41, $10
	.word @1song7ref1108
	.byte $41, $10
	.word @1song7ref1079
	.byte $4d, $01
	.byte $41, $0d
	.word @1song7ref1082
	.byte $83, $85, $00, $81, $4d, $01
	.byte $41, $0b
	.word @1song7ref1082
	.byte $87, $81, $00, $85, $4d, $01
	.byte $41, $0c
	.word @1song7ref1082
	.byte $4d, $01
	.byte $41, $09
	.word @1song7ref1082
@1song7ref1172:
	.byte $83, $85, $00, $81, $4d, $01, $1b, $89, $22, $89, $27, $89, $1b, $87, $81, $00, $85, $4d, $01, $1b, $89, $22, $89, $27
	.byte $89, $1b
	.byte $41, $0b
	.word @1song7ref1172
	.byte $7c, $4e, $00, $92
@1song7ref1205:
	.byte $03, $4d, $00
@1song7ref1208:
	.byte $89, $44, $85, $03, $87, $44, $87, $03, $87, $03, $87, $01, $87, $03, $87, $44, $87, $01, $87, $03, $87, $06, $af, $03
	.byte $41, $15
	.word @1song7ref1208
	.byte $08, $9b, $0a, $91, $4e, $00
	.byte $41, $18
	.word @1song7ref1205
	.byte $75, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $9a, $1e, $87, $1d, $87, $1b, $83, $48, .lobyte(@1env7), .hibyte(@1env7)
	.byte $a1, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $1e, $87, $1d, $87, $1e, $87, $1d, $87, $1b, $83, $48, .lobyte(@1env7)
	.byte .hibyte(@1env7), $8d, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $1e, $87, $1d, $87, $1b, $83, $48, .lobyte(@1env7), .hibyte(@1env7)
	.byte $8b, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $81, $4e, $03, $9c
@1song7ref1300:
	.byte $27, $87, $2e, $87, $27, $87, $2e, $87, $72, $27, $87, $2e, $87, $27, $87, $2e, $87, $75, $31, $87, $2e, $87, $31, $87
	.byte $2e, $87, $72, $31, $87, $2e, $87, $31, $87, $2e, $87, $75, $31, $87, $72, $2e, $87, $75, $31, $87, $72, $31, $87, $75
	.byte $2e, $87, $72, $31, $87, $75, $2e, $87, $72, $2e, $87, $75, $33, $87, $72, $2e, $87, $75, $33, $87, $72, $33, $87, $71
	.byte $3f, $81, $46, $00, $72, $3f, $83, $73, $3f, $81, $46, $00, $74, $3f, $83, $75, $3f, $81, $46, $00, $76, $3f, $83, $77
	.byte $3f, $81, $46, $00, $78, $3f, $83, $75, $4e, $03
	.byte $41, $20
	.word @1song7ref1300
	.byte $75, $4e, $03, $9a, $22, $87, $20, $87, $22, $87, $20, $87, $1d, $87, $1e, $87, $1d, $87, $19, $87, $8e, $1b, $87, $48
	.byte .lobyte(@1env43), .hibyte(@1env43), $89, $74, $93, $73, $93, $72, $8f, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $81
	.byte $4e, $02, $81, $7f, $4d, $ff, $94
@1song7ref1454:
	.byte $1b
@1song7ref1455:
	.byte $87, $22, $87, $44, $87, $22, $91, $48, .lobyte(@1env13), .hibyte(@1env13), $93, $48, .lobyte(@1env0), .hibyte(@1env0)
	.byte $49, $44, $87, $25
	.byte $41, $0b
	.word @1song7ref1455
@1song7ref1476:
	.byte $87, $44, $87, $25, $87, $44, $87, $22, $87, $44, $87, $22, $87, $44, $87, $26, $87, $43, $4f, $fe, $32, $33, $87, $48
	.byte .lobyte(@1env50), .hibyte(@1env50), $81, $43, $27, $ad, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $44, $87, $4d, $ff
	.byte $41, $0c
	.word @1song7ref1454
	.byte $41, $0a
	.word @1song7ref1455
@1song7ref1520:
	.byte $28, $81, $43, $4f, $fd, $34, $35, $83, $48, .lobyte(@1env50), .hibyte(@1env50), $83, $43, $29, $83, $48, .lobyte(@1env0)
	.byte .hibyte(@1env0), $49, $44, $87, $2a, $87, $44, $87, $29, $87, $44, $87, $27, $91, $48, .lobyte(@1env50), .hibyte(@1env50)
	.byte $bb, $48, .lobyte(@1env0), .hibyte(@1env0), $49, $44, $87, $4d, $ff
	.byte $41, $0c
	.word @1song7ref1454
	.byte $41, $0b
	.word @1song7ref1455
	.byte $41, $18
	.word @1song7ref1476
	.byte $4d, $ff
	.byte $41, $0c
	.word @1song7ref1454
	.byte $41, $0a
	.word @1song7ref1455
	.byte $41, $16
	.word @1song7ref1520
	.byte $4e, $00, $86
@1song7ref1586:
	.byte $20, $87, $1e, $87, $1d, $87, $1b, $87, $1d, $87, $48, .lobyte(@1env43), .hibyte(@1env43), $89, $44, $91, $48, .lobyte(@1env0)
	.byte .hibyte(@1env0), $49, $20, $87, $1e, $87, $1d, $87, $24, $87, $48, .lobyte(@1env43), .hibyte(@1env43), $93, $44, $87, $48
	.byte .lobyte(@1env0), .hibyte(@1env0), $49, $27, $87, $ff, $9f, $4e, $00
	.byte $41, $1a
	.word @1song7ref1586
	.byte $42
	.word @1song7ch1loop
@1song7ch2:
@1song7ch2loop:
	.byte $00, $dd, $df, $00, $dd, $df, $00, $dd, $df, $00, $dd, $df, $8e, $1d, $00, $ab, $25, $00, $ab, $1d, $00, $a7, $25, $00
	.byte $a7, $1d, $00, $a3, $25, $00, $a3, $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9b, $25, $00, $9b, $1d, $00, $97, $25, $00
	.byte $97, $1d, $00, $95, $25, $00, $95, $1d, $00, $ab
@1song7ref1695:
	.byte $1d, $0f, $87, $00, $85, $25, $0f, $87, $00, $85, $1d, $0f, $83, $00, $0f, $87, $25, $0d, $85, $0f, $87, $1d, $00, $85
	.byte $0d, $87, $25, $0f, $85, $12, $87, $1d, $12, $8f, $25, $12, $8f
	.byte $41, $1d
	.word @1song7ref1695
	.byte $14, $87, $1d, $14, $8f, $25, $16, $8f
	.byte $41, $25
	.word @1song7ref1695
@1song7ref1746:
	.byte $1d, $0d, $a3, $1d, $0d, $a3, $1d, $0c, $8f, $1d, $0c, $8f, $1d, $0b, $85, $1d, $0b, $85, $1d, $0b, $85, $1d, $0b, $85
	.byte $41, $25
	.word @1song7ref1695
	.byte $41, $23
	.word @1song7ref1695
	.byte $14, $8f
	.byte $41, $25
	.word @1song7ref1695
	.byte $41, $18
	.word @1song7ref1746
	.byte $41, $25
	.word @1song7ref1695
	.byte $41, $23
	.word @1song7ref1695
	.byte $14, $8f
	.byte $41, $25
	.word @1song7ref1695
	.byte $1d, $0d, $8f, $25, $0d, $8f, $1d, $0d, $8f, $25, $0d, $8f, $1d, $0c, $8f, $25, $0c, $8f, $1d, $0b, $8f, $25, $0b, $8f
	.byte $41, $25
	.word @1song7ref1695
	.byte $41, $23
	.word @1song7ref1695
	.byte $14, $8f
	.byte $41, $25
	.word @1song7ref1695
	.byte $41, $18
	.word @1song7ref1746
@1song7ref1833:
	.byte $1d, $11, $87, $00, $85, $25, $11, $87, $00, $85, $1d, $11, $83, $00, $11, $87, $25, $0f, $85, $11, $87, $1d, $00, $85
	.byte $0f, $87, $25, $11, $85, $14, $87, $1d, $14, $8f, $25, $14, $8f
	.byte $41, $20
	.word @1song7ref1833
	.byte $16, $8f, $25, $18, $8f
	.byte $41, $25
	.word @1song7ref1833
	.byte $42
	.word @1song7ch2loop
@1song7ch3:
@1song7ch3loop:
	.byte $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $a0, $14, $ad, $a6, $14, $ad, $a0, $14
	.byte $a9, $a6, $14, $a9, $a0, $14, $a5, $a6, $14, $a5, $a0, $14, $a1, $a6, $14, $a1, $a0, $14, $9d, $a6, $14, $9d, $a0, $14
	.byte $99, $a6, $14, $99, $a0, $14, $97, $a6, $14, $97, $a0, $14, $95, $70, $50, $06, $90, $8e, $23, $95, $7f
@1song7ref1954:
	.byte $a0, $14, $91, $a6, $14, $91, $a0, $14, $91, $a6, $14, $91, $a0, $14, $91, $a6, $14, $91
	.byte $41, $0c
	.word @1song7ref1954
	.byte $41, $0c
	.word @1song7ref1954
	.byte $41, $0c
	.word @1song7ref1954
	.byte $a0, $14, $a5, $14, $a5, $14, $91, $14, $91, $14, $87, $14, $87, $14, $87, $14, $87
@1song7ref1998:
	.byte $14, $87, $a2, $21, $87, $a6, $14, $87, $a2, $21, $87, $a0, $14, $81, $46, $00, $a2, $1f, $83, $21, $81, $46, $00, $1f
	.byte $83, $a6, $14, $87, $a2, $21, $87, $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $77, $50, $fe, $00, $a8, $1b, $b5, $bf, $50, $04, $a0, $8e, $21, $a5, $7f, $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $77, $50, $fe, $00, $a8, $1b, $b5, $bf, $50, $04, $a0, $8e, $21, $a5, $7f, $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $a0
	.byte $41, $14
	.word @1song7ref1998
	.byte $42
	.word @1song7ch3loop
@1song7ch4:
@1song7ch4loop:
@1song7ref2163:
	.byte $32, $a1, $32, $a1, $32, $95, $c7, $32, $95
	.byte $41, $09
	.word @1song7ref2163
	.byte $41, $09
	.word @1song7ref2163
	.byte $41, $09
	.word @1song7ref2163
	.byte $df, $d7, $cf, $c7, $bf, $b7, $b3, $af
@1song7ref2189:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $0a
	.word @1song7ref2189
	.byte $41, $0a
	.word @1song7ref2189
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $42
	.word @1song7ch4loop
