; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music1_data_=music1_data_
.endif

music1_data_:
	.byte 8
	.word @instruments
	.word @samples-5
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; 00 : DPCM ALIGNER (NOT FOR PLAYBACK)
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,323,269 ; 01 : Time for a Smackdown!
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,202,168 ; 02 : Pizza Deluxe!
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; 03 : Mondays
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,286,238 ; 04 : Funiculi Holiday
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,215,179 ; 05 : Cold Spaghetti
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256 ; 06 : hmm look what u done did you found a secret :) V2
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256 ; 07 : It's Pizza Time!

.export music1_data_
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env21,@env54,@env34,@env0 ; 00 : 0 12 arp 1
	.word @env12,@env27,@env35,@env0 ; 01 : 5B square lmao.
	.word @env13,@env27,@env6,@env0 ; 02 : A piano
	.word @env50,@env27,@env34,@env0 ; 03 : ah
	.word @env23,@env19,@env37,@env16 ; 04 : Arp Strings
	.word @env18,@env29,@env5,@env0 ; 05 : bass
	.word @env18,@env27,@env34,@env0 ; 06 : blank
	.word @env28,@env27,@env34,@env0 ; 07 : Blank two electric boogaloo
	.word @env44,@env49,@env37,@env16 ; 08 : Chord like arps
	.word @env26,@env27,@env17,@env0 ; 09 : distort guitar
	.word @env24,@env11,@env8,@env0 ; 0a : funny guitar
	.word @env39,@env27,@env37,@env0 ; 0b : funnyclick.mp4
	.word @env46,@env27,@env31,@env0 ; 0c : goofy Synth Bass 
	.word @env30,@env27,@env34,@env0 ; 0d : main
	.word @env42,@env56,@env1,@env0 ; 0e : Music box
	.word @env55,@env33,@env34,@env0 ; 0f : noise (get it) kick
	.word @env20,@env15,@env34,@env0 ; 10 : noise hat
	.word @env22,@env15,@env34,@env0 ; 11 : noise open hat
	.word @env25,@env32,@env34,@env0 ; 12 : noise snare
	.word @env41,@env27,@env35,@env0 ; 13 : Pulse Organ
	.word @env14,@env27,@env7,@env0 ; 14 : secret bell
	.word @env40,@env27,@env37,@env0 ; 15 : secret square
	.word @env51,@env27,@env34,@env3 ; 16 : Short Tri Snare
	.word @env57,@env27,@env34,@env0 ; 17 : Short Triangle Organ
	.word @env53,@env27,@env43,@env0 ; 18 : slightly better electric guitar
	.word @env36,@env45,@env34,@env0 ; 19 : Tri Toms

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c1,$c0,$00,$01
@env2:
	.byte $00,$c0,$bd,$bd,$c0,$c3,$c3,$00,$01
@env3:
	.byte $80,$e0,$00,$01
@env4:
	.byte $00,$c0,$bd,$bb,$ba,$bb,$be,$c2,$c5,$c6,$c5,$c3,$00,$01
@env5:
	.byte $c2,$c3,$00,$01
@env6:
	.byte $c3,$7f,$00,$00
@env7:
	.byte $c2,$c1,$00,$01
@env8:
	.byte $c2,$c0,$00,$01
@env9:
	.byte $00,$c0,$be,$be,$c0,$c2,$c2,$00,$01
@env10:
	.byte $cc,$cc,$c0,$c0,$00,$00
@env11:
	.byte $c7,$c0,$00,$01
@env12:
	.byte $00,$c9,$c6,$c1,$c3,$c4,$c5,$c2,$c3,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0f
@env13:
	.byte $0a,$c9,$c7,$c6,$c5,$c3,$c4,$c3,$00,$07,$c2,$02,$c1,$c1,$00,$0d
@env14:
	.byte $00,$c3,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$09
@env15:
	.byte $be,$c0,$00,$01
@env16:
	.byte $80,$bf,$c0,$c0,$00,$03
@env17:
	.byte $c3,$07,$c2,$07,$c1,$07,$c0,$07,$c1,$07,$c2,$06,$c2,$00,$00
@env18:
	.byte $00,$cf,$7f,$00,$02
@env19:
	.byte $c0,$c0,$b7,$c3,$00,$00
@env20:
	.byte $00,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@env21:
	.byte $00,$c2,$c4,$00,$02
@env22:
	.byte $00,$c5,$c4,$c3,$00,$03
@env23:
	.byte $08,$c1,$1e,$c2,$20,$c2,$00,$05,$c2,$02,$c1,$05,$c0,$00,$0c
@env24:
	.byte $06,$c7,$c5,$c4,$00,$03,$c3,$c2,$c1,$c0,$00,$09
@env25:
	.byte $00,$ca,$c7,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$0b
@env26:
	.byte $06,$cf,$cb,$c8,$00,$03,$c5,$c3,$c2,$c2,$c1,$02,$c0,$c0,$00,$0d
@env27:
	.byte $c0,$7f,$00,$01
@env28:
	.byte $06,$cf,$cf,$cf,$00,$03,$c0,$00,$06
@env29:
	.byte $c5,$c0,$00,$01
@env30:
	.byte $07,$c2,$c4,$c3,$c2,$00,$04,$c1,$02,$c0,$c0,$00,$0a
@env31:
	.byte $c0,$02,$c1,$c1,$c2,$c2,$c3,$00,$06
@env32:
	.byte $c6,$ca,$00,$01
@env33:
	.byte $c6,$cd,$00,$01
@env34:
	.byte $7f,$00,$00
@env35:
	.byte $c2,$7f,$00,$00
@env36:
	.byte $00,$cf,$09,$c0,$00,$03
@env37:
	.byte $c0,$c2,$00,$01
@env38:
	.byte $00,$c0,$bf,$be,$02,$bf,$c1,$c2,$02,$c1,$00,$01
@env39:
	.byte $06,$c3,$c4,$c3,$00,$03,$c2,$c1,$c1,$c0,$00,$09
@env40:
	.byte $0a,$c2,$c3,$c4,$02,$c3,$c3,$c2,$00,$07,$c2,$04,$c1,$07,$c0,$04,$c0,$00,$10
@env41:
	.byte $09,$c4,$c3,$c3,$c4,$c4,$c3,$00,$06,$c2,$c2,$c1,$c1,$c0,$00,$0d
@env42:
	.byte $09,$c8,$cb,$c8,$c7,$c6,$c5,$00,$06,$c4,$c3,$c2,$00,$0b
@env43:
	.byte $c3,$08,$c2,$00,$02
@env44:
	.byte $00,$c2,$0d,$c3,$5b,$c2,$00,$05
@env45:
	.byte $c0,$bd,$ba,$b7,$b4,$b1,$ae,$ab,$a8,$a5,$00,$09
@env46:
	.byte $0b,$c7,$c6,$c6,$c5,$02,$c4,$c4,$c3,$00,$08,$c3,$c2,$c2,$c1,$c1,$c0,$00,$10
@env47:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@env48:
	.byte $00,$c0,$bf,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$c1,$00,$01
@env49:
	.byte $c0,$c0,$c3,$bb,$00,$00
@env50:
	.byte $07,$c2,$c4,$c5,$c4,$00,$04,$c4,$c4,$c3,$04,$c2,$07,$c1,$0a,$c0,$00,$0f
@env51:
	.byte $00,$cf,$05,$c0,$00,$03
@env52:
	.byte $00,$c0,$bf,$02,$c0,$c0,$c1,$c1,$c1,$00,$01
@env53:
	.byte $0d,$ca,$c7,$c6,$c7,$c8,$c7,$c7,$c5,$c5,$c7,$00,$0a,$c5,$c5,$c4,$c3,$c2,$00,$11
@env54:
	.byte $c0,$c0,$cc,$cc,$00,$00
@env55:
	.byte $00,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00,$09
@env56:
	.byte $cc,$c0,$00,$01
@env57:
	.byte $00,$cf,$cf,$c0,$00,$03

@samples:
	.byte $6a+.lobyte(FAMISTUDIO_DPCM_PTR),$12,$4f,$40,$00 ; 00 arpeggiosquare.dmc (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$45,$2e,$01 ; 01 b1 bass.dmc (Pitch:5)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$65,$47,$2e,$01 ; 02 b1 bass.dmc (Pitch:7)
	.byte $52+.lobyte(FAMISTUDIO_DPCM_PTR),$5f,$45,$00,$00 ; 03 b2 bass.dmc (Pitch:5)
	.byte $62+.lobyte(FAMISTUDIO_DPCM_PTR),$5a,$47,$00,$01 ; 04 b3 bass.dmc (Pitch:7)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4a,$00,$00 ; 05 dash.dmc (Pitch:10)
	.byte $3e+.lobyte(FAMISTUDIO_DPCM_PTR),$29,$4d,$00,$00 ; 06 dash.dmc (Pitch:13)
	.byte $79+.lobyte(FAMISTUDIO_DPCM_PTR),$0d,$0f,$40,$00 ; 07 Hebereke Kick.dmc (Pitch:15)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0c,$40,$00 ; 08 Hebereke Snare.dmc (Pitch:12)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0d,$40,$00 ; 09 Hebereke Snare.dmc (Pitch:13)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0e,$40,$00 ; 0a Hebereke Snare.dmc (Pitch:14)
	.byte $49+.lobyte(FAMISTUDIO_DPCM_PTR),$20,$0f,$40,$00 ; 0b Hebereke Snare.dmc (Pitch:15)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$00 ; 0c OrchHitA.dmc (Pitch:7)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$00 ; 0d OrchHitA.dmc (Pitch:8)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$00 ; 0e OrchHitA.dmc (Pitch:10)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$00 ; 0f OrchHitA.dmc (Pitch:11)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$00 ; 10 OrchHitA.dmc (Pitch:12)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 11 OrchHitA.dmc (Pitch:14)
	.byte $2c+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 12 OrchHitA.dmc (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 13 OrchHitF.dmc (Pitch:14)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 14 OrchHitF.dmc (Pitch:15)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$00 ; 15 OrchHitF#.dmc (Pitch:13)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$00 ; 16 OrchHitF#.dmc (Pitch:14)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$00 ; 17 OrchHitF#.dmc (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 18 OrchHitG.dmc (Pitch:1)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$02,$00,$01 ; 19 OrchHitG.dmc (Pitch:2)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 1a OrchHitG.dmc (Pitch:3)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 1b OrchHitG.dmc (Pitch:4)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$05,$00,$01 ; 1c OrchHitG.dmc (Pitch:5)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 1d OrchHitG.dmc (Pitch:6)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 1e OrchHitG.dmc (Pitch:7)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 1f OrchHitG.dmc (Pitch:9)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 20 OrchHitG.dmc (Pitch:10)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 21 OrchHitG.dmc (Pitch:12)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$00,$01 ; 22 OrchHitG.dmc (Pitch:13)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 23 OrchHitG.dmc (Pitch:14)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 24 OrchHitG.dmc (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$01,$00,$01 ; 25 OrchHitG#.dmc (Pitch:1)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$03,$00,$01 ; 26 OrchHitG#.dmc (Pitch:3)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$04,$00,$01 ; 27 OrchHitG#.dmc (Pitch:4)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$06,$00,$01 ; 28 OrchHitG#.dmc (Pitch:6)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$07,$00,$01 ; 29 OrchHitG#.dmc (Pitch:7)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$08,$00,$01 ; 2a OrchHitG#.dmc (Pitch:8)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$09,$00,$01 ; 2b OrchHitG#.dmc (Pitch:9)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0a,$00,$01 ; 2c OrchHitG#.dmc (Pitch:10)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0b,$00,$01 ; 2d OrchHitG#.dmc (Pitch:11)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0c,$00,$01 ; 2e OrchHitG#.dmc (Pitch:12)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0e,$00,$01 ; 2f OrchHitG#.dmc (Pitch:14)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$00,$01 ; 30 OrchHitG#.dmc (Pitch:15)
	.byte $74+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0d,$00,$00 ; 31 Pac_Kick44 (Pitch:13)
	.byte $74+.lobyte(FAMISTUDIO_DPCM_PTR),$14,$0e,$00,$00 ; 32 Pac_Kick44 (Pitch:14)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0d,$00,$00 ; 33 Pac_Kick64 (Pitch:13)
	.byte $6f+.lobyte(FAMISTUDIO_DPCM_PTR),$13,$0e,$00,$00 ; 34 Pac_Kick64 (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$44,$0f,$00,$01 ; 35 taunt.dmc (Pitch:15)
	.byte $0e+.lobyte(FAMISTUDIO_DPCM_PTR),$2f,$07,$00,$00 ; 36 untitled.dmc (Pitch:7)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$34,$08,$00,$00 ; 37 untitled1.dmc (Pitch:8)

@song0ch0:
	.byte $45, $01, $ff, $ff, $ff, $ff
@song0ch0loop:
	.byte $00, $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $ff, $ff, $ff
@song0ch1loop:
	.byte $00, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $ff, $ff, $ff
@song0ch2loop:
	.byte $00, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $ff, $ff
@song0ch3loop:
	.byte $00, $42
	.word @song0ch3loop
@song0ch4:
	.byte $34, $35, $32, $37, $33, $38, $06, $07, $36, $08, $0c, $0b, $0a, $09, $01, $13, $31, $25, $18, $15, $12, $30, $24, $17
	.byte $14, $23, $16, $11, $2f, $22, $10, $2e, $0f, $2d, $21, $2c, $20, $0e, $2b, $0d, $2a, $1f, $29, $1e, $1d, $28, $1c, $27
	.byte $1b, $1a, $26, $19, $05, $03, $04, $02, $00, $ff, $ff, $ff, $8d
@song0ch4loop:
	.byte $00, $42
	.word @song0ch4loop
@song1ch0:
	.byte $45, $03, $4d, $00, $88, $1e, $bd, $bf, $bf, $ab, $44, $85, $4e, $03, $84, $1c, $81, $1e, $81, $21, $81, $23, $95, $25
	.byte $a1, $44
@song1ref27:
	.byte $81, $25, $81, $23, $81, $21, $81, $1e, $81, $1c, $81, $1e, $81, $21, $81, $23, $81, $25, $81, $28, $81, $2a, $81, $2d
	.byte $85, $2a, $81, $2d, $81, $2a, $81, $2f, $a7, $48, .lobyte(@env38), .hibyte(@env38), $8d, $44, $81, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $2a, $81, $2f, $85, $2d, $81, $2a, $81, $28
	.byte $41, $0c
	.word @song1ref27
	.byte $85, $1c, $81, $1e, $85, $1c, $81, $25, $a1, $44, $81, $28, $85, $44, $00, $25, $85, $44, $00, $23, $85, $44, $00, $21
	.byte $85, $44, $00, $20, $85, $2a, $99, $44, $81, $2a, $9d, $44, $81, $00, $81, $2a, $85, $00, $85, $23, $85, $b3, $44, $81
	.byte $00, $85, $7c, $4d, $ff
@song1ref135:
	.byte $82
@song1ref136:
	.byte $19, $85, $1e, $85, $21, $85, $25, $85, $25, $85, $2a, $85, $2d, $85, $31, $85, $4d, $ff
	.byte $41, $10
	.word @song1ref136
@song1ref157:
	.byte $4d, $ff
@song1ref159:
	.byte $19, $85, $1c, $85, $1e, $85, $23, $85, $25, $85, $28, $85, $2a, $85, $2f, $85
	.byte $41, $10
	.word @song1ref157
@song1ref178:
	.byte $4d, $ff
@song1ref180:
	.byte $19, $85, $1e, $85, $25, $85, $28, $85, $25, $85, $2a, $85, $31, $85, $34, $85
	.byte $41, $10
	.word @song1ref178
@song1ref199:
	.byte $4d, $ff
@song1ref201:
	.byte $20, $85, $28, $85, $2a, $85, $2d, $85, $2c, $85, $34, $85, $4d, $ff, $36, $85, $4d, $ff, $39, $85
	.byte $41, $10
	.word @song1ref199
	.byte $4d, $ff
	.byte $41, $10
	.word @song1ref136
	.byte $4d, $ff
	.byte $41, $10
	.word @song1ref136
	.byte $41, $10
	.word @song1ref157
	.byte $41, $10
	.word @song1ref157
	.byte $41, $10
	.word @song1ref178
	.byte $41, $10
	.word @song1ref178
	.byte $41, $10
	.word @song1ref199
	.byte $41, $10
	.word @song1ref199
	.byte $7e, $92, $06, $95, $08, $95, $09, $8d, $87, $0b, $95, $09, $8d, $08, $8d, $7d, $12, $95, $14, $95, $15, $8d, $87, $17
	.byte $95, $7c, $19, $8d, $1c, $8d, $7b, $1e, $95, $20, $95, $21, $8d, $87, $23, $95, $25, $8d, $28, $8b, $44, $7a
@song1ref298:
	.byte $2d, $85
@song1ref300:
	.byte $2c, $85, $2a, $85, $2d, $85, $2c, $85, $2a, $85
	.byte $41, $0c
	.word @song1ref298
	.byte $2d, $85, $2c, $85, $2a, $85, $2d, $85, $2a, $91, $48, .lobyte(@env48), .hibyte(@env48), $ab, $83, $43, $4f, $0b, $36
	.byte $25, $83, $44, $9d
@song1ch0loop:
	.byte $00, $42
	.word @song1ch0loop
@song1ch1:
	.byte $4d, $00, $88, $19, $bd, $bf, $bf, $bf, $90, $1e, $bd, $bf, $20, $bd, $bf, $7b, $25, $bd, $9f, $84, $25, $99, $44, $81
	.byte $25, $9d, $44, $81, $00, $81, $25, $85, $00, $85, $20, $85, $b3, $44, $81, $00, $85, $8b, $79, $4d, $fe
	.byte $41, $0d
	.word @song1ref135
	.byte $81, $4d, $fe, $83, $31, $85
	.byte $41, $0d
	.word @song1ref136
	.byte $81, $83, $31, $85, $4d, $fe
	.byte $41, $0d
	.word @song1ref159
	.byte $81, $83, $4d, $fe, $2f, $85
	.byte $41, $0d
	.word @song1ref159
	.byte $81, $4d, $fe, $83, $aa, $2f, $85
	.byte $41, $0d
	.word @song1ref180
	.byte $81, $4d, $fe, $83, $82, $34, $85
	.byte $41, $0d
	.word @song1ref180
	.byte $81, $4d, $fe, $83, $34, $85, $4d, $fe
	.byte $41, $0d
	.word @song1ref201
	.byte $81, $4d, $fe, $83, $39, $85, $4d, $fe
	.byte $41, $0d
	.word @song1ref201
	.byte $81, $7d, $4d, $00, $b0
@song1ref463:
	.byte $21, $87, $44, $81, $00, $1c, $87, $44, $81, $00, $1e, $8d, $48, .lobyte(@env4), .hibyte(@env4), $89, $44, $81, $48
	.byte .lobyte(@env0), .hibyte(@env0), $49, $81, $21, $83, $44, $1c, $85, $44, $81, $00, $81, $1e, $85, $44, $81, $00, $81
	.byte $21, $85, $44, $81, $00, $81, $23, $85, $85, $44, $21, $83, $44, $23, $83, $44, $21, $83, $44, $23, $83, $44, $25, $83
	.byte $44, $23, $83, $44, $21, $85, $87, $48, .lobyte(@env4), .hibyte(@env4), $8f, $44, $81, $00, $81, $48, .lobyte(@env0)
	.byte .hibyte(@env0), $49, $1c, $9d, $4d, $00
	.byte $41, $42
	.word @song1ref463
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49, $81, $2a, $87, $48, .lobyte(@env4), .hibyte(@env4), $93, $44, $77, $8b, $48
	.byte .lobyte(@env0), .hibyte(@env0), $49, $92, $06, $95, $08, $95, $09, $81, $93, $0b, $95, $09, $8d, $08, $81, $8b, $12
	.byte $95, $14, $95, $15, $81, $91, $17, $95, $19, $8d, $1c, $83, $76, $89, $1e, $95, $20, $95, $21, $83, $99, $23, $95, $25
	.byte $89, $44, $8b
	.byte $41, $0c
	.word @song1ref298
	.byte $2d, $81, $83
	.byte $41, $0a
	.word @song1ref300
	.byte $2d, $85, $2c, $85, $2a, $81, $1e, $91, $48, .lobyte(@env48), .hibyte(@env48), $ab, $83, $43, $4f, $11, $2a, $1c, $83
	.byte $44, $9d
@song1ch1loop:
	.byte $00, $42
	.word @song1ch1loop
@song1ch2:
	.byte $8a
@song1ref648:
	.byte $12, $85, $1e, $81, $12, $85, $1e, $81, $15, $85, $12, $85, $21, $85, $12, $89, $00, $81
	.byte $41, $0b
	.word @song1ref648
	.byte $89, $00, $81, $12, $89, $00, $81
	.byte $41, $0b
	.word @song1ref648
	.byte $89, $00, $81, $12, $89, $00, $81, $0e, $85, $1a, $81, $0e, $85, $1a, $81, $12, $85, $0e, $89, $00, $81, $0e, $89
@song1ref702:
	.byte $00, $81
@song1ref704:
	.byte $b2
@song1ref705:
	.byte $23, $8d, $8a
@song1ref708:
	.byte $1e, $83, $00, $14, $8b, $00, $20, $83, $00, $15, $87, $00, $15, $81, $1a, $83, $00, $21, $83, $00, $19, $83, $00, $23
	.byte $81, $17, $83, $00, $1e, $81, $15, $83, $00, $10, $81, $00, $81, $12, $85, $1a, $85, $23, $81, $00, $81, $1c, $87, $00
	.byte $1a, $89, $19, $85, $17, $8d, $15, $89, $1e, $81, $14, $81, $00, $81, $18, $81, $00, $81, $12, $85, $1e, $81, $00, $81
	.byte $12, $81, $1e, $81, $12, $81, $00, $81, $12, $8d
	.byte $41, $42
	.word @song1ref708
	.byte $b2, $2e, $81, $2e, $81, $2e, $85, $28, $81, $28, $81, $28, $85
	.byte $41, $54
	.word @song1ref705
	.byte $41, $36
	.word @song1ref708
	.byte $b2, $23, $89, $8a, $1e, $81, $b2, $23, $81, $00, $81, $8a, $18, $81, $00, $81, $b2, $23, $85, $8a, $1e, $81, $00, $81
	.byte $b2, $23, $81, $8a, $1e, $81, $12, $81
	.byte $41, $56
	.word @song1ref702
	.byte $41, $50
	.word @song1ref708
	.byte $41, $54
	.word @song1ref704
	.byte $41, $50
	.word @song1ref708
	.byte $b2, $23, $81, $8c, $12, $b9, $a9
@song1ch2loop:
	.byte $00, $42
	.word @song1ch2loop
@song1ch3:
@song1ref868:
	.byte $9e, $14, $85, $a0, $21, $85
@song1ref874:
	.byte $a4, $14, $85, $a0, $21, $81, $a4, $15, $85
@song1ref883:
	.byte $16, $81, $9e, $14, $85, $a4, $14, $85, $a0, $21, $81, $a4, $14, $81
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
@song1ref903:
	.byte $9e, $14, $85, $a0, $21, $85, $a4, $14, $85, $a0, $21, $81, $a4, $15, $81, $70, $50, $04, $b0, $8c, $1f, $9d, $7a, $50
	.byte $f9, $10, $1f, $8d, $7f
	.byte $41, $10
	.word @song1ref874
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $0a
	.word @song1ref903
	.byte $9e, $14, $81, $14, $81, $14, $85, $a4, $14, $81, $14, $81, $14, $85, $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @song1ref874
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $0a
	.word @song1ref903
	.byte $9e, $14, $81, $a4
	.byte $41, $0a
	.word @song1ref883
	.byte $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @song1ref874
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $7a, $50, $f9, $10, $8c, $1f, $8d, $7f
	.byte $41, $10
	.word @song1ref874
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $41, $14
	.word @song1ref868
	.byte $7a, $50, $fe, $00, $8c, $1f, $b7, $85, $00, $a7
@song1ch3loop:
	.byte $00, $42
	.word @song1ch3loop
@song1ch4:
	.byte $51, $47, $34, $bd, $51, $47, $34, $bd, $51, $47, $34, $bd, $51, $47, $34
@song1ref1103:
	.byte $bd
@song1ref1104:
	.byte $2e, $95, $2e, $95, $2e, $8d, $87, $34, $8d, $34, $8d
@song1ref1115:
	.byte $35, $8d, $34, $85, $87, $34, $8d, $34, $8d, $35, $8d, $34, $85, $87, $34, $8d, $34, $8d, $35, $8d, $34, $85
	.byte $41, $0f
	.word @song1ref1104
	.byte $2e, $a1, $35, $81
	.byte $41, $0d
	.word @song1ref1115
	.byte $41, $21
	.word @song1ref1104
	.byte $41, $18
	.word @song1ref1104
	.byte $2e, $8d, $2e, $8d, $2e, $8d, $2e, $8d, $2e, $95, $01, $a5, $2e, $95, $01, $a5, $2e, $95, $01, $a5, $2e, $8d, $2e, $8d
	.byte $2e, $9d, $2e, $95, $2e, $95, $2e, $8d, $01, $bd, $01, $bd, $01
	.byte $41, $22
	.word @song1ref1103
	.byte $41, $21
	.word @song1ref1104
	.byte $8d, $00, $af, $a9
@song1ch4loop:
	.byte $00, $42
	.word @song1ch4loop
@song2ch0:
	.byte $45, $02
@song2ch0loop:
	.byte $7f, $98
@song2ref6:
	.byte $0d, $85, $44, $87, $10, $83, $0d
@song2ref13:
	.byte $83, $08, $83, $44, $83, $0d, $83, $44, $83, $0b, $83, $44, $83, $09, $8f, $44, $89, $0d, $85, $44, $87, $10, $83, $0d
	.byte $83, $44, $83, $08, $83, $44, $83, $0d
@song2ref45:
	.byte $85, $09, $81, $0b, $85, $44, $81, $09, $8d, $44, $85, $0d, $85, $44, $87, $10, $83, $0d, $85, $44, $87, $0d, $83, $44
	.byte $41, $12
	.word @song2ref45
	.byte $83, $44, $83, $08, $83, $44, $83, $0d, $85
@song2ref81:
	.byte $7c, $0f, $0d, $7f, $0b, $85, $44, $81, $09, $85, $44, $81, $08, $85, $44, $81
	.byte $41, $39
	.word @song2ref6
	.byte $41, $32
	.word @song2ref13
	.byte $41, $21
	.word @song2ref13
	.byte $41, $0e
	.word @song2ref81
	.byte $0d, $83, $0b, $85, $44, $81, $0d, $85, $44, $9b, $0b, $81, $0d, $83, $44, $10, $85, $44, $81, $0d, $81, $10, $85, $0d
	.byte $81, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $00, $dd, $00, $dd, $00, $dd, $00, $dd, $00, $dd, $af, $4d, $00, $a6
@song2ref152:
	.byte $2c, $2a, $28, $27, $25, $81, $23, $81, $21, $81, $20, $81, $1e, $89, $1c, $89, $48, .lobyte(@env9), .hibyte(@env9)
	.byte $17, $c5, $00, $89, $17, $89, $48, .lobyte(@env9), .hibyte(@env9), $16, $c5, $00, $89, $16, $89, $48, .lobyte(@env9)
	.byte .hibyte(@env9), $17, $d7, $00, $83, $48, .lobyte(@env9), .hibyte(@env9), $16, $ad, $4d, $00, $48, .lobyte(@env0), .hibyte(@env0)
	.byte $49
	.byte $41, $10
	.word @song2ref152
	.byte $00, $dd, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $00, $dd, $00, $dd, $48, .lobyte(@env52), .hibyte(@env52), $93, $8e, $31, $81, $34, $83, $00, $36, $85, $00, $36, $38
	.byte $af, $00, $31, $85, $00, $89, $31, $81, $34, $83, $00, $36, $83, $00, $83, $3b, $89, $39, $81, $38, $36, $83, $38, $83
	.byte $36, $83, $38, $89, $34, $81, $81, $8c, $31, $87, $34, $83, $00, $83, $36, $89, $34, $83, $00, $36, $38, $ab, $00, $81
	.byte $98, $36, $89, $34, $89, $31, $89, $2f, $89
@song2ref289:
	.byte $ae, $38, $36, $98, $34, $ae, $33, $98, $31, $81, $2f, $81, $2d, $81, $2c, $81, $2a, $89, $28, $89, $48, .lobyte(@env2)
	.byte .hibyte(@env2), $8e, $20, $c5, $00, $89, $20, $89, $48, .lobyte(@env2), .hibyte(@env2), $1e, $c5, $00, $89, $1e, $89
	.byte $48, .lobyte(@env2), .hibyte(@env2), $20, $d7, $00, $83, $48, .lobyte(@env2), .hibyte(@env2), $1e, $ad, $48, .lobyte(@env52)
	.byte .hibyte(@env52)
	.byte $41, $10
	.word @song2ref289
	.byte $00, $dd, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $df, $df, $df, $df, $df, $df
@song2ref358:
	.byte $9e, $14, $89, $a0, $21, $89, $a4, $14, $89, $a0, $21, $85, $21, $81, $9e, $14, $89, $a0, $21, $89, $a4, $14, $89, $a0
	.byte $21, $85, $1f, $81
	.byte $41, $14
	.word @song2ref358
	.byte $41, $14
	.word @song2ref358
	.byte $41, $14
	.word @song2ref358
	.byte $df, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $51, $bf, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $df, $42
	.word @song2ch4loop
@song3ch0:
	.byte $45, $02
@song3ref3:
	.byte $4d, $00, $4e, $00, $9a, $28, $9d, $2b, $9d, $2f, $9d, $2e, $9d, $44, $d1, $28, $81, $28, $81, $28, $81, $28, $8d, $43
	.byte $4f, $18, $34, $19
@song3ref31:
	.byte $8d, $44, $ad, $4e, $02, $3b, $85, $44, $95, $36, $85, $44, $8d, $3b, $85, $3a, $85, $44, $85, $8f, $36, $85, $44, $8d
	.byte $77, $3b, $85, $3a, $85, $44, $8d, $36, $85, $44, $8d, $74, $3b, $85, $3a, $85, $44, $8d, $7f, $4e, $00, $27, $9d, $2a
	.byte $9d, $2e, $9d, $2d, $9d, $44, $d1, $27, $81, $27, $81, $27, $81, $27, $8d, $43, $4f, $18, $33, $19
	.byte $41, $26
	.word @song3ref31
@song3ch0loop:
	.byte $7f
@song3ref104:
	.byte $4e, $00, $94, $15, $81, $00, $81, $7d, $15, $81, $00, $81, $7b, $15, $81, $00, $81, $79, $15, $81, $00, $81, $7f, $15
	.byte $95, $44, $85, $15, $81, $00, $81, $15, $81, $15, $81, $15, $81, $00, $81, $15, $81, $00, $81, $15, $95, $43, $4f, $3f
	.byte $21, $1b, $85, $9a, $32, $85, $46, $01, $34, $89, $46, $00, $32, $89, $30, $85, $32, $85, $30, $85, $2d, $85, $2b, $85
	.byte $2d, $85, $28, $85, $29, $85, $28, $85, $44, $95, $7a, $50, $fc, $00, $8a, $03, $a5, $d7, $7f, $4d, $00, $4e, $00, $9a
@song3ref200:
	.byte $26, $85, $28, $81, $44, $81, $2b, $85, $2d, $81, $44, $81, $30, $81, $2d, $81, $2f, $81, $30, $81, $35, $85, $37, $85
	.byte $39, $85, $44, $85, $00, $ad
	.byte $41, $28
	.word @song3ref104
@song3ref233:
	.byte $9a, $2f, $85, $46, $01, $30, $89, $46, $00, $2f, $89, $2d, $85, $2f, $85, $2d, $85, $2b, $85, $28, $85, $2b, $85, $27
	.byte $85, $28, $85, $27, $85, $44, $95, $8f, $72, $4e, $03, $8c, $02, $bd, $71, $af, $7f, $4d, $00, $4e, $00, $9a
@song3ref279:
	.byte $26, $85, $28, $81, $44, $81, $28, $85, $2b, $81, $44, $81, $2d, $81, $2b, $81, $2d, $81, $2f, $81, $2f, $85, $30, $85
	.byte $2f, $85, $44, $85, $00, $ad
	.byte $41, $63
	.word @song3ref104
	.byte $41, $28
	.word @song3ref104
	.byte $41, $3c
	.word @song3ref233
	.byte $79, $50, $ff, $10, $4d, $00, $8a, $09, $fd, $79, $50, $ff, $10, $4d, $00, $10, $f1, $80, $02, $89, $79, $50, $ff, $10
	.byte $4d, $00, $8a, $0f, $fd, $79, $50, $ff, $10, $4d, $00, $0e, $fd, $79, $50, $ff, $10, $4d, $00, $08, $fd, $79, $50, $ff
	.byte $10, $4d, $00, $0f, $fd, $79, $50, $ff, $10, $4d, $00, $0e, $fd, $79, $50, $ff, $30, $4d, $00, $0d, $dd, $7f, $80, $1c
	.byte $8b, $00, $8f, $73, $4d, $00, $8c, $1c, $bd, $1e, $bd, $4d, $00, $21, $bd, $4d, $ff, $87, $4d, $fe, $87, $4d, $fd, $87
	.byte $4d, $fc, $87, $4d, $fb, $87, $4d, $fa, $87, $4d, $f9, $87, $4d, $f8, $87, $4d, $f7, $87, $4d, $f6, $87, $4d, $f5, $87
	.byte $4d, $f4, $87, $4d, $f3, $87, $4d, $f2, $87, $4d, $f1, $87, $4d, $f0, $87, $4d, $ef, $87, $4d, $ee, $87, $4d, $ed, $87
	.byte $4d, $ec, $87, $4d, $eb, $87, $4d, $ea, $87, $4d, $e9, $87, $4d, $e8, $87, $4d, $e7, $87, $4d, $e6, $87, $4d, $e5, $87
	.byte $4d, $e4, $87, $4d, $e3, $87, $4d, $e2, $87, $4d, $e1, $87, $4d, $e0, $87, $4d, $df, $87, $4d, $de, $87, $4d, $dd, $87
	.byte $4d, $dc, $87, $4d, $db, $87, $4d, $da, $87, $4d, $d9, $87, $4d, $d8, $87, $4d, $00, $1b, $bd, $1c, $bd, $20, $bd, $4d
	.byte $00, $87, $4d, $01, $87, $4d, $02, $87, $4d, $03, $87, $4d, $04, $87, $4d, $05, $87, $4d, $06, $87, $4d, $07, $87, $4d
	.byte $08, $87, $4d, $09, $87, $4d, $0a, $87, $4d, $0b, $87, $4d, $0c, $87, $4d, $0d, $87, $4d, $0e, $87, $4d, $0f, $87, $4d
	.byte $10, $87, $4d, $11, $87, $4d, $12, $87, $4d, $13, $87, $4d, $14, $87, $4d, $15, $87, $4d, $16, $87, $4d, $17, $87, $4d
	.byte $18, $87, $4d, $19, $87, $4d, $1a, $87, $4d, $1b, $87, $4d, $1c, $87, $4d, $1d, $87, $4d, $1e, $87, $4d, $1f, $87, $4d
	.byte $20, $87, $4d, $21, $87, $4d, $22, $87, $4d, $23, $87, $4d, $24, $87, $4d, $25, $87, $4d, $26, $87, $4d, $27, $87, $7f
	.byte $41, $4c
	.word @song3ref3
	.byte $41, $26
	.word @song3ref31
	.byte $42
	.word @song3ch0loop
@song3ch1:
	.byte $4e, $00, $00, $95, $71
@song3ref668:
	.byte $4d, $01, $8c, $28, $9d, $2b, $9d, $2f, $9d, $2e, $85, $9b, $4d, $00, $00, $b5, $7f, $9a, $27, $81, $27, $81, $27, $81
	.byte $27, $8d, $43, $4f, $13, $33, $19
@song3ref699:
	.byte $8d, $44, $bd, $71, $4e, $02, $8c, $3b, $85, $00, $95, $36, $85, $00, $8d, $3b, $85, $3a, $85, $00, $95, $36, $85, $00
	.byte $8d, $3b, $85, $3a, $85, $00, $8d, $36, $85, $00, $8d, $3b, $85, $3a, $85, $4e, $00, $00, $95, $4d, $01, $27, $9d, $2a
	.byte $9d, $2e, $9d, $2d, $85, $9b, $4d, $00, $00, $b5, $7f, $9a, $26, $81, $26, $81, $26, $81, $26, $8d, $43, $4f, $13, $32
	.byte $19
	.byte $41, $23
	.word @song3ref699
@song3ch1loop:
@song3ref776:
	.byte $7f, $4e, $00, $94, $10, $81, $00, $81, $7d, $10, $81, $00, $81, $7b, $10, $81, $00, $81, $79, $10, $81, $00, $81, $7f
	.byte $10, $95, $44, $85, $10, $81, $00, $81, $10, $81, $10, $81, $10, $81, $00, $81, $10, $81, $00, $81, $10, $95, $43, $4f
	.byte $54, $1c, $16, $85, $7a, $50, $fc, $30, $8a, $04, $99, $71, $8c, $32, $85, $34, $89, $32, $89, $30, $85, $32, $85, $30
	.byte $85, $2d, $85, $2b, $85, $2d, $85, $28, $85, $29, $85, $28, $81, $8f, $72, $4e, $03, $03, $bd, $71, $af, $7a, $50, $fc
	.byte $40, $8a, $02, $95, $71, $4e, $00, $8c
	.byte $41, $1d
	.word @song3ref200
	.byte $95
	.byte $41, $28
	.word @song3ref776
@song3ref887:
	.byte $7a, $50, $fc, $30, $8a, $03, $99, $71, $8c, $2f, $85, $46, $01, $30, $89, $46, $00, $2f, $89, $2d, $85, $2f, $85, $2d
	.byte $85, $2b, $85, $28, $85, $2b, $85, $27, $85, $28, $85, $27, $81, $7a, $50, $fc, $00, $8a, $02, $a5, $d7, $7a, $50, $fc
	.byte $40, $01, $95, $71, $8c
	.byte $41, $1d
	.word @song3ref279
	.byte $95
	.byte $41, $48
	.word @song3ref776
	.byte $71, $4e, $00, $8c
	.byte $41, $1d
	.word @song3ref200
	.byte $95
	.byte $41, $28
	.word @song3ref776
	.byte $41, $1f
	.word @song3ref887
	.byte $71, $8c
	.byte $41, $1d
	.word @song3ref279
	.byte $95, $bf, $7f, $80, $10, $8d, $13, $8d, $18, $8d, $17, $8d, $df, $13, $9d, $16, $dd, $10, $9d, $0f, $bd, $17, $b5, $16
	.byte $81, $15, $81, $14, $f5, $17, $81, $19, $81, $1b, $f5, $19, $81, $1b, $81, $1c, $b5, $1c, $81, $1f, $81, $21, $b5, $23
	.byte $81, $21, $81, $20, $bd, $00, $9d, $21, $8d, $00, $8d, $78, $8a, $09, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73
	.byte $8f, $72, $8f, $71, $8f, $ff, $78, $09, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff
	.byte $78, $08, $8d, $77, $8f, $76, $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff, $78, $08, $8d, $77, $8f, $76
	.byte $8f, $75, $8f, $74, $8f, $73, $8f, $72, $8f, $71, $8f, $ff, $4e, $00, $00, $95
	.byte $41, $4d
	.word @song3ref668
	.byte $41, $23
	.word @song3ref699
	.byte $42
	.word @song3ch1loop
@song3ch2:
	.byte $8a, $09, $fd, $ff, $09, $fd, $ff, $08, $fd, $ff, $08, $fd, $ff
@song3ch2loop:
	.byte $8c
@song3ref1126:
	.byte $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb, $1d, $15, $bb, $25, $15, $bb
	.byte $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb, $1d, $14, $bb, $25, $14, $bb
	.byte $41, $30
	.word @song3ref1126
	.byte $41, $30
	.word @song3ref1126
	.byte $8a, $09, $fd, $09, $fd, $09, $fd, $09, $fd, $08, $fd, $08, $fd, $08, $fd, $08, $fd, $09, $fd, $ff, $09, $fd, $ff, $08
	.byte $fd, $ff, $08, $fd, $08, $fd, $42
	.word @song3ch2loop
@song3ch3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $70, $50, $02, $80, $8c, $20, $bd
@song3ch3loop:
	.byte $7f
@song3ref1230:
	.byte $9e, $14, $85, $a0, $23, $85, $23, $85, $21, $85, $23, $85, $23, $85, $21, $8d, $a4, $14, $9d, $a0, $21, $85, $23, $85
	.byte $23, $85, $23, $85, $9e, $14, $85, $a0, $23, $85, $23, $85, $21, $85, $23, $85, $23, $85, $21, $8d, $a4, $14, $9d, $a0
	.byte $21, $85, $23, $85, $23, $85, $23, $85
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $41, $30
	.word @song3ref1230
	.byte $75, $50, $fc, $40, $8c, $1e, $81, $83, $50, $fc, $30, $83, $83, $50, $fc, $20, $83, $83, $50, $fc, $10, $83, $83, $50
	.byte $fc, $00, $83, $db, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf, $50, $02, $80, $20, $bd
	.byte $42
	.word @song3ch3loop
@song3ch4:
	.byte $32, $bd, $32, $9d, $32, $9d, $d3, $38, $a9, $51, $80, $ff, $51, $80, $ff, $32, $bd, $32, $9d, $32, $9d, $d3, $37, $a9
	.byte $51, $80, $ff, $51, $80, $ff
@song3ch4loop:
@song3ref1401:
	.byte $35, $85, $34, $85, $34, $85, $35, $85, $34, $85, $34, $85, $35, $8d, $34, $8d, $34, $8d, $35, $85, $34, $85, $34, $85
	.byte $34, $85, $35, $85, $34, $85, $34, $85, $35, $85, $34, $85, $34, $85, $35, $8d, $34, $8d, $34, $8d, $35, $85, $34, $85
	.byte $34, $85, $34, $85
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
	.byte $41, $34
	.word @song3ref1401
@song3ref1486:
	.byte $33, $85, $32, $85, $32, $85, $33, $85, $32, $85, $32, $85, $33, $8d, $32, $8d, $32, $8d, $33, $85, $32, $85, $32, $85
	.byte $32, $85, $33, $85, $32, $85, $32, $85, $33, $85, $32, $85, $32, $85, $33, $8d, $32, $8d, $32, $8d, $33, $85, $32, $85
	.byte $32, $85, $32, $85
	.byte $41, $34
	.word @song3ref1486
	.byte $41, $34
	.word @song3ref1486
	.byte $41, $34
	.word @song3ref1486
	.byte $41, $2b
	.word @song3ref1486
	.byte $81, $38, $a1, $32, $85
	.byte $41, $34
	.word @song3ref1486
	.byte $41, $2b
	.word @song3ref1486
	.byte $81, $37, $a1, $32, $85
	.byte $41, $34
	.word @song3ref1486
	.byte $42
	.word @song3ch4loop
@song4ch0:
	.byte $45, $03
@song4ch0loop:
	.byte $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $9c
@song4ref13:
	.byte $34, $89, $44, $81, $32, $89, $44, $81, $34, $89, $44, $81, $32, $89, $44, $81, $35, $85, $44, $34, $83, $32, $85, $44
	.byte $35, $83, $34, $8f, $44, $85, $00, $83
	.byte $41, $20
	.word @song4ref13
	.byte $41, $20
	.word @song4ref13
	.byte $41, $1a
	.word @song4ref13
@song4ref54:
	.byte $30, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d
	.byte $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $2d, $85, $44, $2d, $83, $35, $8f, $44, $85, $00, $83, $37, $85
	.byte $44, $35, $83, $32, $85, $44, $35, $83, $30, $85, $44, $2e, $83, $2d, $85, $44, $2e, $83, $30, $85, $44, $2e, $83, $2d
	.byte $85, $44, $2b, $83, $29, $8b, $44, $35, $85, $44, $85, $00, $bd, $bf, $bf, $bf, $bf, $bf, $bf, $bf
	.byte $41, $20
	.word @song4ref13
	.byte $41, $20
	.word @song4ref13
	.byte $41, $20
	.word @song4ref13
	.byte $41, $1a
	.word @song4ref13
	.byte $41, $5c
	.word @song4ref54
	.byte $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $4b, $7e, $81, $00, $8b, $84
@song4ref171:
	.byte $29, $81, $44, $81, $00, $29, $81, $44, $81, $00, $8b, $29, $81, $44, $81, $00, $85, $8f, $29, $81, $44, $81, $00, $29
	.byte $81, $44, $81, $00, $8b, $32, $81, $44, $81, $00, $30, $81, $44, $81, $00, $8b
	.byte $41, $28
	.word @song4ref171
	.byte $41, $28
	.word @song4ref171
	.byte $41, $28
	.word @song4ref171
	.byte $41, $28
	.word @song4ref171
	.byte $41, $28
	.word @song4ref171
	.byte $41, $28
	.word @song4ref171
	.byte $41, $28
	.word @song4ref171
	.byte $26, $81, $44, $81, $00, $26, $81, $44, $81, $00, $85, $29, $81, $44, $81, $00, $85, $29, $81, $44, $81, $00, $8b, $26
	.byte $81, $44, $81, $00, $26, $81, $44, $29, $81, $44, $81, $00, $85, $26, $81, $44, $81, $00, $85, $8f, $2b, $81, $44, $81
	.byte $00, $2b, $81, $44, $81, $00, $8b, $2b, $81, $44, $81, $00, $85, $2b, $81, $44, $81, $00, $85, $2c, $81, $44, $81, $00
	.byte $85, $2d, $81, $44, $81, $00, $95, $7f, $4a, .lobyte(@env10), .hibyte(@env10)
@song4ref315:
	.byte $1f, $81, $44, $81, $00, $85, $4c, $1f, $81, $44, $81, $00, $85, $4c, $1d, $81, $44, $81, $4c, $1d, $81, $44, $81, $00
	.byte $8d, $4c, $1f, $81, $44, $81, $00, $85, $4c, $1f, $81, $44, $81, $4c, $1f, $81, $44, $81, $00, $85, $4c, $1c, $81, $44
	.byte $81, $4c, $1c, $81, $44, $81, $00, $85, $4c
	.byte $41, $30
	.word @song4ref315
	.byte $4c
	.byte $41, $30
	.word @song4ref315
	.byte $4c
	.byte $41, $30
	.word @song4ref315
	.byte $4c
	.byte $41, $30
	.word @song4ref315
	.byte $4c
	.byte $41, $30
	.word @song4ref315
	.byte $4c
	.byte $41, $30
	.word @song4ref315
	.byte $4c
	.byte $41, $30
	.word @song4ref315
	.byte $4c
	.byte $41, $26
	.word @song4ref315
	.byte $4c, $1d, $8d, $44, $85, $4c, $1d, $95, $44, $85, $4c, $1f, $95, $44, $85, $4c, $1d, $83, $44, $83, $00, $81, $4c, $1f
	.byte $83, $44, $83, $00, $81, $4c, $1c, $44, $83, $4c, $1c, $44, $83, $00, $8d, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $bf, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $8c
@song4ref455:
	.byte $11, $8d, $00, $87, $ac, $29, $83, $8c, $18, $8d, $ac, $29, $8d, $8c, $11, $8d, $00, $87, $ac, $29, $83, $8c, $18, $85
	.byte $00, $85, $ac, $29, $8c, $10, $83, $00, $85
	.byte $41, $19
	.word @song4ref455
	.byte $41, $19
	.word @song4ref455
	.byte $41, $19
	.word @song4ref455
	.byte $41, $19
	.word @song4ref455
	.byte $41, $19
	.word @song4ref455
	.byte $41, $19
	.word @song4ref455
	.byte $41, $19
	.word @song4ref455
	.byte $1a, $8d, $00, $87, $ac, $29, $83, $8c, $15, $8d, $ac, $29, $8d, $8c, $1a, $8d, $00, $87, $ac, $29, $83, $8c, $15, $8d
	.byte $ac, $29, $8d, $8c, $13, $8d, $00, $87, $ac, $29, $83, $8c, $17, $8d, $ac, $29, $8d, $8c, $1b, $87, $00, $83, $1c, $87
	.byte $ac, $29, $83, $8c, $1d, $8d, $ac, $29, $8d, $8c
@song4ref567:
	.byte $11, $8d, $00, $8d, $18, $8d, $00, $8d, $11, $8d, $00, $8d, $18, $85, $00, $85, $10, $85, $00, $85, $11, $8d, $00, $8d
	.byte $18, $8d, $00, $8d, $11, $8d, $00, $8d, $18, $85, $00, $85, $10, $85, $00, $85
	.byte $41, $28
	.word @song4ref567
	.byte $41, $28
	.word @song4ref567
	.byte $41, $28
	.word @song4ref567
	.byte $1a, $8d, $00, $8d, $15, $8d, $00, $8d, $1a, $8d, $00, $8d, $15, $8d, $00, $8d, $13, $8d, $00, $8d, $15, $8d, $00, $8d
	.byte $13, $87, $00, $83, $15, $87, $00, $83, $11, $8d, $00, $8d
	.byte $41, $28
	.word @song4ref567
	.byte $41, $28
	.word @song4ref567
	.byte $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $7f
@song4ref663:
	.byte $9e, $14, $8d, $a2, $1f, $81, $50, $e2, $30, $83, $81, $7f, $a4, $14, $83, $a0, $21, $87, $21, $83, $a4, $14, $8d, $9e
	.byte $14, $8d, $a2, $1f, $81, $50, $e2, $30, $83, $81, $7f, $a4, $14, $83, $a0, $21, $87, $21, $83, $a4, $14, $8d
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
@song4ref736:
	.byte $9e, $14, $85, $a0, $21, $85, $a4, $14, $85, $14, $81, $14, $81, $a0, $21, $81, $a4, $14, $81, $14, $85, $14, $81, $14
	.byte $81, $14, $81, $14, $81, $9e, $14, $85, $a0, $21, $85, $a4, $14, $85, $14, $81, $14, $81, $a0, $21, $81, $a4, $14, $81
	.byte $14, $85, $14, $81, $14, $81, $14, $81, $14, $81
	.byte $41, $30
	.word @song4ref736
	.byte $41, $30
	.word @song4ref736
	.byte $41, $30
	.word @song4ref736
	.byte $41, $30
	.word @song4ref736
	.byte $41, $30
	.word @song4ref736
	.byte $41, $30
	.word @song4ref736
	.byte $41, $30
	.word @song4ref736
	.byte $41, $30
	.word @song4ref736
	.byte $41, $30
	.word @song4ref736
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $41, $1c
	.word @song4ref663
	.byte $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
@song4ref837:
	.byte $35, $8d, $35, $8d, $35, $87, $35, $93, $35, $8d, $35, $8d, $35, $87, $35, $93, $35, $8d, $35, $8d, $35, $87, $35, $93
	.byte $35, $8d, $35, $8d, $35, $87, $35, $93
	.byte $41, $20
	.word @song4ref837
	.byte $41, $20
	.word @song4ref837
	.byte $41, $20
	.word @song4ref837
	.byte $41, $20
	.word @song4ref837
@song4ref881:
	.byte $08, $8d, $35, $85, $35, $81, $35, $85, $35, $81, $35, $85, $35, $81, $35, $81, $35, $81, $35, $81, $08, $8d, $35, $85
	.byte $35, $81, $35, $85, $35, $81, $35, $85, $35, $81, $35, $81, $35, $81, $35, $81
	.byte $41, $28
	.word @song4ref881
	.byte $41, $28
	.word @song4ref881
	.byte $41, $28
	.word @song4ref881
	.byte $41, $28
	.word @song4ref881
	.byte $41, $28
	.word @song4ref881
	.byte $41, $28
	.word @song4ref881
	.byte $41, $28
	.word @song4ref881
	.byte $41, $28
	.word @song4ref881
	.byte $41, $28
	.word @song4ref881
	.byte $41, $20
	.word @song4ref837
	.byte $41, $20
	.word @song4ref837
	.byte $42
	.word @song4ch4loop
@song5ch0:
	.byte $45, $02
@song5ch0loop:
	.byte $ff, $42
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $8c, $25, $83, $44, $83, $2c, $f1, $42
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
	.byte $ff, $42
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
	.byte $ff, $42
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $ff, $42
	.word @song5ch4loop
@song6ch0:
	.byte $45, $02
@song6ch0loop:
	.byte $7f, $4d, $01
@song6ref7:
	.byte $aa
@song6ref8:
	.byte $19, $83, $44, $89, $20, $83, $44, $89, $1f, $83, $44, $89, $19, $83, $44, $83, $1c, $83, $44, $89, $1c, $83, $44, $89
	.byte $1c, $83, $44, $89, $1c, $83, $1e, $83, $44, $89, $4d, $01
	.byte $41, $22
	.word @song6ref8
@song6ref47:
	.byte $17, $83, $44, $89, $20, $83, $44, $89, $1e, $83, $44, $89, $17, $83, $44, $83, $1b, $83, $44, $89, $1b, $83, $44, $89
	.byte $1b, $83, $44, $89, $1c, $83, $1e, $83, $44, $89, $17, $83, $44, $89, $20, $83, $44, $89, $1e, $83, $44, $89, $17, $83
	.byte $44, $83, $1b, $83, $44, $89, $1e, $83, $44, $89, $20, $83, $44, $89, $23, $83, $25, $83, $44, $89, $4d, $01
	.byte $41, $22
	.word @song6ref8
	.byte $4d, $01
	.byte $41, $22
	.word @song6ref8
	.byte $41, $3c
	.word @song6ref47
	.byte $4f, $7f, $2c, $14, $89, $00, $95, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $8b
	.byte $76, $4d, $ff, $a8
@song6ref156:
	.byte $2c, $8f, $33, $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $83, $8b, $4d, $ff, $2c, $8f, $33
	.byte $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $83, $8b, $2a, $8f, $33, $8f, $31, $8f, $2a, $89
	.byte $2e, $8f, $2e, $8f, $2e, $8f, $2f, $83, $31, $83, $8b, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f, $31, $8f, $33
	.byte $8f, $36, $83, $38, $83, $8b, $4d, $ff
	.byte $41, $4c
	.word @song6ref156
	.byte $4d, $ff
	.byte $41, $4b
	.word @song6ref156
	.byte $42
	.word @song6ch0loop
@song6ch1:
@song6ch1loop:
	.byte $7f, $4d, $ff
	.byte $41, $22
	.word @song6ref7
	.byte $4d, $ff
	.byte $41, $22
	.word @song6ref8
	.byte $41, $44
	.word @song6ref47
	.byte $4d, $ff
	.byte $41, $22
	.word @song6ref8
	.byte $4d, $ff
	.byte $41, $22
	.word @song6ref8
	.byte $41, $3c
	.word @song6ref47
	.byte $4f, $7f, $2c, $14, $89, $00, $95, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $4d
	.byte $00, $a8
@song6ref301:
	.byte $2c, $8f, $33, $8f, $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $8f, $4d, $00, $2c, $8f, $33, $8f
	.byte $32, $8f, $2c, $89, $2f, $8f, $2f, $8f, $2f, $8f, $2f, $83, $31, $8f, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f
	.byte $2e, $8f, $2e, $8f, $2f, $83, $31, $8f, $2a, $8f, $33, $8f, $31, $8f, $2a, $89, $2e, $8f, $31, $8f, $33, $8f, $36, $83
	.byte $38, $8f, $4d, $00
	.byte $41, $48
	.word @song6ref301
	.byte $4d, $00
	.byte $41, $48
	.word @song6ref301
	.byte $42
	.word @song6ch1loop
@song6ch2:
@song6ch2loop:
	.byte $8c
@song6ref390:
	.byte $1d, $0d, $87, $00, $83, $0d, $89, $00, $83, $47, $02, $25, $00, $8d, $0b, $8f, $1d, $0d, $87, $00, $83, $8a, $0d, $89
	.byte $00, $83, $47, $02, $8c, $25, $00, $9f, $1d, $0d, $87, $00, $83, $0d, $89, $00, $83, $47, $02, $25, $00, $8d, $0b, $8f
	.byte $1d, $0d, $87, $00, $83, $10, $8f, $25, $12, $8d, $14, $8f, $1d, $0b, $87, $00, $83, $0b, $89, $00, $83, $47, $02, $25
	.byte $00, $8d, $0a, $8f, $1d, $0b, $87, $00, $83, $0b, $89, $00, $83, $47, $02, $25, $00, $9f, $1d, $0b, $87, $00, $83, $0b
	.byte $89, $00, $83, $47, $02, $25, $00, $8d, $0a, $8f, $1d, $0b, $8d, $0f, $8f, $25, $12, $8d, $14, $8f
	.byte $41, $66
	.word @song6ref390
	.byte $41, $66
	.word @song6ref390
	.byte $41, $66
	.word @song6ref390
	.byte $41, $66
	.word @song6ref390
	.byte $41, $66
	.word @song6ref390
@song6ref521:
	.byte $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f, $1d, $00, $9f, $25, $00, $9f
	.byte $41, $18
	.word @song6ref521
	.byte $42
	.word @song6ch2loop
@song6ch3:
@song6ch3loop:
@song6ref552:
	.byte $9e, $14, $89, $a0, $23, $83, $21, $89, $23, $83, $a4, $14, $89, $a0, $23, $83, $21, $89, $23, $83, $9e, $14, $89, $a0
	.byte $23, $83, $a2, $21, $89, $a0, $23, $83, $a4, $14, $89, $a0, $23, $83, $a2, $21, $89, $a0, $23, $83
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $19
	.word @song6ref552
	.byte $a1
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $20
	.word @song6ref552
	.byte $41, $19
	.word @song6ref552
	.byte $a1, $42
	.word @song6ch3loop
@song6ch4:
@song6ch4loop:
@song6ref683:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
	.byte $41, $18
	.word @song6ref683
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $42
	.word @song6ch4loop
@song7ch0:
	.byte $45, $02
@song7ch0loop:
	.byte $7f, $4d, $ff, $96
@song7ref8:
	.byte $28, $83, $44, $91, $79, $28, $83, $44, $81, $7f, $23, $83, $44, $89, $79, $28, $83, $44, $23, $83, $44, $81, $7f, $27
	.byte $83, $44, $89, $79, $23, $85, $27, $83, $44, $89, $77, $23, $85, $27, $83, $44, $8b, $7f, $4d, $ff
	.byte $41, $23
	.word @song7ref8
	.byte $7f, $4d, $ff
	.byte $41, $23
	.word @song7ref8
	.byte $7f, $4d, $ff
	.byte $41, $23
	.word @song7ref8
	.byte $00, $ff, $9d, $7f, $4d, $fe, $29, $44, $81, $00, $81, $2b, $44, $81, $00, $81, $4d, $fe, $29, $44, $81, $00, $81, $2b
	.byte $44, $81, $00, $81, $29, $44, $81, $00, $81, $4d, $fe, $27, $44, $81, $00, $81, $24, $44, $81, $00, $81, $23, $44, $81
	.byte $00, $81, $25, $87, $48, .lobyte(@env47), .hibyte(@env47), $9d, $43, $4f, $02, $31, $2f, $a3, $48, .lobyte(@env0), .hibyte(@env0)
	.byte $49, $43, $23, $00, $ff, $9d, $00, $ff, $9d, $4d, $ff, $86
@song7ref144:
	.byte $24, $91, $1f, $91, $22, $91, $44, $91, $24, $91, $1f, $91, $22, $91, $44, $91
@song7ref160:
	.byte $24, $87, $26, $87, $24, $87, $26, $87, $24, $87, $22, $87, $1f, $87, $1d, $87, $1f, $c3, $44, $87, $4d, $ff
	.byte $41, $20
	.word @song7ref144
	.byte $20, $87, $4d, $00, $43, $4f, $fb, $2c, $37, $c1, $4e, $03, $43, $2b, $75, $48, .lobyte(@env0), .hibyte(@env0), $49
	.byte $8c
@song7ref205:
	.byte $30, $87, $72, $89, $75, $4f, $0e, $3c, $37, $83, $43, $2b, $81, $72, $89, $75, $4f, $f2, $37, $3a, $81, $43, $2e, $83
	.byte $72, $93, $00, $87, $75, $4e, $03, $30, $87, $72, $89, $75, $4f, $0e, $3c, $37, $83, $43, $2b, $81, $72, $89, $75, $4f
	.byte $f2, $37, $3a, $81, $43, $2e, $83, $72, $93, $00, $87, $75, $48, .lobyte(@env0), .hibyte(@env0), $49, $30, $87, $4f
	.byte $f9, $3c, $3e, $81, $43, $32, $83, $4f, $07, $3e, $3c, $81, $43, $30, $83
@song7ref287:
	.byte $4f, $f9, $3c, $3e, $81, $43, $32, $83, $4f, $07, $3e, $3c, $81, $43, $30, $83, $4f, $08, $3c, $3a, $81, $43, $2e, $83
	.byte $4f, $07, $3a, $37, $85, $43, $2b, $4f, $06, $37, $36, $81, $43, $2a, $83, $4f, $fa, $36, $37, $81, $43, $2b, $8d, $48
	.byte .lobyte(@env47), .hibyte(@env47), $b1, $43, $4f, $03, $37, $36, $87, $48, .lobyte(@env0), .hibyte(@env0), $49
	.byte $41, $42
	.word @song7ref205
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49
	.byte $41, $1e
	.word @song7ref205
	.byte $75, $48, .lobyte(@env0), .hibyte(@env0), $49, $4f, $f5, $36, $37, $43, $2b, $85, $4f, $f9, $37, $3b, $87, $4f, $f8
	.byte $3b, $3c, $43, $30, $85
	.byte $41, $13
	.word @song7ref287
	.byte $00, $cd, $48, .lobyte(@env0), .hibyte(@env0), $49
	.byte $41, $42
	.word @song7ref205
	.byte $48, .lobyte(@env0), .hibyte(@env0), $49
	.byte $41, $1e
	.word @song7ref205
	.byte $42
	.word @song7ch0loop
@song7ch1:
@song7ch1loop:
	.byte $ff, $8f, $c7, $70, $50, $02, $90, $92, $04, $c5, $7f, $04, $83, $44, $89, $04, $83, $44, $f5, $c7, $70, $50, $02, $90
	.byte $04, $c5, $7f, $04, $83, $44, $89, $04, $83, $44, $ff, $85, $ff, $9f, $ff, $9f, $ff, $9f, $85, $7a, $50, $02, $f0, $4d
	.byte $00, $86
@song7ref455:
	.byte $24, $91, $1f, $91, $22, $91, $44, $91, $24, $91, $1f, $91, $22, $91, $44, $8b, $85
	.byte $41, $13
	.word @song7ref160
	.byte $81, $85, $7a, $50, $02, $f0, $4d, $00
	.byte $41, $11
	.word @song7ref455
	.byte $41, $10
	.word @song7ref160
	.byte $20, $87, $43, $4f, $fb, $2c, $35, $bb, $43, $29, $4d, $01, $4e, $03, $8d, $71, $8c, $30, $91, $2b, $91, $2e, $9b, $00
	.byte $87, $30, $91, $2b, $91, $2e, $97, $8f, $30, $87, $32, $87, $30, $87, $32, $87, $30, $87, $2e, $87, $2b, $87, $2a, $87
	.byte $2b, $91, $48, .lobyte(@env47), .hibyte(@env47), $ab, $7c, $4d, $00, $92
@song7ref547:
	.byte $40, $0c, $87, $40, $0c, $87, $00, $87, $40, $0c, $9b, $40, $0a, $91, $40, $0c, $87, $40, $0c, $87, $00, $87, $03, $9b
	.byte $05, $91, $4d, $00
	.byte $41, $14
	.word @song7ref547
	.byte $4d, $00
	.byte $41, $14
	.word @song7ref547
	.byte $4d, $00
	.byte $41, $14
	.word @song7ref547
	.byte $4d, $00
	.byte $41, $14
	.word @song7ref547
	.byte $4d, $00
	.byte $41, $14
	.word @song7ref547
	.byte $4d, $00
	.byte $41, $14
	.word @song7ref547
	.byte $42
	.word @song7ch1loop
@song7ch2:
@song7ch2loop:
	.byte $ff, $8f, $ff, $8f, $8c, $10, $83, $00, $89, $10, $83, $00, $f5, $ff, $8f, $10, $83, $00, $89, $10, $83, $00, $ff, $85
	.byte $ff, $9f
@song7ref633:
	.byte $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47, $01, $31, $00, $8d, $1d, $47, $01, $2a, $00, $83, $47
	.byte $01, $2a, $00, $85, $1d, $47, $01, $31, $00, $83, $47, $01, $23, $00, $85
	.byte $41, $19
	.word @song7ref633
	.byte $41, $19
	.word @song7ref633
@song7ref678:
	.byte $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47, $01, $2a, $00, $83, $47, $01, $2a, $00, $85, $1d, $47
	.byte $01, $2a, $00, $83, $1d, $47, $01, $2a, $46, $00, $1d, $46, $00, $2a, $00, $1d, $47, $01, $2a, $00, $83, $1d, $47, $01
	.byte $23, $00, $83
	.byte $41, $19
	.word @song7ref633
	.byte $41, $19
	.word @song7ref633
	.byte $41, $19
	.word @song7ref633
	.byte $41, $1f
	.word @song7ref678
	.byte $41, $19
	.word @song7ref633
	.byte $41, $19
	.word @song7ref633
	.byte $41, $19
	.word @song7ref633
	.byte $41, $19
	.word @song7ref633
	.byte $ff, $9f, $ff, $9f, $7f
@song7ref758:
	.byte $4d, $00, $0c, $87, $0c, $87, $00, $87, $0c, $9b, $0a, $91, $0c, $87, $0c, $87, $00, $87, $0f, $9b, $11, $91
	.byte $41, $14
	.word @song7ref758
	.byte $41, $14
	.word @song7ref758
	.byte $41, $14
	.word @song7ref758
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $42
	.word @song7ch2loop
@song7ch3:
@song7ch3loop:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f, $ff, $9f, $ff, $9f, $9e
@song7ref812:
	.byte $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91, $14, $91
	.byte $14, $91, $14, $91, $14, $87, $14, $81, $46, $00, $14, $83, $14, $87, $14, $87
	.byte $41, $26
	.word @song7ref812
	.byte $41, $1d
	.word @song7ref812
	.byte $91, $14, $91, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $cf, $70, $50, $02, $f0, $8c, $21, $cd, $00, $a5, $f7
	.byte $00, $a5, $f7, $00, $a5, $f7, $42
	.word @song7ch3loop
@song7ch4:
@song7ch4loop:
	.byte $ff, $8f, $ff, $8f, $ff, $8f, $ff, $8f
@song7ref900:
	.byte $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f, $ff, $9f
	.byte $41, $10
	.word @song7ref900
	.byte $ff, $9f, $42
	.word @song7ch4loop
