; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_sfx_dash_1
	.word @sfx_ntsc_sfx_dash2_1
	.word @sfx_ntsc_sfx_taunt_1

@sfx_ntsc_sfx_dash_1:
	.byte $89,$f0,$00
@sfx_ntsc_sfx_dash2_1:
	.byte $89,$f0,$00
@sfx_ntsc_sfx_taunt_1:
	.byte $89,$f0,$00

.export sounds
