;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2
	.word @sfx_ntsc_3
@pal:
	.word @sfx_pal_0
	.word @sfx_pal_1
	.word @sfx_pal_2
	.word @sfx_pal_3

@sfx_ntsc_0:
	.byte $86,$81,$87,$8e,$88,$00,$01,$87,$1c,$88,$01,$01,$87,$8e,$88,$00
	.byte $02,$00
@sfx_pal_0:
	.byte $86,$81,$87,$84,$88,$00,$01,$87,$08,$88,$01,$01,$87,$84,$88,$00
	.byte $02,$00
@sfx_ntsc_1:
	.byte $86,$81,$87,$1c,$88,$01,$03,$87,$8e,$88,$00,$03,$87,$46,$03,$00
@sfx_pal_1:
	.byte $86,$81,$87,$08,$88,$01,$03,$87,$84,$88,$00,$02,$87,$41,$03,$00
@sfx_ntsc_2:
	.byte $86,$81,$87,$46,$88,$00,$02,$87,$6a,$02,$87,$46,$02,$87,$6a,$02
	.byte $87,$46,$02,$00
@sfx_pal_2:
	.byte $86,$81,$87,$41,$88,$00,$02,$87,$62,$02,$87,$41,$01,$87,$62,$02
	.byte $87,$41,$02,$00
@sfx_ntsc_3:
	.byte $86,$81,$87,$1c,$88,$01,$01,$87,$8e,$88,$00,$01,$00
@sfx_pal_3:
	.byte $86,$81,$87,$08,$88,$01,$01,$87,$84,$88,$00,$01,$00
